### PR TITLE
Split huge interpreter source file into translation info and interpreter (+ some tiny misc style fixes)

### PR DESCRIPTION
**Pull request by archshift**
Two 2500-3000 line files are still more palatable than a 6000 line file!

### CODE REVIEW

**Comment by lioncash** [comment]
Looks fine

**Comment by mailwl** [comment]
with this PR latest master games stop working for me at all. (even Zelda:OOT).
looks like interpreter try to execute data

**Comment by wwylele** [comment]
Same here. Can we first revert this? It is too big to review.

**Comment by JamePeng** [comment]
look like the latest master cause a big bug with all of game
qq 20160610210054

**Comment by MoochMcGee** [comment]
ABORT ABORT

**Pull request merged**
