### PR TITLE
frontend: Add setting for whether to use LLE applets.

### PR DESCRIPTION
**Pull request by Steveice10**
Adds a setting to configure whether to use LLE applets, so that users with system firmware installed can choose not to use them.

Off by default as HLE applets are often more convenient, e.g. you can actually use your keyboard for typing.

New UI:

Screenshot 2024-01-12 at 2 56 21 PM

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7345)

### CODE REVIEW

**Comment by PabloMK7** [comment]
Are you sure you want this off by default? The only advantage I see for this is the keyboard applet, but doesn't apply to others like the mii selector.

**Comment by Steveice10** [comment]
> Are you sure you want this off by default? The only advantage I see for this is the keyboard applet, but doesn't apply to others like the mii selector.

It preserves behavior from the default state when the user does not have firmware installed, so I think it makes sense to default to off. Open to changing it if most people feel that it should be the other way though.

**Comment by DaniElectra** [comment]
I think this is reasonable, but we could maybe add individual toggles like on LLE services?

**Comment by Steveice10** [comment]
> I think this is reasonable, but we could maybe add individual toggles like on LLE services?

Sure, but such a UI is not something I have plans to work on. I think at least having a simple toggle is a good start as opposed to having no control at all.

**Review by GPUCode — APPROVED** [review]

**Pull request merged**
