### PR TITLE
DiskDirectory: Initialize the directory member with valid info.

### PR DESCRIPTION
**Pull request by Subv**

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2015-12-25T22:04:24Z: https://github.com/citra-emu/citra/compare/031443199bf5df2fc1f840793b36b975a61a5596...Subv:b910fa55b1c56de1b2653a235f7f60984bc107a9

**Comment by yuriks** [comment]
Needs a rebase.

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-01-16T14:31:20Z: https://github.com/citra-emu/citra/compare/7b2d03476985ca3747350d195c32654a371ee85b...Subv:922b31ebbdc6d8cbfe76bebbaa158cf16b9e7b0c

**Comment by Subv** [comment]
Updated

**Comment by yuriks** [comment]
What is this doing, exactly?

**Comment by yuriks** [comment]
LGTM

**Comment by bunnei** [comment]
Somehow I missed this one in the sea of stale PRs

**Pull request merged**
