### PR TITLE
HLE/IPC: clean up System::GetInstance

### PR DESCRIPTION
**Pull request by wwylele**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4617)

### CODE REVIEW

**Comment by wwylele** [comment]
Update: reset IPC header to param = 1 for unimplemented function to avoid translating garbage in the command buffer (which is introduced in this PR due to copying the entire buffer)

**Comment by mspass** [comment]
i get this log after canary 1201 with System Settings and Kirby: Planet Robot:

Debug <Critical> core/hle/kernel/hle_ipc.cpp:operator():224: Assertion Failed!
Unsupported handle translation: 0X00000020

and this with Nintendo 3DS Sound:
Debug <Critical> core/hle/kernel/hle_ipc.cpp:operator():79: Assertion Failed!

**Comment by wwylele** [comment]
@mspass It was just fixed. Please test canary 1205

**Comment by wwylele** [comment]
Will merge soon if no more comments

**Pull request merged**
