### PR TITLE
core: Eliminate more uses of Core::System::GetInstance().

### PR DESCRIPTION
**Pull request by Steveice10**
Eliminates some more uses of `Core::System::GetInstance()` across the codebase, including but not limited to the following:
* Changed `Memory::RasterizerFlushVirtualRegion` from a static function to an instance function of `MemorySystem`, to utilize its `System` instance.
* Refactored HLE applet management into `AppletManager` instead of using static state, to eliminate some more global state and utilize its `System` instance.
* Added `System` parameter to app loader constructors. Note this was not a complete elimination, just refactoring it out to a single use in the `GetLoader` function for now instead of multiple scattered usages.
* Added `System` parameter to a few services, fixed up their serialization as needed, and eliminated some static state.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7313)

### CODE REVIEW

**Review by GPUCode — APPROVED** [review]
Awesome, thanks!

**Comment by PabloMK7** [comment]
@Steveice10 breaks CTGP-7. The plgldr service needs static state as the plugin loader configuration needs to persist between games.

**Comment by Steveice10** [comment]
Why does it need to persist between games? Nothing should have persistent state between `System` loads in Citra.

**Comment by PabloMK7** [comment]
> Why does it need to persist between games? Nothing should have persistent state between `System` loads in Citra.

Because apt app jumps resets the system on citra. Either that should be changed or static state should be allowed.

**Pull request merged**
