### PR TITLE
Revert running_core optimization

### PR DESCRIPTION
**Pull request by xperia64**
Reverts an optimization from #5227 
This optimization broke many (but not all) games when running with the interpreter.

Should probably figure out why this optimization doesn't work, but better to quick fix the interpreter for now.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5347)

### CODE REVIEW

**Comment by B3n30** [comment]
I don't like reverting this, but better than have it broken. So I'm fine with merging this

But can you please elaborate a bit more, what is broken? Stacktrace? Log?

**Comment by xperia64** [comment]
Many games simply fail to boot, running wild in a variety of failures depending on the game (unmapped reads, whole citra segfaults, etc), and the state of the emulator after closing the game is evidently "dirty" compared to first launch.

For example, in Animal Crossing, when booting it first after launching Citra, I get:
`dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x00000000000000)`

After booting and stopping another game with a "unmapped reads" non-segfault, then launching Animal Crossing again, I get:
`dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x00557947549e4d)`

**Comment by lioncash** [comment]
Commit message should probably include the extended description of what gets broken so its in the git repository history and available when doing git blames, etc.

**Comment by xperia64** [comment]
#5257 apparently fixed the interpreter issues caused by #5227, so interpreter behavior at least seems the same as before #5227.

**Pull request closed without merging**
