### PR TITLE
renderer_opengl: Remove non-separable path

### PR DESCRIPTION
**Pull request by GPUCode**
This is was attempted in the vulkan PR, but we encountered issues so it didn't make it for the final merge. Opening this as a separate PR for testing/review. It also completely removes OGLShaderStage in favour of using OGLProgram directly with the more modern glCreateShaderProgramv call to create separable programs directly from shader source. This simplifies shader caching a lot and allow for easier commonization and cleanup of the existing structures for vulkan to use in the future and should reduce shader stutter on Android

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7116)

### CODE REVIEW

**Comment by SachinVin** [comment]
Wasn't separable shaders broken on android?

**Comment by GPUCode** [comment]
I remember there were issues with geometry shaders specifically, everything else worked correctly

**Comment by Steveice10** [comment]
Do we have any specific plans for testing / bug squashing on this?

**Comment by GPUCode** [comment]
This is something that I want to do eventually, but I don't have time to bug hunt this right now, so I'll reopen it sometime in the future

**Pull request closed without merging**
