### PR TITLE
Don't pull in entire JSON repo for single header file

### PR DESCRIPTION
**Pull request by j-selby**
It is nonsensical to pull in a 100mb+ repository, with tests, documentation and so on for a single C++ header. This PR removes the link to the upstream repository and substitutes it for the aforementioned header.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2833)

### CODE REVIEW

**Comment by wwylele** [comment]
Would be better if you add a README in that directory saying the source of the repo and the version

**Comment by j-selby** [comment]
@wwylele We aren't doing this for getopt and only a URL for microprofile. Should that happen here?

**Comment by wwylele** [comment]
@j-selby IMO they should also have, but they are out of the scope of this PR so you don't need to mind it :p

**Comment by j-selby** [comment]
Fixed.

**Comment by bunnei** [comment]
With fast internet and lots of storage space, I'm personally indifferent to this (and generally prefer submoduling the source repo wherever possible instead of copying things into our repository)... but I know others care about size.

**Pull request merged**
