### PR TITLE
gl_rasterizer_cache: Remove all fully invalid surfaces from the cache

### PR DESCRIPTION
**Pull request by BreadFish64**
Previously we only did this for fill surfaces. The surfaces were left in the cache to avoid the overhead of reallocating the texture, but certain poorly behaved games (*cough Pilotwings*) make many surfaces that are fully invalidated and never reused. The dead weight in the cache bogged down texture lookup times and other cache management functions. I introduced a map of recycled textures from destroyed surfaces to avoid the aforementioned driver overhead from allocations. Pilotwings now never drops below 60fps average on my machine.
image

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5710)

### CODE REVIEW

**Comment by slentara1** [comment]
could you explain what this does to us lay men?

**Comment by BreadFish64** [comment]
The more textures there are in the cache, the longer it takes for Citra to find a certain texture. This removes textures that don't have any useful data from the cache which should make games go faster.

**Comment by slentara1** [comment]
Like textures that are no longer on screen?

**Comment by BreadFish64** [comment]
Textures whos memory has been completely overwritten, usually by a framebuffer which occupies the same memory location but doesn't have the same dimensions/format.

**Review by zhaowenlan1779 — APPROVED** [review]
If I read this correctly, all deleted CachedSurfaces are now saved for recycling (not just ones that previously won't be removed at all), right? Would this possibly result in using up too much memory?

**Comment by BreadFish64** [comment]
That was my initial reaction, but if you look at the usage of UnregisterSurface... Correct me if I'm wrong but it only really removed surfaces that were invalidated by the CPU before this. The rest just sat in the cache consuming memory. I'd be very surprised if this increased memory usage, although I guess it's possible if a game invalidates a bunch of different-size or format surfaces from the CPU. I'm actually curious if this fixes the memory usage problem in Inazuma Eleven Go Galaxy.

**Comment by Nerrel** [comment]
I think these changes broke custom texture support in MM3D and possibly other games as well.  Canary builds after 1932 have rampant graphical glitches and hang when loading new areas (1928 is OK).  I confirmed that the issue does not happen in the current nightly builds and I also made sure to remove any patches when testing it.  Other members of the MM3DHD discord server have experienced the same problem, it should be easy to reproduce in any canary build after 1932.  .  

Textures used: https://drive.google.com/file/d/1sCDH7w9pawZX6U3JxOZvuRb_d0fFpDvO/view?usp=sharing
[citra_log.txt](https://github.com/citra-emu/citra/files/5946796/citra_log.txt)
107271520-fc036000-6a11-11eb-8b42-bfbdd675dcbe

**Comment by BreadFish64** [comment]
@Nerrel It should be fixed in Canary 1947 👍

**Comment by schmurtzm** [comment]
Hi, this PR still problematic with texture replacement. It also impacts Retroarch citra core.
I find the bug present in the last version of Citra Nightly (1757) and Canary Build (2097).
With Citra Nightly 1691 or earlier, the issue is much less likely to occur.

image

The bug is detailed in this issue : https://github.com/citra-emu/citra/issues/5728

May be it could be a good idea to revert back the change in Nightly Build to have a version which supports texture replacement and keep this PR changes in the Canary Builds to keep working on the problem in parallel ?

**Pull request merged**
