### PR TITLE
Enable AAC Audio Decoder on Linux AppImage

### PR DESCRIPTION
**Pull request by TGP17**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6563)

### CODE REVIEW

**Comment by SachinVin** [comment]
AAC is patented and non free, windows, macos and android link to the system's decoders, which Linux doesn't have

**Comment by TGP17** [comment]
> AAC is patented and non free, windows, macos and android link to the system's decoders, which Linux doesn't have

The Flatpak seems to use the -DENABLE_FDK=ON build flag. Doesn't flatpak also bundle all dependencies for it?

**Comment by SachinVin** [comment]
It's some weird technicality that flatpak is the one bundling the decoder

**Comment by SachinVin** [comment]
If you can make fdk link at runtime, you could have users install from their favourite non free repo

**Pull request closed without merging**
