### PR TITLE
Port various game_list changes from yuzu

### PR DESCRIPTION
**Pull request by FearlessTobi**
See https://github.com/yuzu-emu/yuzu/pull/1259, https://github.com/yuzu-emu/yuzu/pull/1282, https://github.com/yuzu-emu/yuzu/pull/1301 and https://github.com/yuzu-emu/yuzu/pull/1335 for more details.

It is highly advised to review commit-by-commit.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4235)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Did not do a full review, but here are some issues I found in the current version of this PR.
* yuzu-emu/yuzu#1301 is already ported.
* `#include`s shouldn't be splitted
* The copyright headers should probably be `Citra` or at least `yuzu / Citra` (if required by GPL)

**Comment by FearlessTobi** [comment]
Dropped the two commits.

**Comment by wwylele** [comment]
This conflicts with something on canary...

**Comment by wwylele** [comment]
Please resolve the conflict

**Comment by FearlessTobi** [comment]
Don't do anything with this for now... I'm having some issues with the changes currently and I'd like to get them fixed.

**Comment by zhaowenlan1779** [comment]
Please resolve the conflict

**Comment by FearlessTobi** [comment]
Rebased again. Please check that I didn't break anything @zhaowenlan1779.

**Comment by zhaowenlan1779** [comment]
needs rebase

**Comment by FearlessTobi** [comment]
Rebased yet another time. I'd like to get this merged soon.

**Pull request merged**
