### PR TITLE
Pica/VertexShader: Fix a bug caused due to incorrect assumptions of consecutive output register tables.

### PR DESCRIPTION
**Pull request by neobrain**
Credits go to @RHY3756547 for spotting this issue (I rewrote his fix, though, since some ideas came to my mind for cleaning up the shader emulation code).

This should still fix some issue in Super Monkey Ball, hopefully.

### CODE REVIEW

**Comment by RHY3756547** [comment]
Yeah, this is definitely a lot cleaner than occasionally modifying vec4s of pointers instead of values for the destination. I can confirm that monkey ball still works, so long as you also include the change from command_processor.cpp:

https://github.com/RHY3756547/citra/commit/e91e9afe385bf6eaea88510873fa763b2edbe7e5#commitcomment-10171159

Obligatory screenshot:
image

**Comment by neobrain** [comment]
Thanks for verifying the new patch :)

As for zeroing out the input attributes, I don't think this is something we want to do since it's more likely to hide issues. At least currently, when uninitialized vertex attributes are read, it's obvious by the immediate brokenness. However, Subv is looking into an issue, the fix for which will probably make that workaround obsolete hopefully.

**Comment by RHY3756547** [comment]
I'll hold out for that, but I'm not sure keeping the same vertex attributes as the last submitted vertex is the correct behaviour either. Might be worth investigating in the future.

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
