### PR TITLE
[WIP] Fix "Open $DIR location" in flatpak

### LINKED ISSUE #4471: Flatpak doesn't open file manager to display the location.
I am running Citra Nightly 1126 HEAD-2678c1a9.

Steps to reproduce:
Install Citra flatpak. Open Citra and right click on a ROM and choose Open Save File location or Open Update Data location. Watch as nothing opens.

System Specs:
Ubuntu Budgie 18.10

The weird thing is that right clicking on the directory the games are in and choosing open directory location works correctly but clicking on a ROM doesn't.

### PR DESCRIPTION
**Pull request by bscubed**
Fixes #4471

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4519)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Tagged canary. Can you check if it works?

**Comment by bscubed** [comment]
That's a negative. Could you remove the canary-merge tag so I can make this WIP until I sort it out?

**Comment by B3n30** [comment]
What's the status of this PR?

**Comment by zhaowenlan1779** [comment]
According to my investigation, this is because Flatpak has the XDG env vars (which we use to hold the user directory) set to a virtual directory that does not actually exist in the host filesystem, and therefore cannot be opened in explorer.

So.. I guess this is pretty hard to solve. We'll likely have to add a special case for Flatpak and open the 'real' directories when requested.

Anyway this PR has been abandoned for a pretty long time. It might be better to open a new one when an actual fix is implemented.

**Pull request closed without merging**
