### PR TITLE
citra_qt: allow to set size to 1x using mouse's middle button

### PR DESCRIPTION
**Pull request by vvanelslande**
This doesn't work in fullscreen mode.

[Video](https://streamable.com/kxc7d)

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4949)

### CODE REVIEW

**Comment by chris062689** [comment]
Middle clicking to achieve this is not intuitive. 
I think this option would be better off under the View menu as, "Restore to 1x screen size"

**Comment by FearlessTobi** [comment]
Even in the menu, I don't see any benefit for 99% of our users in this to be honest.

**Comment by vvanelslande** [comment]
canary allows any window size and I like this change, so I wanted a way to set size to 400*480 quickly, on nightly you can do this by resizing the window to the minimum size.

**Comment by jroweboy** [comment]
@vvanelslande thats a bug in my PR, so mention it there instead pretty please

**Pull request closed without merging**
