### PR TITLE
Fix typo in travis clang-format comment version name

### PR DESCRIPTION
**Pull request by superheri**
Correcting a typo in the comment of the travis clang-format about the version number to actually represent the code.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3035)

### CODE REVIEW

**Comment by wwylele** [comment]
:thinking: I thought that comment actually meant:
"The default clang-format (in Travis CI) points to default 3.5 version one, (so we have to explicitly set it to 3.9 here)" ?

**Comment by superheri** [comment]
It feels more to me that it is an old comment left there when the version was changed.

**Comment by Dragios** [comment]
I think @wwylele is correct here.
See #2086 and #2257

**Comment by superheri** [comment]
If it is for the Travis CI default version, I think we should just clost this pull request then. Sorry for the misunderstanding.

**Pull request closed without merging**
