### PR TITLE
[NOT FOR MERGE] Use Citra as local debugger

### PR DESCRIPTION
**Pull request by mailwl**
Since Nintendo give access for everyone for CTR SDK (at developer.nintendo.com), i want to add to load compiled by SDK .cci by Citra.
Don't use it to improve Citra itself, because it violated Nintendo rules, but you may test your apps and games without hardware until you have it.

### CODE REVIEW

**Comment by wwylele** [comment]
then don't pollute our PR list please

**Comment by mailwl** [comment]
what the other way?

**Comment by hyperdrive3** [comment]
Add it to the readme.md possibly? Or just on the forums/discord.

**Comment by mailwl** [comment]
on discord only users, not developers...

**Comment by wwylele** [comment]
and please use IRC or diacord to discuss this.(Or better, don't talk anymore)

**Pull request closed without merging**
