### PR TITLE
fixed the prehook on osx,linux when using the github client

### PR DESCRIPTION
**Pull request by jfmherokiller**
if anyone knows how to remove those stupid merge things im all ears

### CODE REVIEW

**Comment by mailwl** [comment]
git rebase -i upstream/master

**Comment by jfmherokiller** [comment]
@mailwl i tried that but it said 
`fatal: Needed a single revision`
`invalid upstream upstream/master`

**Comment by MerryMage** [comment]
Use a branch that tracks `citra-emu/citra:master`, which from your commit messages above I assume would require:

`git rebase refs/remotes/citra-emu/master`

**Comment by jfmherokiller** [comment]
@MerryMage thanks that worked

**Comment by jfmherokiller** [comment]
closing because after futher testing the script still breaks for unknown reasons

**Comment by jfmherokiller** [comment]
found a fix so i am reopening this pull request

**Comment by jfmherokiller** [comment]
this issue is not completely fixed but for linux and mac it should work 
windows has this issue http://stackoverflow.com/questions/12410164/github-for-windows-pre-commit-hook

**Comment by jfmherokiller** [comment]
if you want i could try to rewrite the pre-hook using powershell but for rn im also going to add a commit that writes the prehook fixes diff to a file so the user can read them easier

**Comment by jfmherokiller** [comment]
um the build failed with `The command "eval git clone --depth=50 https://github.com/citra-emu/citra.git citra-emu/citra " failed 3 times.`

**Comment by yuriks** [comment]
IMO at this point we would just get rid of the commit hook. It seems to have caused a lot of problems and annoyance to people, and our CI builds will already catch bad formatting. People can still manually run clang-format locally as needed.

**Comment by jfmherokiller** [comment]
ok im gonna close this pull request then

**Pull request closed without merging**
