### PR TITLE
Add MSVC binaries for Windows on releases

### PR DESCRIPTION
**Pull request by vitor-k**
This adds steps to release msvc-compiled binaries as an alternative to the mingw/gcc compiled binaries for windows users.
The shipped binaries are already being produced by the existing Windows CI, just packaged with certain files added/removed.

This ports yuzu-emu/yuzu#585 to fix the CitraCopyQt5/SDL/FFmpegDeps cmake modules that had silently stopped working.
The Windows test error on the CI was also fixed by this.

This was inspired by @GPUCode's troubles with a gcc bug affecting AMD users of the vulkan WIP branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6190)

### CODE REVIEW

**Review by GPUCode — APPROVED** [review]
Thanks!

**Comment by SachinVin** [comment]
Can you benchmark MSVC vs Mingw, back in the day MSVC was noticably slower than gcc.

**Comment by GPUCode** [comment]
> Can you benchmark MSVC vs Mingw, back in the day MSVC was noticably slower than gcc.

I've been alternating between these compilers and I haven't noticed any significant performance regressions.
Στιγμιότυπο οθόνης (17)
Στιγμιότυπο οθόνης (18)

**Comment by SachinVin** [comment]
LGTM then!

**Pull request merged**
