### PR TITLE
Add address conversion functions returning optional, Add function to flush virtual region from rasterizer cache

### PR DESCRIPTION
**Pull request by yuriks**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2799)

### CODE REVIEW

**Comment by wwylele** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/memory.cpp, line 705 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2799#-KnF7_48Qf0B7PLifCEI:-KnF7_48Qf0B7PLifCEJ:bjs5imc) ([raw file](https://github.com/citra-emu/citra/blob/72b69cea4bf9d01e520fb984a382de3e85af4e36/src/core/memory.cpp#L705)):*
> ```cpp
>     }
> 
>     LOG_ERROR(HW_Memory, "Unknown physical address @ 0x%08X", addr);
> ```

Why is this log removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2799)*

**Comment by yuriks** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/memory.cpp, line 705 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2799#-KnF7_48Qf0B7PLifCEI:-KnGHlRaVah7Mr_GSNO6:bp1e0q) ([raw file](https://github.com/citra-emu/citra/blob/72b69cea4bf9d01e520fb984a382de3e85af4e36/src/core/memory.cpp#L705)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

Why is this log removed?
</blockquote></details>

The function now lets you recover from errors, so there's no reason to log it (and clog up the logs more) if you expect and can correctly handle the error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2799)*

**Comment by wwylele** [comment]
srubs2009 on discord reports this bypasses #2110.

**Comment by wwylele** [comment]
:lgtm: code looks fine. I am not so familiar with memory stuff so better to have another one review it.

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/memory.h, line 201 at r3](https://reviewable.io:443/reviews/citra-emu/citra/2799#-KnVz5ixKH30vsXrwDk2:-KnVz5ixKH30vsXrwDk3:bxw05gt) ([raw file](https://github.com/citra-emu/citra/blob/d5531357487a144cf962ce08a912417fd5e61570/src/core/memory.h#L201)):*
> ```objc
> 
> /**
>  * Flushes and invalidates any externally cached rasterizer resources touching the given virtual
> ```

probably can word it better here since invalidation is optional.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2799#-:-KnVyWBNWhX46Yq8iKwl:bmz1k07)*

**Comment by jroweboy** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2799)*

**Pull request merged**
