### PR TITLE
ThreadProcessorId2

### PR DESCRIPTION
**Pull request by Jhon5912**
CMD Request ThreadProcessorId2

Requested and Boots Minecraft New Nintendo 3DS Edition USA/AUS/EUR, Possible other Games ?, Start up Boot of Game broken by #3440  - A little boost to this and it loads up the game.

Review ?

(Note) Not for this Request, but other possible fixes for this game.
Baypass is FLV hack but "not" for this Request
Other possible loading while in game freeze fix
https://github.com/Jhon5912/citra-1/commit/b213e6133ab423fb9a5f9568b168e29a1d56ead6

Minecraft without code screenshot

file1

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4362)

### CODE REVIEW

**Comment by Jhon5912** [comment]
No Review ?

**Comment by Jhon5912** [comment]
Edit good for minecrft boot without error ^
        static constexpr u64 slope(94);
        static constexpr u64 offset(782778);
        static constexpr u64 minimum(863124);

+ this thread

**Comment by wwylele** [comment]
No. Even if the code is acceptable, I won't accept this PR, because you clearly doesn't understand what the hell you are doing.

**Comment by Jhon5912** [comment]
Yes its a missing request of the games function that is required ?

**Comment by wwylele** [comment]
@Jhon5912 IIRC We have been trying to explain it to you (an everyone) on gbatemp but it looks like you have learned nothing. Sorry, I gave up.

**Pull request closed without merging**
