### PR TITLE
rasterizer: implement combiner operation 7 (Dot3_RGBA)

### PR DESCRIPTION
**Pull request by wwylele**
Knowledge source:
 - [Documentation on 3dbrew](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_TEXENVi_OPERAND): "Value 7 - Dot3 RGBA"
 - [OpenGL documentation](https://www.khronos.org/registry/OpenGL-Refpages/es1.1/xhtml/glTexEnv.xml): GL_DOT3_RGB and GL_DOT3_RGBA have the same formula, but "The scalar results for GL_DOT3_RGB and GL_DOT3_RGBA are placed into each of the 3 (RGB) or **4 (RGBA)** components on output.

Hardware test: ~~not yet.~~ result verified. For more details see below.

Fixed game: Monster Hunter X/Generations / XX
Screenshot (black bottom screen is GS related):
screenshot from 2017-04-19 23-52-10
screenshot from 2017-04-19 23-49-39

### CODE REVIEW

**Comment by wwylele** [comment]
Until now I only observed that the game sets both color and alpha combiners to Dot3_RGBA at the same time, and I don't know what will happen for other cases. I added check and log for `(color_op==Dot3_RGBA && alpha_op!=Dot3_RGBA)`. Note that `(alpha_op==Dot3_RGBA && color_op!=Dot3_RGBA)` still falls into `AppendAlphaCombiner`/`AlphaCombine` 's old log. 

I will try to do hwtest for these cases. Don't expect too much though, because this is the first time for me to test PICA :stuck_out_tongue:

**Comment by JayFoxRox** [comment]
Also see https://github.com/citra-emu/citra/pull/1655 for more hw-test proposals

**Comment by wwylele** [comment]
Hardware test result, using [this program](https://github.com/JayFoxRox/3ds-tests/pull/7):

 - :heavy_check_mark:  if `color_op==Dot3_RGBA`, `alpha_out = color_out = Dot3(in[0], in[1])`, no matter what value `alpha_op` has 
 - if `alpha_op==Dot3_RGB/Dot3_RGBA`, 
   - :warning:if `color_op==Replace/Modulate/Add/AddSigned/AddThenMultiply`, `alpha_out = in[0].g + in[1].g`
   - :warning:if `color_op==Lerp/Subtract`, `alpha_out = Lerp(in[0].g, in[1].g, in[2].g)`
   - :heavy_check_mark:  if `color_op==Dot3_RGB/Dot3_RGBA`, `alpha_out = color_out = Dot3(in[0], in[1])` 
   - :warning:if `color_op==MultiplyThenAdd`, `alpha_out = MultiplyThenAdd(in[0].g, in[1].g, in[2].g)`
 - :heavy_check_mark: other cases yield the same result as citra does (with error of +/-1)

Summary:
 - The implementation of this PR is correct. when `color_op==Dot3_RGBA`, `alpha_op` is ignored. Thus I will remove the log when `alpha_op!=Dot3_RGBA`
 - Results from `alpha_op==Dot3_RGB/Dot3_RGBA` looks like undefined behaviour of pica, so I will leave them unimplemented (except for `both_op==Dot3_RGBA`)

Bonus:
[This TODO](https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_shader_gen.cpp#L309) has been done, and citra's implementation has been verified. I will remove that TODO

**Comment by yuriks** [comment]
Oh, nice! I think emitting a warning for the invalid configuration would still be useful for homebrew developers, etc., but it's not a big deal.

**Pull request merged**
