### PR TITLE
OpenGL: Make OpenGL object resource wrappers fully inline

### PR DESCRIPTION
**Pull request by yuriks**
The functions are so simple that having them separate only bloats the
code and hinders optimization. Also added move constructor which will
come in handy.

### CODE REVIEW

**Comment by Subv** [comment]
LGTM

**Comment by yuriks** [comment]
Oops, found a bug. Don't merge.

**Comment by yuriks** [comment]
Ok, done. (Was missing returns on the operator='s)

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
