### PR TITLE
glad: Update to OpenGL 4.1

### PR DESCRIPTION
**Pull request by Steveice10**
On my M1 Macbook Air, Citra currently crashes with disk shader cache enabled, since GL_ARB_get_program_binary is not advertised and thus glGetProgramBinary is never resolved. However, OpenGL does report support for version 4.1, which includes glGetProgramBinary. Thus, by updating the generated version of GLAD to support up to OpenGL 4.1, glGetProgramBinary will be loaded and disk shader cache will work on systems like mine.

My understanding is that upgrading GLAD in this way only means OpenGL 4.1 support will be loaded when available, and that since the version check in Citra is still set to 3.3 the minimum requirement will not be raised by this change. Let me know if this is incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5831)

### CODE REVIEW

**Comment by SachinVin** [comment]
I'm just thinking of lazily adding an ifdef for apple, probably fine for now, given builds are currently broken for MacOs older than 10.15, but ideally we want to support older versions

**Comment by Steveice10** [comment]
This change shouldn't reduce compatibility as the minimum target is still OpenGL 3.3. It just means that if OpenGL 4.1 is available it can be used as an alternative way to get the functions otherwise provided by the extension.

**Comment by SachinVin** [comment]
I meant adding an ifdef as a workaround in #5785, sorry for the confusion.

**Comment by Steveice10** [comment]
Ahh okay. I think in that case you could also just add GLAD_GL_VERSION_4_1 to your check and that would work.

**Comment by SachinVin** [comment]
I did think about doing that, but then I found an [old af doc](https://developer.apple.com/opengl/OpenGL-Capabilities-Tables.pdf) from them saying the `NUM_PROGRAM_BINARY_FORMATS` is zero, even for 4.1 drivers, (though I do not know how true that is for "recent" drivers if they provide any), and I couldn't find any other sources that confirm if the feature is actually available, or apple just provides some sort of null implementation.

**Comment by Steveice10** [comment]
Ah yes you seem to be correct, on further inspection program size is being returned as 0, so this change is pretty much moot.

I will say, though, that at least having the transferable cache working seems to greatly reduce stuttering in-game at the expense of a few seconds of compile time at launch, which suggests to me that macOS would benefit from not having the shader cache entirely disabled as it is in your PR.

**Comment by SachinVin** [comment]
Not really, the current implementation of transferable shaders only works for separable shader, which is disabled by default on MacOs (thanks to broken drivers, atleast for Intel). Because the vertex and fragment shaders are independently cached, the combined shader is never actually compiled when loading the transferable cache. Though eventually reworking the shader cache for android (if it ever happens) should allow us to load the combined shader blob.

**Comment by Steveice10** [comment]
I'm on M1 not Intel though, so separable shaders are not being affected by the Intel vendor check. I'm noticing much better performance with the transferable cache vs completely disabling disk shader cache in the settings.

**Comment by Steveice10** [comment]
Never mind. Not sure why but even though I was getting stutters before on first run, even if I disable shader cache again it still runs smoothly now. Must be something else at work.

**Comment by SachinVin** [comment]
Driver cache perhaps

**Comment by Steveice10** [comment]
Probably. Separable shaders should still have been enabled though since vendor isn't Intel, so they didn't seem to be causing any issues with the Apple GPU at least.

**Pull request closed without merging**
