### PR TITLE
shader_jit: Fixes for Gunman clive

### PR DESCRIPTION
**Pull request by SachinVin**
Fixes Gunman clive crashing when shader JIT enabled (#6006), there were a couple things that made it crash. The game is still bugged with the interpreter because BREAKC isn't implemented.

The game compiles large-ish loops with BREAKC near the entry, this breaks the back patching of the `jnz`, because Xbyak compiles a short `jnz` in `Compile_BREAKC`, simply passing `T_NEAR` when compiling the `jnz` does the trick.

The game also compiles nested loops(~that it never uses?~ nvm it does). Implemented nested LOOPs in the shader jit, the unit test are pretty basic, but the behaviour should be similar to the interpreter.

I've only tested with Gunman clive 1, and some regression testing doesn't seem to break anything so far.

@Seamed if you can test Gunman clive 2 and possible some other games too, that would be great!

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6010)

### CODE REVIEW

**Review by bunnei — APPROVED** [review]

**Review by Seamed — COMMENTED** [review]
Sorry for late response, yes, I've tested gunman clive too, it seems to work fine there, however, I still encounter some graphical issues on gunman clive, on stage 10, when the boss spits fire at you, the fire effect is nearly invisible, as in very few particles show up while mayority are still invisible, I haven't had the chance to test things due to school, but I'll try more tests when I can
[2022-05-03 21-17-15\_Trim.mp4](https://files.reviewableusercontent.io/images/reviewable/103855819/LwgA11R_1ajAR9F310edHwQ1/2022-05-03%2021-17-15_Trim.mp4)

> *[Reviewable](https://reviewable.io/reviews/citra-emu/citra/6010#-:-N1BqWDJCWC1_CVl80bU:bicbhx1)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by Seamed** [comment]
Here's the log
[citra_log.txt](https://github.com/citra-emu/citra/files/8617592/citra_log.txt)

**Comment by Seamed** [comment]
As for gunman clive 2, from this one test I made, it seems to be working fine, again, I'll do further testing when I can

Prior to JIT fix

https://user-images.githubusercontent.com/103855819/166618050-6bb0b4a5-8c7d-4694-b8ac-7c37c1605921.mp4

After JIT fix

https://user-images.githubusercontent.com/103855819/166616000-62105fcd-0f88-4a07-a056-7e947337887b.mp4

**Comment by SachinVin** [comment]
@Seamed Thanks I'll have a look 👍

**Comment by SachinVin** [comment]
So, it seems like the `LOOPCOUNT_REG` does get saved and restored in nested loops, going against the implementation in both the interpreter and the glsl decompiler.
I couldn't find any discussions about it, but I did find an old doc that mentions a certain "_loop index variable [that] appears to be magically saved and restored when doing nested LOOPs_" ([ref](https://docs.google.com/document/d/1tQcbp42CuXnhVWXrLreOdYff9GmFrd03kBt28qjZENg/edit)). 
Unsure if they are the same thing ...
The HLSL spec for the loop does seem to match but that might just be confimation bias - [HLSL loop](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/loop---vs)

This is how the game looks when saving and restoring `LOOPCOUNT_REG`, the texture for whatever  that stuff is, still seems off.
Gunman clive

**Comment by Seamed** [comment]
That looks fine actually, I just noticed I forgot to show you how it should look like, so here it's the fire in real hardware

https://user-images.githubusercontent.com/103855819/168489270-bd64e4cf-6807-4f26-b517-749e24970587.mp4

That fix looks pretty spot on

**Comment by SachinVin** [comment]
I though the "particles" the appeared more circular on hardware compared to citra... on second thoughts it might just be the lower resolution.
I'll clean up and push later some time

**Comment by SachinVin** [comment]
Updated so it new saves and restores the `LOOPCOUNT_REG` registers, also updated the tests.
I've added back the soft assert, in case we want to look at other games that might have nested loops.

**Review by BreadFish64 — APPROVED** [review]

**Pull request merged**
