### PR TITLE
Chore: enable `-Werror` on GCC and clang

### PR DESCRIPTION
**Pull request by SachinVin**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6602)

### CODE REVIEW

**Review by FearlessTobi — APPROVED** [review]

**Comment by SachinVin** [comment]
Will likely conflict with the ffmpeg PR

**Comment by Steveice10** [comment]
Getting the following trying to compile on Clang 15 (I remember seeing this warning in the past on Clang 14 as well):
```
src/common/string_util.cpp:158:31: error: 'codecvt_utf8_utf16<char16_t>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
                    ^

src/common/string_util.cpp:158:10: error: 'wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
         ^

src/common/string_util.cpp:163:31: error: 'codecvt_utf8_utf16<char16_t>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
                              ^

src/common/string_util.cpp:163:10: error: 'wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;
         ^
```

**Comment by GPUCode** [comment]
Canary is failing due to this PR
```
C/C++: /home/runner/work/citra-canary/citra-canary/src/core/hle/service/nfc/nfc.cpp:124:16: error: unused variable 'result' [-Werror,-Wunused-variable]
C/C++:     const auto result = nfc->device->StopCommunication();
C/C++:                ^
C/C++: 1 error generated.
```

**Comment by SachinVin** [comment]
Will insta merge once #6623 is merged, other PRs can rebase and fix warnings

**Pull request merged**
