### PR TITLE
DSP update some functions

### PR DESCRIPTION
**Pull request by Danman3412**
Just updating some DSP functions.

Please wait for checks to clear,  Be four reviewing ?

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4523)

### CODE REVIEW

**Comment by wwylele** [comment]
And stop creating alt accounts, drwhojan.

**Comment by Danman3412** [comment]
Ok @wwylele, I asked NarcolepticK for review by email and he seed it looked fine also did a review himself and some changes long ago.

If any think not fine then let us know what to change to help.

And Yes my first account got flagged and cannot get out, and could not get out, Also excuse me while I'v had a long day with life too yarn.

**Comment by NarcolepticK** [comment]
Please don't involve me in this. I stated I was uncertain about it. Dsp is not my area. I cannot speak on implementation I could only speak on structuring the code. I don't wish to be used as ammo for fights.

**Comment by Danman3412** [comment]
> Please don't involve me in this. I stated I was uncertain about it. Dsp is not my area. I cannot speak on implementation I could only speak on structuring the code. I don't wish to be used as ammo for fights.

Your not going to be, best to watch "city slickers" I suppose *Curly "You city folk worry about a lot of shit" lol

**Comment by Danman3412** [comment]
Anyway whats requested changes ?..

**Comment by wwylele** [comment]
@Danman3412 Please be aware that creating alt account violates github's ToS and it is exactly the reason your previous accounts were flagged. I am tired of dealing with your stuff.  It has been two damn years and you are still what you were. Please leave, and maybe one day come back and contribute here as a new person that we don't recognize.

**Comment by Danman3412** [comment]
It was the first account started it, and no and yes you know its me I just did not mention me.

anyway who help work out a bigger fix from me was - priority -=1 you.. zelda a link to the pass that lead to bigger fixes from it, 
https://gbatemp.net/threads/citra-unofficial-chinese-builds-discussion.431974/page-36

Anyway yes getting off topic so leave it at this,

**Comment by Danman3412** [comment]
Gone and broke some think from the small changes in checks, rechecking ^

**Comment by chris062689** [comment]
You have been told several times in the past not to make low quality PRs. 
This is the same low quality pull requests as others in the past. 

You have been suspended in the past for this after not stopping. 

You have been reported to Github for violation of their terms of service.

**Pull request closed without merging**
