### PR TITLE
Correcting word order of a comment in memory.cpp

### PR DESCRIPTION
**Pull request by superheri**
Making a comment easier to read by changing the order of the verb to make a correct sentence.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3060)

### CODE REVIEW

**Comment by mailwl** [comment]
useless...

**Comment by Jhon591** [comment]
@mailwl 
No more useless then this lol
https://gbatemp.net/threads/citra-unofficial-chinese-builds-discussion.431974/page-310#post-7658005

**Comment by mailwl** [comment]
sorry sorry for my comment, citra development really weak last year, so i too angry for comment changing PR

**Comment by superheri** [comment]
@mailwl 
I thought it useful to correct this since it was a bit hard to understand at the first read when I was trying to unsertand this part of code.

**Comment by mailwl** [comment]
@superheri sorry for trolling, i am not from citra team

**Pull request merged**
