### PR TITLE
Add website to README. Be proud of it!

### PR DESCRIPTION
**Pull request by vgturtle127**
It looks too good NOT to put in there! :wink:

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-02-25T07:43:16Z: https://github.com/citra-emu/citra/compare/e04e6aabbc7bbd2bc3a08a6cecd50273670ca0a6...vgturtle127:e58ad4ab5109e04df941353d7ea83bfec10c55b6

**Comment by DotERM** [comment]
Why not?

**Comment by MoochMcGee** [comment]
VGTURTLE127 ЕСТЬ СУКА БЛЯТЬ

**Comment by archshift** [comment]
@MoochMcGee if you have to troll, please do it somewhere else.

**Pull request merged**
