### PR TITLE
hid: fix pad update

### LINKED ISSUE #1507: Pokemon Picross input issue
(I am not a native English speaker. This issue is a little bit hard for me to describe.)
The issue happens when you choose control method to be "Stylus".
### On real console
During the game, you can use D-Pad or Circle Pad to switch between two pattern (solid or "x") to be drawn. That's saying:
 - when you press and hold "Up" on D-Pad, or push up Circle Pad and hold it, you are in "drawing" state and you can fill in grids on the board with stylus
 - when you press and hold "Down" on D-Pad, or push down Circle Pad and hold it, you are in "cross out" state and you can put "x" in the grids. 
 - if you release D-Pad or Circle Pad, you are now in "idle" state, and you can draw nothing with stylus. 

pic

An icon is shown at the left up corner of the bottom screen, indicating which state you are in. For example, if you are in "drawing state", the upper red icon will be shining.

### On Citra
Both D-Pad and Circle Pad seem broken. When you push up Circle Pad and hold it, the game responses as if you are not holding it, but pushing it up and releasing it in a high frequency. You can see the icon is not shining normally, but continuously switching between "filling" state and "idle" state. At the same time you can hardly draw anything with stylus (mouse). Similar thing happens to D-Pad.

I don't know if other Picross games have this issue. I only have this one game.

### PR DESCRIPTION
**Pull request by wwylele**
Fix #1507

### CODE REVIEW

**Comment by Leo626** [comment]
Tested it with Bravely Default and there's no more fast key repeats on the D-pad. Good job wwylele.

**Comment by MerryMage** [comment]
LGTM

**Comment by Romsstar** [comment]
This fixes the Circle Pad in Digimon World Re:Digitize Decode.
I was going to make a separate issue for this but wwylele already fixed it :)

**Comment by Subv** [comment]
LGTM

**Comment by yuriks** [comment]
Oh wow, what a silly bug. Nice catch!

**Pull request merged**
