### PR TITLE
Y2R: Fix narrowing warning

### PR DESCRIPTION
**Pull request by aroulin**
Fix initializer-list narrowing warning (u32 -> u8)

### CODE REVIEW

**Comment by yuriks** [comment]
LGTM

**Comment by archshift** [comment]
(Oops)

Wht not keep the brace initialization but just change the masks to casts?

**Comment by aroulin** [comment]
Changed masks to casts. It's nice that integer conversions to smaller unsigned types is well-defined (unlike conversions to smaller signed types which are implementation-defined).

**Comment by neobrain** [comment]
I find those ugly casts both needlessly verbose, yet much less clear than the manually masking. Why not just use constructor initialization by changing `{` and `}` to `(` and `(`, as discussed on IRC earlier today?

**Comment by yuriks** [comment]
One advantage of the casts is that I think MSVC will still generate narrowing warnings with the function call.

**Comment by neobrain** [comment]
@yuriks: Could you verify that claim? I'd rather not have such ugly code used based on preventing hypothetical warning messages (also, if MSVC is really that dumb about narrowing warnings, we might actually want to consider disabling that one).

**Comment by yuriks** [comment]
@neobrain MSVC emits warnings for any implicit narrowing conversions (assignment, parameters passing, etc.). We could disable them, but I think they're valuable in identifying mistakes in type usage. Instead I'd rather we simply allow C-style casts for simple integer conversions, since `static_cast` is verbose and distracting.

**Comment by yuriks** [comment]
As per #919, change it to C-style casts and then LGTM.

**Comment by aroulin** [comment]
Changed to C-style casts. Masks with 0xFF are not necessary but if that's better for readability, I can put them back.

**Comment by yuriks** [comment]
LGTM

**Comment by purpasmart96** [comment]
LGTM

**Pull request merged**
