### PR TITLE
Add link to Discord

### PR DESCRIPTION
**Pull request by daniellimws**
Add Discord in addition to IRC since people nowadays would find it easier to contact through Discord.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3466)

### CODE REVIEW

**Comment by jroweboy** [comment]
we should hold off on this one until we find out if we get accepted for the branded url thingy https://support.discordapp.com/hc/en-us/articles/115001542132-Server-Vanity-URLs we did the partnership application recently so i don't know how much longer citra-emu.org/discord will be around for. @chris062689 care to comment?

**Comment by adityaruplaha** [comment]
Also add a link in README.MD

**Comment by chris062689** [comment]
Still waiting back from Discord on this. My main concern with pushing users to report issues on Discord is that genuine issues should stay on Github. Rarely when users report them on Discord, do they actually take the time to crosspost them.

**Comment by bunnei** [comment]
@chris062689 on the contrary, I think I'd rather people be filtered at the Discord level to distinguish between support requests and legitimate GitHub issues.

**Comment by chris062689** [comment]
Understood. Discord denied our application, so I'm fine with continuing this change.

**Pull request merged**
