### PR TITLE
service/nwm_uds: log instead of assert to prevent crashes during multiplayer in Monster Hunter games

### PR DESCRIPTION
**Pull request by tywald**
Similarly to #5382 this will fix random crashes that can occur while playing multiplayer in Monster Hunter games.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6161)

### CODE REVIEW

**Review by FearlessTobi — APPROVED** [review]

**Comment by tywald** [comment]
Though now that I think about it, the return statements might trigger disconnects. They were only added because <https://github.com/citra-emu/citra/pull/5382/files#diff-dc4873448b59edfba892353bcc73241d8760f2d2c2177bd22588c3460c923df2R350> 

@zhaowenlan1779 do we want to return?

**Comment by SachinVin** [comment]
Shouldn't you push `ResultCode` to let the game know about it ?

**Comment by tywald** [comment]
I assume it's for the change in `sendTo()` as no other if statements in `HandleDeauthenticationFrame()` do it (unless those are wrong from the start)?

**Comment by SachinVin** [comment]
Yep just `sendTo()`. `HandleDeauthenticationFrame()` seem to be a just helper function.

**Comment by tywald** [comment]
Seems I need to make it the second if statement since `rb` is declared below it.

Should be fine I guess?

**Pull request merged**
