### PR TITLE
SVC: Update the SVC function table

### PR DESCRIPTION
**Pull request by purpasmart96**

### CODE REVIEW

**Comment by yuriks** [comment]
-1. Unecessary (and precludes moving to a faster SVC dispatch in the future.)

**Comment by purpasmart96** [comment]
@yuriks Why? There is no functional change.

**Comment by Subv** [comment]
@yuriks I'm not sure what you're talking about, all this does is renaming some "Unknown" strings to the value from 3dbrew, and the indentation.

**Comment by yuriks** [comment]
The Unknown entries were actually removed. I'd rather this table be converted into an array.

**Comment by purpasmart96** [comment]
@yuriks All the of the Unkown entries I deleted were the ones that were dummies, those Uknown entries never existed in first place. There is Documentation on these and No retail rom I know of call the ones that were not listed on 3dbrew.

**Comment by Subv** [comment]
Here's a fun fact, we actually need those dummy entries because this table is already an array, and it's registered using ARRAY_SIZE(SVC_Table);

**Comment by yuriks** [comment]
And the table also acesses the SVC by array index. So I was right all along! :)

**Comment by yuriks** [comment]
Can you not re-indent everything then?

**Comment by purpasmart96** [comment]
@yuriks no, because It needed to be re-indented anyway..

**Comment by yuriks** [comment]
I'd much rather have that one function hanging out there, since it's the only one with a longer name.

**Comment by purpasmart96** [comment]
I disagree, it should be consistent.

**Comment by chinhodado** [comment]
I agree with @yuriks, we should avoid re-indent stuffs like this since it messes up git blame and the like.

**Comment by purpasmart96** [comment]
@yuriks That's very not consistent, even if its only one function, it still needs to be aligned properly.

**Comment by neobrain** [comment]
Just remove the reindentation. It's not crucial for the actual change in this PR.

**Comment by bunnei** [comment]
LGTM

**Comment by neobrain** [comment]
@purpasmart96 Just a note: branch pushes don't trigger email notifications, so I didn't notice when you updated the branch. Thanks for sorting the issue out, though.

**Comment by purpasmart96** [comment]
@neobrain no prob

**Pull request merged**
