### PR TITLE
Remove unused and bitrotted "controller config" files

### PR DESCRIPTION
**Pull request by archshift**
There's no use keeping this around IMO, if we want an actual useful controller config UI we'll resurrect #531 or #1119.

### CODE REVIEW

**Comment by Subv** [comment]
Kill it with fire.

**Comment by makotech222** [comment]
Just fyi, i have a controller config UI waiting in the wings. Need for #1789 to get accepted first though.

**Comment by MerryMage** [comment]
@makotech222 Does that block this PR?

**Comment by makotech222** [comment]
@MerryMage Nope

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
