### PR TITLE
Android: Gradle updates

### PR DESCRIPTION
**Pull request by t895**
Includes updates to all android dependencies/ndk (minus billing) and adds support for Kotlin, Android 13, and view binding.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6653)

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Android CI is failing.

**Comment by t895** [comment]
Yeah looks like I broke the copy task at the end. Working through it now.

**Comment by t895** [comment]
Just adding this comment here as a notice that might help someone else.

When using `android.applicationVariants.all`, gradle will not detect any of the build variants and as a result, not run any of the new tasks we wanted to add. Instead, we have to use `android.applicationVariants.configureEach` which does detect all build variants correctly. I'm not 100% sure why since I've seen `.all` work on other projects but this works for us.

**Comment by t895** [comment]
Just dropped in some last minute changes to the dependencies too. For whatever reason there were a couple duplicated or unused dependencies. Should improve the speed of the first gradle sync.

**Review by Steveice10 — APPROVED** [review]
Both the scripts and output artifacts LGTM

**Pull request merged**
