### PR TITLE
shader_jit_x64_compiler: Use haddps for horizontal summation

### PR DESCRIPTION
**Pull request by MerryMage**
ICC emits this instead for its __sec_reduce_add intrinsic when supported.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3261)

### CODE REVIEW

**Comment by yuriks** [comment]
We used to have this, but we removed it for some reason a while back. (Possibly because it was actually slower than the shuffles?) Needs some quick investigation...

**Comment by MerryMage** [comment]
Looking at the git history, it looks like originally DP4 and DPH were implemented with dpps, but was replaced with what is currently present because of the need to do checked multiplication.

**Comment by yuriks** [comment]
Ah, I think it's because the two sequences are basically a wash: (manual scheduling, using Haswell latencies) (and if you remove the movs then the shuffle version actually ends up being theoretically faster).

```
haddps src1, src1 // lat 5, tput 2
-- lat (tput)
-- lat
-- lat
-- lat
haddps src1, src1 // lat 5, tput 2
-- lat (tput)
-- lat
-- lat
-- lat
result in src1

movaps src2, src1 // lat 0-1
shufps src1, src1 // lat 1, tput 1
addps src1, src2 // lat 3, tput 1
-- lat
-- lat
movaps src2, src1 // lat 0-1
shufps src1, src1 // lat 1, tput 1
addps src1, src2 // lat 3, tput 1
-- lat
-- lat
result in src1
```

Would be interesting to get a live benchmark of this to see if it makes any difference, though the smaller code is probably nice either way.

**Comment by yuriks** [comment]
Bonus Intel Architecture Code Analyzer output:

Haswell / haddps:
```
Binary Format - 64Bit
Architecture  -  HSW
Analysis Type - Throughput

Throughput Analysis Report
--------------------------
Block Throughput: 9.77 Cycles       Throughput Bottleneck: Backend
Loop Count:  25
Port Binding In Cycles Per Iteration:
--------------------------------------------------------------------------------------------------
|  Port  |   0   -  DV   |   1   |   2   -  D    |   3   -  D    |   4   |   5   |   6   |   7   |
--------------------------------------------------------------------------------------------------
| Cycles |  0.0     0.0  |  2.0  |  0.0     0.0  |  0.0     0.0  |  0.0  |  4.0  |  0.0  |  0.0  |
--------------------------------------------------------------------------------------------------

DV - Divider pipe (on port 0)
D - Data fetch pipe (on ports 2 and 3)
F - Macro Fusion with the previous instruction occurred
* - instruction micro-ops not bound to a port
^ - Micro Fusion occurred
# - ESP Tracking sync uop was issued
@ - SSE instruction followed an AVX256/AVX512 instruction, dozens of cycles penalty is expected
X - instruction not supported, was not accounted in Analysis

| Num Of   |                    Ports pressure in cycles                         |      |
|  Uops    |  0  - DV    |  1   |  2  -  D    |  3  -  D    |  4   |  5   |  6   |  7   |
-----------------------------------------------------------------------------------------
|   3      |             | 1.0  |             |             |      | 2.0  |      |      | haddps xmm1, xmm1
|   3      |             | 1.0  |             |             |      | 2.0  |      |      | haddps xmm1, xmm1
Total Num Of Uops: 6
Analysis Notes:
Backend allocation was stalled due to unavailable allocation resources.
```

Haswell / shufps:
```
Binary Format - 64Bit
Architecture  -  HSW
Analysis Type - Throughput

Throughput Analysis Report
--------------------------
Block Throughput: 8.00 Cycles       Throughput Bottleneck: Backend
Loop Count:  29
Port Binding In Cycles Per Iteration:
--------------------------------------------------------------------------------------------------
|  Port  |   0   -  DV   |   1   |   2   -  D    |   3   -  D    |   4   |   5   |   6   |   7   |
--------------------------------------------------------------------------------------------------
| Cycles |  0.0     0.0  |  2.0  |  0.0     0.0  |  0.0     0.0  |  0.0  |  2.0  |  0.0  |  0.0  |
--------------------------------------------------------------------------------------------------

DV - Divider pipe (on port 0)
D - Data fetch pipe (on ports 2 and 3)
F - Macro Fusion with the previous instruction occurred
* - instruction micro-ops not bound to a port
^ - Micro Fusion occurred
# - ESP Tracking sync uop was issued
@ - SSE instruction followed an AVX256/AVX512 instruction, dozens of cycles penalty is expected
X - instruction not supported, was not accounted in Analysis

| Num Of   |                    Ports pressure in cycles                         |      |
|  Uops    |  0  - DV    |  1   |  2  -  D    |  3  -  D    |  4   |  5   |  6   |  7   |
-----------------------------------------------------------------------------------------
|   1*     |             |      |             |             |      |      |      |      | movaps xmm2, xmm1
|   1      |             |      |             |             |      | 1.0  |      |      | shufps xmm1, xmm1, 0xb1
|   1      |             | 1.0  |             |             |      |      |      |      | addps xmm1, xmm2
|   1*     |             |      |             |             |      |      |      |      | movaps xmm2, xmm1
|   1      |             |      |             |             |      | 1.0  |      |      | shufps xmm1, xmm1, 0x1b
|   1      |             | 1.0  |             |             |      |      |      |      | addps xmm1, xmm1
Total Num Of Uops: 6
Analysis Notes:
Backend allocation was stalled due to unavailable allocation resources.
```

Skylake / haddps:
```
Binary Format - 64Bit
Architecture  -  SKL
Analysis Type - Throughput

Throughput Analysis Report
--------------------------
Block Throughput: 7.80 Cycles       Throughput Bottleneck: Backend
Loop Count:  23
Port Binding In Cycles Per Iteration:
--------------------------------------------------------------------------------------------------
|  Port  |   0   -  DV   |   1   |   2   -  D    |   3   -  D    |   4   |   5   |   6   |   7   |
--------------------------------------------------------------------------------------------------
| Cycles |  1.0     0.0  |  1.0  |  0.0     0.0  |  0.0     0.0  |  0.0  |  4.0  |  0.0  |  0.0  |
--------------------------------------------------------------------------------------------------

DV - Divider pipe (on port 0)
D - Data fetch pipe (on ports 2 and 3)
F - Macro Fusion with the previous instruction occurred
* - instruction micro-ops not bound to a port
^ - Micro Fusion occurred
# - ESP Tracking sync uop was issued
@ - SSE instruction followed an AVX256/AVX512 instruction, dozens of cycles penalty is expected
X - instruction not supported, was not accounted in Analysis

| Num Of   |                    Ports pressure in cycles                         |      |
|  Uops    |  0  - DV    |  1   |  2  -  D    |  3  -  D    |  4   |  5   |  6   |  7   |
-----------------------------------------------------------------------------------------
|   3      | 1.0         |      |             |             |      | 2.0  |      |      | haddps xmm1, xmm1
|   3      |             | 1.0  |             |             |      | 2.0  |      |      | haddps xmm1, xmm1
Total Num Of Uops: 6
Analysis Notes:
Backend allocation was stalled due to unavailable allocation resources.
```

Skylake / shufps:
```
Binary Format - 64Bit
Architecture  -  SKL
Analysis Type - Throughput

Throughput Analysis Report
--------------------------
Block Throughput: 10.00 Cycles       Throughput Bottleneck: Backend
Loop Count:  27
Port Binding In Cycles Per Iteration:
--------------------------------------------------------------------------------------------------
|  Port  |   0   -  DV   |   1   |   2   -  D    |   3   -  D    |   4   |   5   |   6   |   7   |
--------------------------------------------------------------------------------------------------
| Cycles |  1.0     0.0  |  1.0  |  0.0     0.0  |  0.0     0.0  |  0.0  |  2.0  |  0.0  |  0.0  |
--------------------------------------------------------------------------------------------------

DV - Divider pipe (on port 0)
D - Data fetch pipe (on ports 2 and 3)
F - Macro Fusion with the previous instruction occurred
* - instruction micro-ops not bound to a port
^ - Micro Fusion occurred
# - ESP Tracking sync uop was issued
@ - SSE instruction followed an AVX256/AVX512 instruction, dozens of cycles penalty is expected
X - instruction not supported, was not accounted in Analysis

| Num Of   |                    Ports pressure in cycles                         |      |
|  Uops    |  0  - DV    |  1   |  2  -  D    |  3  -  D    |  4   |  5   |  6   |  7   |
-----------------------------------------------------------------------------------------
|   1*     |             |      |             |             |      |      |      |      | movaps xmm2, xmm1
|   1      |             |      |             |             |      | 1.0  |      |      | shufps xmm1, xmm1, 0xb1
|   1      | 1.0         |      |             |             |      |      |      |      | addps xmm1, xmm2
|   1*     |             |      |             |             |      |      |      |      | movaps xmm2, xmm1
|   1      |             |      |             |             |      | 1.0  |      |      | shufps xmm1, xmm1, 0x1b
|   1      |             | 1.0  |             |             |      |      |      |      | addps xmm1, xmm1
Total Num Of Uops: 6
Analysis Notes:
Backend allocation was stalled due to unavailable allocation resources.
```

**Comment by yuriks** [comment]
Adding to canary for a bit just in case the feature testing explodes something somehow.

**Comment by DaMan69** [comment]
The fallback is IMO unnecessary.  Steam survey has SSE3 at 99.99%.  The fastest SSE2 only CPU is the Athlon64 FX-55 2.6GHZ.  I wouldn't even play homebrew on that.

**Comment by Subv** [comment]
According to our telemetry, all of our users support SSE3

**Comment by MerryMage** [comment]
For posterity, here are a list of x64 CPUs that don't support SSE3: https://gist.github.com/MerryMage/f5f4b3f926ae844ba437e5fe5c61f63f

Dropping fallback.

**Pull request merged**
