### PR TITLE
travis/macos/upload: Don't hardcode ffmpeg/libvorbis versions

### LINKED ISSUE #4643: Citra Nightly 1193 issue
As of 150219 1100 (GMT +8) 2 MacOS machines can't run Citra Nightly build 1193.  Both running the latest MacOS.  A 2016 MacBook Pro 15 running 10.14.3 and a 2012 MacBook Pro running MacOS 10.14.1.  Give abort code: 6.  Last running version is: 1180 (240119).  All other version give abort code 6.
screenshot 2019-02-15 at 11 03 13

### PR DESCRIPTION
**Pull request by al3xtjames**
Should fix #4643 (ffmpeg was updated to 4.1.1).

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4650)

### CODE REVIEW

**Comment by B3n30** [comment]
This will break canary builds since canary builds with ffmpeg 4.1.6

**Comment by wwylele** [comment]
@B3n30 
 - Is canary building with a different version from nightly? and why/how?
 - wouldn't this code work anyway, as it detects what version it uses?

**Comment by B3n30** [comment]
> * Is canary building with a different version from nightly? and why/how?
yes, I don't know why
> * wouldn't this code work anyway, as it detects what version it uses?
You are right. I missed that when I had a quick look. In that case: I checked it locally and it worked so LGTM

**Comment by al3xtjames** [comment]
[macpack](https://github.com/chearon/macpack) (an alternative to dylibbundler) [seems to properly bundle and patch all dependencies](https://github.com/al3xtjames/citra/commit/4e4be097f13e402ed7eb6a7bd411fb1a5f8aa2b8) (including ffmpeg) - install_name_tool doesn't have to be manually invoked. Should I open a new PR for this (and close this one)?

**Pull request merged**
