### PR TITLE
Use correct style name: PascalCase instead of CamelCase

### PR DESCRIPTION
**Pull request by chinhodado**

### CODE REVIEW

**Comment by yuriks** [comment]
LGTM

**Comment by neobrain** [comment]
Uhm, is PascalCase actually the more common thing to say? I never heared about that and find it pretty confusing. After some research, it seems that only some microsoft documentation makes a distinction between CamelCase and PascalCase...

**Comment by yuriks** [comment]
As far as I know camel case is widely understood to mean `camelCaseLikeThis`. `ThisConvention` is usually called camel case qualified with something else.

**Comment by chinhodado** [comment]
When we say PascalCase, there's no ambiguity. Camel case usually means `camelCaseLikeThis`, but can also mean `CamelCaseLikeThis` sometimes too, which is not something we would want.

**Comment by yuriks** [comment]
Can we just call it "capitalized letters joined without separators" and call it a day?

```
[18:10:20] <yuriks> I need a device that will automatically launch nuclear weapons to anihilate all humanity in case someone starts having a bikeshedding discussion
[18:10:53] <yuriks> this will either eliminate bikeshedding or it won't. In either case the outcome is probably positive
```

**Comment by neobrain** [comment]
Fair enough.

**Pull request merged**
