### PR TITLE
Assist_hle_dsp_dsp-binary_pipe3-write_process_pipe

### PR DESCRIPTION
**Pull request by Jhon59123**
[To](url) be fair this was edited and used from
https://github.com/citra-emu/citra/compare/master...MerryMage:pipe3

I have no idea how it Work's Maybe you can let us know ?, I'm not really a programmer but trying to pick up small bits.

And yes wwylele I Admit ^..  Without throwing a Paddy.

How ever it dose Assist the Write_Process_Pipe at Binary @xsacha at size and pipe number buffer[4] = 1;
https://github.com/Jhon59123/citra/blob/a753b9c6cc76a7eb3202e6d335b4da44a78e2b23/src/core/hle/service/dsp/dsp_dsp.cpp#L105

This dose help with extra sounds in Pokemon x/y as in my Uploaded Videos below "Listen Carefully 2 each video", Other games Unknown ?..

No Extra Sounds
https://www.youtube.com/watch?v=nCMdWKCMjzE

Extra Sounds with this PR
https://www.youtube.com/watch?time_continue=4&v=fOalc6OBe78

So ?..

Feel free to edit code,  If not quite wright..

Also sorry if I get a little Mild Cognitive Impairment at times.
 

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4391)

### CODE REVIEW

**Comment by tgsm** [comment]
Why are you submitting a PR of this when you have no idea how it works? Also, I don't think ban evasion is going to help your case.

**Comment by Jhon59123** [comment]
I think I have the idea, yes both audio hle and dsp work in a connected between the two that's for sure,
just trying local compiles in msvc2017 , the test worked fine, and pm x/y was a random find within the test.

 size 20 / buffer_size 20 this game is also using

When using wwylele teakra build reads

core\hle\service\dsp\dsp_dsp.cpp:Service::DSP::DSP_DSP::WriteProcessPipe:372: channel=3, size=0x20, buffer_size=20

Anyway don't matter, Citra has worse merges like that broken Stereoscopic 3D to date.

**Comment by wwylele** [comment]
@Jhon59123 Have you passed pokemon xy softlock after intro which presents in the master?

**Comment by Jhon59123** [comment]
I know it dose fix the freeze think softlock.. after the intro with your branch, But I need a up to date build to do some more testing..

Not much time tonight uk time, i'll post images in morning.

I'v not used it for a little while.

**Comment by wwylele** [comment]
@Jhon59123 What does "I know" mean? You actually managed it, or you just assumed it?

**Pull request closed without merging**
