### PR TITLE
Input gui rebase

### PR DESCRIPTION
**Pull request by Jhno591**
Request these files to fully merge correctly, thank you.

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-09-12T21:38:03Z: https://github.com/citra-emu/citra/compare/5cd37016639bcb1dea8a692562759ccf9d904b20...makotech222:964689db180c17d38f0e6834789577ea30ea1be6

**Comment by kode54** [comment]
Hey, redundant PRs aren't meant to be created as a means of upvoting existing PRs you'd like to see merged sooner. This is probably going to be closed.

**Comment by MerryMage** [comment]
Again, no.

**Comment by MerryMage** [comment]
Also, the PR has already been merged, so this was completely unnecessary.

**Comment by Dragios** [comment]
Please do not abuse the feature and use for wrong purpose as these are meant for developers to review codes.

**Pull request closed without merging**
