### PR TITLE
shared_memory: Fix assignments in SharedMemory::Map

### PR DESCRIPTION
**Pull request by lioncash**
added `this->` to `base_address` for side-by-side consistency.

### CODE REVIEW

**Comment by purpasmart96** [comment]
Great! This should help with my upcoming pr.

**Comment by yuriks** [comment]
Not sure about this one. Do we particularly use `this` in other classes?

**Comment by Subv** [comment]
LGTM

**Comment by bunnei** [comment]
@yuriks please elaborate on your issue with this?

**Comment by yuriks** [comment]
@bunnei Why is `this->` being added? We don't use it as a convention on the rest of the code or anything. (I'm not totally opposed to it, but if we're doing it we need to establish a firm guideline.)

**Comment by Subv** [comment]
yuriks, permissions is eclipsing the class member, effectively turning the line into a nop

**Comment by yuriks** [comment]
Derp.

**Pull request merged**
