### PR TITLE
 video_core: Perform quaternion correction and interpolation in fragment shader using barycentric extension.

### PR DESCRIPTION
**Pull request by Steveice10**
Builds on https://github.com/citra-emu/citra/pull/7123

Introduces the use of `VK_KHR_fragment_shader_barycentric` to perform quaternion correction from within the fragment shader, instead of relying on a fixed geometry shader. This eliminates our last need for hardware geometry shaders (bar potentially translating PICA geometry shaders in the future), allowing us to run with just a vertex and fragment shader if the extension is supported.

As seen in https://github.com/citra-emu/citra/pull/7123, eliminating the geometry shader stage can offer a nice little performance improvement. It can especially help with GPU architectures where geometry shaders are treated as legacy and thus are unsupported or more expensive to use, provided they gain support for this extension.

Force-disabled for now on MoltenVK as it advertises support for the extension but does not actually support the PerVertexKHR attribute, which we need. Hopefully it can support it in the future, as this would resolve the lack of geometry shaders under MoltenVK. See: https://github.com/KhronosGroup/MoltenVK/issues/2059

This is also not available in the OpenGL renderer currently as the extension requires using GLSL 450, which is logistically complicated given our OpenGL 4.3 context.

Using Captain Toad: Treasure Tracker as an example, I saw a roughly ~0.20ms average frame time improvement in the first  level on my Windows system, granted I'm using a fairly powerful machine so that might scale better for weaker systems that support it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7126)

### CODE REVIEW

**Comment by Wunkolo** [comment]
Can verify that it works on my RTX 3090 when utilizing the GLSL shader generator.
General availability can be seen [here](https://vulkan.gpuinfo.org/listdevicescoverage.php?extensionname=VK_KHR_fragment_shader_barycentric&extensionfeature=fragmentShaderBarycentric&platform=all).

**Comment by FearlessTobi** [comment]
Code looks okay.
Better let someone with GPU experience review this though.

**Review by GPUCode — APPROVED** [review]
Provides a 2ms frametime improvement in Dark Moon when testing with my GTX 1650

**Comment by Steveice10** [comment]
Rebased on top of fragment shader generator refactor.

**Pull request merged**
