### PR TITLE
CI: upload builds to builds.citra-emu.org instead of MEGA

### PR DESCRIPTION
**Pull request by archshift**
This uploads Linux, OS X, and Windows builds to the server at http://builds.citra-emu.org.

@bunnei: I need the encrypted password to place in these scripts. Then, I'll test it out by removing the master/PR guards. Then it'll be ready to merge. 

Uploaded builds should also be tested out on fresh installations, or VMs, of their respective platforms to make sure they can be run.

### CODE REVIEW

**Comment by linkmauve** [comment]
You should add the architecture in either the directory names or the archive names (better imo), as we are quite likely to have more than one architecture supported by platform.

**Comment by archshift** [comment]
Addressed.

**Comment by archshift** [comment]
This is ready to go. As can be seen by the [builds branch](https://github.com/citra-emu/citra/tree/builds) passing [on Travis](https://travis-ci.org/citra-emu/citra/builds/54196749) and [on AppVeyor](https://ci.appveyor.com/project/bunnei/citra/build/1.0.642). The builds have been successfully uploaded to the server.

**Comment by linkmauve** [comment]
Please use the correct name for the architecture, either x86_64 or amd64, as there are many other architectures with 64 in their name.

**Comment by archshift** [comment]
Addressed.

**Comment by linkmauve** [comment]
LGTM.

**Comment by archshift** [comment]
```
[18:04:40]  <@bunnei>	archshift, it's ready
```

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
