### PR TITLE
Kernel/SVC: Implemented svcQueryProcessMemory

### PR DESCRIPTION
**Pull request by Subv**

### CODE REVIEW

**Comment by yuriks** [comment]
Meh, instead of duplicating the code, just have one func call the other with the process pseudo-handle.

**Comment by yuriks** [comment]
LGTM

**Comment by mailwl** [comment]
and another question, is it good idea to change R4-R5 registers, if SVC call returns error?
i understand the syscall not usual function, but i... don't know, i don't like it

**Comment by yuriks** [comment]
@mailwl Since the caller can't know if the function will fail, it'll have saved the registers anyway, so there shouldn't be any harm.

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
