### PR TITLE
video_core: Initialize unrefered attributes to 1

### PR DESCRIPTION
**Pull request by GPUCode**
Fixes https://github.com/citra-emu/citra/issues/4111

Citra (master) | Citra (PR)
-|-
weapon_shop_citra | weapon_shop_citrapr

The game uses primary_color in texenv but doesn't set GPUREG_SH_OUTMAP_Oi properly, leaving the attribute uninitialized. Writing a hardware test for this shows that the default value is 1 and not 0 as previously used.

Attribute | 3DS | Citra (master) | Citra (PR)
-|-|-|-
primary_color | 3ds_color | citra_tex0_color | citrapr_color
texcoord0 | 3ds_tex0 | citra_tex0 | citrapr_tex0

Both tests were conducted with the unmodified simple_tri/textured_cube homebrew but also patching libctru to set corresponding outmap register to 0x1F1F1F1F (unused). For the texcoord test in particular, I coloured the edges of the texture to see which corner was being used (and thus which texcoord value is set).

kitten

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6966)

### CODE REVIEW

**Review by FearlessTobi — APPROVED** [review]
Thanks for looking into this!

**Comment by SachinVin** [comment]
Could the home menu have initialized it to 1?

**Comment by GPUCode** [comment]
> Could the home menu have initialized it to 1?

Shader output registers are not writeable from the CPU

**Comment by SachinVin** [comment]
I guess the question should be, if the register is intialised every time the shader is run, or does it keep the value from the previous run

**Comment by GPUCode** [comment]
Oh I see what you mean now. The PR doesn't initialize a register to 1, but rather the output vertex.
What happens here is that the vertex shader runs normally and ouputs its results to the output registers. Then the GPUREG_SH_OUTMAP_Oi registers are used to map these output registers to the final vertex (for example the x component of o0 register will be position.x). The game doesn't configure a map for primary_color at all which causes the issue

**Comment by GPUCode** [comment]
There could be some retension but I'm not sure how to test that

**Comment by SachinVin** [comment]
Alright thanks for explaining!

**Pull request merged**
