### PR TITLE
scm_rev: Simplify the revision system to use a single header file.

### PR DESCRIPTION
**Pull request by adityaruplaha**
* Updated to use C++17 `constexpr auto`
* Clang-format

Tested on VS2019. No CMake errors.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4724)

### CODE REVIEW

**Comment by lioncash** [comment]
Note that the reason for the split was so that the strings weren't duplicated into every single translation unit that references them, wasting space in the binary.

**Comment by wwylele** [comment]
What's the motivation for this? VS2019?

**Comment by adityaruplaha** [comment]
Motivation:
* Code simplification
* Clang format
* Using C++17 `constexpr auto` as it was applicable here.

Lioncache has got a point, I think I'll revert those changes. But I think
those might get optimised out during LINK (?)

Will check the final binary size, and report back.

**Comment by lioncash** [comment]
They aren't allowed to be optimized out. If something is internally linked from namespace scope and two different translation units reference that entity, they're required by the language to each get a copy of said entity. This is because the address of the entity can be taken or used (therefore a compiler cannot optimize it out in that case at link time). The use of an address is inherent with strings, since an array of characters is essentially an address with a bounded size.

**Comment by adityaruplaha** [comment]
In that case I'm going to close this.

**Pull request closed without merging**
