### PR TITLE
Clang-cl support Citra

### PR DESCRIPTION
**Pull request by freiro**
I currently got clang-cl to fully compile a working version of citra, this PR works without problems and it's a first step to fully support clang-cl as a compiler.
(I actually wanted to PR this to my own repo, but is ready)

I am interested in feedback from Linux (using clang) and macOS.

### CODE REVIEW

**Comment by MerryMage** [comment]
This has never been necessary in my experience. 

For the record I just did a build with cmake 3.4.1 and clang-cl 3.8.0.

**Comment by freiro** [comment]
@MerryMage that's the point of the discussion we were having.

**Comment by JayFoxRox** [comment]
Which discussion? There is no discussion on record here at github.

**Comment by freiro** [comment]
Well, to sum this up:
a few days ago Citra wasn't able to compile on Windows using cmake (3.5.2 iirc) + clang-cl 3.9.0, the error was: 
> clang-cl.exe : error : unknown argument ignored in clang-cl: '-std=c++14'
And this is the error the PR was targeting.

In the attempt to solve the other errors related to dynarmic (broken cpu jit and missing compiler flags) I updated to Cmake 3.7.1 and clang-cl 4.0.0 (r284979). 

Merry told me she didn't encounter this error before, I double checked on the latest master and it works without patchs.
I tried with an older cmake and still works, this might have been a bug in that specific version I was using.

**Pull request closed without merging**
