### PR TITLE
Remove built-in disassembler and related code

### LINKED ISSUE #427: Qt: Disassembler view *always* loads 125000 lines (500000 bytes) no matter how big the .code is.
Probably due to [this crazy function](https://github.com/citra-emu/citra/blob/master/src/citra_qt/debugger/disassembler.cpp#L102-L136) which populates the disasm with 125000 lines, with no concern for how large the .code actually is.

### PR DESCRIPTION
**Pull request by yuriks**
The commit messages have some additional justification, but it's mostly just straightforward deletion of code.

Closes #427, #1480, #586, #1632, #1280

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2689)

### CODE REVIEW

**Comment by yuriks** [comment]
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2689)

**Comment by archshift** [comment]
RIP

**Comment by jroweboy** [comment]
(Perhaps too cautious but should we put this in bleeding edge for a quick test?)

**Comment by sin3point14** [comment]
:'(

**Pull request merged**
