### PR TITLE
Updates to github actions

### PR DESCRIPTION
**Pull request by vitor-k**
Updates multiple actions used in the CI.
Fixes msvc builds not having the proper names.
Resolves some CI deprecation warnings by dropping the use of the get-git-tag action. This replaces the action by a regex match (GIT_TAG_NAME would be empty if the release is not tagged, while GITHUB_REF_NAME would have the branch name.)
The deprecated commands are set to be removed on the 31st of May, starting to error out on the 1st of June.

For reference:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6358)

### CODE REVIEW

**Comment by SachinVin** [comment]
Android need an update too, https://github.com/citra-emu/citra/blob/master/src/android/app/build.gradle#L157

**Review by liushuyu — APPROVED** [review]
LGTM

**Comment by vitor-k** [comment]
Pushed commits updating the scm_rev generation and addressing android too (well, sidestepping the issue because I don't know enough about gradle syntax).
There's a small change in behavior as now branches created in the citra-emu/citra-canary or citra-emu/citra-nightly repositories with the canary/nightly-([0-9]+) naming convention would set the BUILD_FULLNAME the same way as if they were a tag, but I don't think this is likely to be a problem.

**Comment by SachinVin** [comment]
Seems tag isn't working on android

**Comment by vitor-k** [comment]
> Seems tag isn't working on android

Fixed

**Pull request merged**
