### PR TITLE
citra-qt: Fixed some Qt errors on initialization

### PR DESCRIPTION
**Pull request by Subv**
Fixes two errors from #449
```
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferWidthChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:87
QObject::connect:  (receiver name: 'PicaFramebuffer')
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferHeightChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:88 
QObject::connect:  (receiver name: 'PicaFramebuffer')
````

The other error is caused by a connect call on an invalid object, this->windowHandle() returns nullptr in the GRenderWindow constructor, I don't know of a proper way to fix this

### CODE REVIEW

**Comment by yuriks** [comment]
I believe this function parameter was changed from `int` to `unsigned int` to fix a warning. Is there any way you can fix this without reintroducing it? Can you change the other end of connecting signal/slot pair instead?

**Comment by Subv** [comment]
I can't change the other end, it's part of the Qt library itself.

**Comment by yuriks** [comment]
Oh well. Then at least add explicit casts to prevent re-introducing the warning.

**Comment by neobrain** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
