### PR TITLE
Bump clang format to 15

### PR DESCRIPTION
**Pull request by SachinVin**
For: https://github.com/citra-emu/build-environments/pull/55

ext-windows-bin https://github.com/citra-emu/ext-windows-bin/pull/35

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7014)

### CODE REVIEW

**Comment by Steveice10** [comment]
This will probably need code formatting updates once it's able to be tested, going by all the additional changes I usually get locally using clang-format 15

**Comment by SachinVin** [comment]
For some reason running `make clang-fomat` doesn't create diffs, I wonder if it is still using the old version...
I'll probably try something else

**Comment by Steveice10** [comment]
Worst case, with the update to clang-format-15 pulled into the build image you can check the CI output.

**Comment by SachinVin** [comment]
Probably what I'll end up doing

**Comment by SachinVin** [comment]
Hey, my local clang format didn't lie!

**Pull request merged**
