### PR TITLE
Implement svcBreak

### PR DESCRIPTION
**Pull request by archshift**

### CODE REVIEW

**Comment by Subv** [comment]
Is it ok to let it continue execution after this?

**Comment by archshift** [comment]
Ostensibly no, but I'm not sure what the best way to break execution would be from here. I don't think an assert would be appropriate.

**Comment by yuriks** [comment]
Breaking execution here would cause many titles that currently boot to stop booting. I think we should hold off on that for a while longer.

**Comment by yuriks** [comment]
LGTM btw

**Comment by Subv** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
