### PR TITLE
http svc moved to its own sub directory

### PR DESCRIPTION
**Pull request by jfmherokiller**
I believe this pull request will help in the organization of the code

### CODE REVIEW

**Comment by wwylele** [comment]
I think the current convention is to make sub directories only for service that contain multiple ports. http module only contains one port `http:C` (according to 3dbrew) so no need to make a sub directory?

Even if a sub directory is preferred, why not make sub directories for all services?

**Comment by mailwl** [comment]
why? http:C is alone service

**Comment by jfmherokiller** [comment]
so that if it get split into multiple files during implementation it wont dirty the service directory

**Comment by mailwl** [comment]
implemetation will go to /externals

**Comment by wwylele** [comment]
@jfmherokiller A service implementation getting split into multiple files only happens in the following cases:
 - it contains multiple ports. This happened to most services in sub directories. But it won't happen to http service unless someone find out it has multiple ports.
 - the implementation is so huge that one file can't hold it. This happened to `fs:user` and `ldr:ro`. But This should be decided by who actually implement the service, and the split should be go with the implementation PR

**Comment by darkf** [comment]
This was done in WIP implementations of http:C which had more than one implementation file. If someone plans on picking one of those up, they should probably do it.

**Comment by jfmherokiller** [comment]
so is this pull request a good idea or bad idea? ill close it if it was a bad idea

**Comment by mailwl** [comment]
mostly bad.
but there is another services, like soc:U & soc:P, which nobody cares, because privileged ports not used in games

**Comment by jfmherokiller** [comment]
ok closing it then

**Pull request closed without merging**
