### PR TITLE
[WIP] dynarmic updates

### PR DESCRIPTION
**Pull request by MerryMage**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3153)

### CODE REVIEW

**Comment by MerryMage** [comment]
Changelog from <tt><a href="https://github.com/MerryMage/dynarmic/compare/dfbd3912a4b8e0d28e1a4045893a750f0107fbaa...993946fad84441aefd39e311a08147e2fc50b007">dfbd39...993946</a></tt>:

<table>
<tr>
<th>Purpose</th>
<th>Commit</th>
</tr>
<tr>
<td rowspan=2>Minor VFP bug fix; corrects FPSCR values</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/3e4b02dd40de3e49a71fb7e0980591fb6e014b27"><tt>3e4b02</tt></a>: skyeye: Correct assumption that VFP_REG_ZERO will always be zero</td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/c421a137c09aecb0f55a480fb59cc0dce09f2628"><tt>c09aec</tt></a>: VCMP and VCMPE were the other way around</td>
</tr>

<tr>
<td>Small speed improvement in VFP heavy games.</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/f050825d4db6c3d3bb54e2559ab2a3088f745da0"><tt>f05082</tt></a>: emit_x64: Improve code emission of FPCompare{32,64} </td>
</tr>

<tr>
<td rowspan=5>Speed improvement in games that heavily use packed instructions.<br>You should see a speed improvement in FMV sequences.</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/81c5322f40671bfc9091bad2796c5f99f49b3e18"><tt>81c532</tt></a>: emit_x64: Remove SSSE3 implementation of PackedHalvingAddU8</td>
</tr>

<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/311b6609aae93c2760b05e8b482d03cd302e6636"><tt>311b66</tt></a>: Implement IR instruction PackedSelect, reimplement SEL</td>
</tr>

<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/c1dd87aeebbee5e894c2aab47956d9a5cea52536"><tt>c1dd87</tt></a>: fuzz_arm: Test SEL alongside packed instructions</td>
</tr>

<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/6f4affd67f3cc6425a37758e359644122113c5ad"><tt>6f4aff</tt></a>: emit_x64: Eliminate conversion of GE flags</td>
</tr>

<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/993946fad84441aefd39e311a08147e2fc50b007"><tt>993946</tt></a>: emit_x64: Perform mask creation for packed instructions in SSE</td>
</tr>

</table>

**Comment by Subv** [comment]
Shouldn't 3e4b02 be ported to dyncom in the citra repo?

**Comment by tabnk** [comment]
Super Mario 3D Land is 2% slower than master build

**Comment by YOUDONTSAYMEMEWILLBEMINE** [comment]
3-5% speed improvement in ORAS.

**Comment by YOUDONTSAYMEMEWILLBEMINE** [comment]
3-4% speed improvement in Sun and Moon and all of the stutter is gone.

**Comment by MerryMage** [comment]
Changelog from <tt><a href="https://github.com/MerryMage/dynarmic/compare/993946fad84441aefd39e311a08147e2fc50b007...bb87d2540c9e39d6ef51acfee6b3e0fcaa8c9664">993946...bb87d2</a></tt>:

<table>
<tr>
<th>Purpose</th>
<th>Commit</th>
</tr>

<tr>
<td>Lioncash drags us into the modern world of cmake</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/87c9b0affe73ca6ab41f62b94274aa8e16045ea9"><tt>87c9b0a</tt></a>: CMakeLists: Derive the source file listings from targets directly (#&#8203;118)</td>
</tr>

<tr>
<td rowspan=6>IsLastUse optimization: Reduction in register spillage<br/><br/>Also removes DecrementRemainingUses whose existence has been annoying me for a while.</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/e53d00905fd0518ce7a234888ebf01d829e21719"><tt>e53d00</tt></a>: Revert "reg_alloc: Improve performance of HostLocInfo (#&#8203;112)"</td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/6776f83a0c36c187ea211e1d57322531e604a051"><tt>6776f8</tt></a>: basic_block: Add inst address and use count to DumpBlock </td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/92ae4c783bd484ec00f4c76f1f7d25366a10313c"><tt>92ae4c</tt></a>: emit_x86: Standardize time of DefineValue call</td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/44e6ce33d4d6801c623f14909faa12be1bed6423"><tt>44e6ce</tt></a>: reg_alloc: Add IsLastUse optimization for UseScratch </td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/8e454186302efa2d7f387ca93fc69ce3d4740931"><tt>8e4541</tt></a>: reg_alloc: Remove reliance on IR::Inst::DecrementRemainingUses </td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/67c8e6e6951d65a01b1ec41a42433e0948313951"><tt>67c8e6</tt></a>: microinstruction: Remove DecrementRemainingUses</td>
</tr>

<tr>
<td rowspan=2>Remove warnings introduced in GCC6.</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/1d75664afd8c34dfe7b1427a5865f06f07829562"><tt>1d7566</tt></a>: Remove UNUSED macro</td>
</tr>
<tr>
<td><a href="https://github.com/MerryMage/dynarmic/commit/5f64bf9cfae72e6862c5b0256996e32e03e8ceeb"><tt>5f64bf</tt></a>: decoder_detail: Lambda captures may be unused if iota is an empty seqence</td>
</tr>
<tr>
<td>-</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/355d65ec0da931a69c88a1a1e069b82ae25a8056"><tt>355d65</tt></a>: CMakeLists: Default to a Release build</td>
</tr>
<tr>
<td>Resolve compilation issues with boost 1.66.0 beta 1</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/bb87d2540c9e39d6ef51acfee6b3e0fcaa8c9664"><tt>bb87d2</tt></a>: Remove unnecessary use of boost::make_optional</td>
</tr>
</table>

**Comment by MerryMage** [comment]
Updates subsumed by #3184.

**Comment by MerryMage** [comment]
Changelog from <tt><a href="https://github.com/MerryMage/dynarmic/compare/bb87d2540c9e39d6ef51acfee6b3e0fcaa8c9664...b6b061f2447fffc2947fb0815738ed9ec9b02797">bb87d2...b6b061</a></tt>:

<table>
<tr>
<th>Purpose</th>
<th>Commit</th>
</tr>

<tr>
<td>Required for future CRO optimizations</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/6131d0e053431c025b92411162364da385d07327"><tt>6131d0</tt></a>: BlockOfCode: Detect space remaining</td>
</tr>

<tr>
<td>Improve JIT timing</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/024fa2461c40154be849d65728204866e0a51ce8"><tt>024fa2</tt></a>: Add AddTicks and GetTicksRemaining callbacks</td>
</tr>

<tr>
<td>~10% speed improvement<br><br>due to unnecessary MXCSR switching</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/f343c56268ef3f8fbed5bbc513fbc56430a47255"><tt>f343c5</tt></a>: block_of_code: Move MXCSR switching out of dispatch loop</td>
</tr>

<tr>
<td>~5% speed improvement<br><br>due to unnecessary register spills</td>
<td><a href="https://github.com/MerryMage/dynarmic/commit/b6b061f2447fffc2947fb0815738ed9ec9b02797"><tt>b6b061</tt></a>: emit_x64: Remove unnecessary ABI overhead in ReadMemory, WriteMemory </td>
</tr>

</table>

**Comment by MerryMage** [comment]
All updates in this PR have been merged.

**Pull request closed without merging**
