### PR TITLE
Change size formatting

### PR DESCRIPTION
**Pull request by adityaruplaha**
~I've never seen units used with an "i" before the "B". I guess we should remove them.~

img_20180302_214414

Also any idea why the sizes have a "," instead of a decimal point? I'll fix that too.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3464)

### CODE REVIEW

**Comment by wwylele** [comment]
https://en.wikipedia.org/wiki/Binary_prefix

**Comment by Dragios** [comment]
@adityaruplaha Which means you did not do your research. It is used for binary prefix. The one without 'i' is used in decimal prefix which is more commonly used. Also refer comment ^

**Comment by adityaruplaha** [comment]
Well, well, I always used binary prefix, but without the I. Sorry!

**Comment by adityaruplaha** [comment]
I'll still fix the issue with the decimal point though. Can anyone tell me what may cause it?

**Comment by wwylele** [comment]
I am not sure what decimal point issue is. Could you elaborate it?

**Comment by jroweboy** [comment]
@adityaruplaha https://en.wikipedia.org/wiki/Decimal_separator its an internationalization thing and not a real issue. the %L specifier uses the current locale to choose a period or a comma, and your locale is set to use commas instead.

**Comment by wwylele** [comment]
Closing as this is a non-issue on citra side

**Comment by adityaruplaha** [comment]
Ok thanks. I'll try to tweak my locale.

**Pull request closed without merging**
