### PR TITLE
hle: Reduce Y2R stub warnings to debug logs.

### PR DESCRIPTION
**Pull request by Steveice10**
These stub log messages spam a lot during FMVs but are often of little consequence. Lowers them to debug level, same as most other stubs in Y2R, to reduce log size and noise when diagnosing other problems.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6617)

### CODE REVIEW

**Review by FearlessTobi — APPROVED** [review]
Thanks, this has bothered me for a while.

I have only seen Get/SetTransferEndInterrupt spammed in logs though.
Maybe it's enough to only lower those to DEBUG?

**Comment by Steveice10** [comment]
> I have only seen Get/SetTransferEndInterrupt spammed in logs though. Maybe it's enough to only lower those to DEBUG?

Most of the stubs in Y2R for similar functions are already debug level, it's just these few that weren't so I moved them all over for consistency. None of them seem particularly noteworthy but if we identify anything important we can always move them back to warnings if needed.

**Comment by FearlessTobi** [comment]
If we already have several other functions as debug, then it's fine to leave it I guess.

**Comment by KostaSaizo7** [comment]
Maybe relates to https://github.com/citra-emu/citra/issues/6550?

**Comment by FearlessTobi** [comment]
I don't think so

**Pull request merged**
