### PR TITLE
Pica: Correct switched S/T texture wrapping registers

### PR DESCRIPTION
**Pull request by yuriks**
This was found and hwtested by Lectem in https://github.com/Lectem/3DS_gpu_tests/tree/wrap_modes

### CODE REVIEW

**Comment by neobrain** [comment]
Once ready, please provide a link to a hardware test homebrew app.

**Comment by yuriks** [comment]
Added a link to Lectem's test.

**Comment by neobrain** [comment]
@Lectem What revision of ctrulib was that test written against?

**Comment by Lectem** [comment]
Well, it was built against https://github.com/smealum/ctrulib/commit/096bbdf40155fda036ba517a40f59c5796a8013a but https://github.com/smealum/ctrulib/commit/4109bf5b66d1d29ad816f327be49c0b82ec28f30 fixed it.

**Comment by neobrain** [comment]
So if anyone wants to build the test, they should use smealum/ctrulib@096bbdf. Thanks.

**Comment by yuriks** [comment]
While that's the case for verifying things against the future, any version if fine to just compare Citra vs. HW since the results will have to be consistent on both.

**Pull request merged**
