### PR TITLE
opengl: disable ClearTexture on Intel drivers

### PR DESCRIPTION
**Pull request by vitor-k**
drivers for old intel hd graphics (Haswell era) report support for ArbClearTexture but users have reported black screens since glClearTexSubImage usage has been introduced.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6879)

### CODE REVIEW

**Review by GPUCode — APPROVED** [review]

**Comment by SachinVin** [comment]
If it is only haswell we can probably do an additional check for the driver version

**Comment by vitor-k** [comment]
> If it is only haswell we can probably do an additional check for the driver version

Actually I just checked more reports and it probably affects Broadwell too. Reportedly happened on an HD Graphics 5500.
Considering the ARB was incorporated into the 4.4 spec, which Broadwell is supposed to support, that's bad. Latest drivers too.

I'll add a mention of Broadwell to the note.

As for checking based on driver version, I'm not sure the numbering is sane enough for that (besides checking for exact matches).
Checking the renderer would work for the most part, though a bit verbose (Haswell has HD 5000, 4600, 4400 and 4200; Iris Pro 5200, Iris 5000 and 5100. Broadwell has Iris Pro 6200 and P6300, Iris 6100 and HD 6000, P5700, 5600, 5500, 5300 and HD Graphics (Broadwell))

**Comment by SachinVin** [comment]
> 6th Generation Intel® Core processors, Intel Core™ M, and related Pentium® processors with Intel® HD Graphics 510, 515, 520, 530
5th Generation Intel® Core processors with Intel HD Graphics 5500, 5600, 6000, Intel Iris™ Graphics 6100, Iris Pro Graphics 6200 and select Pentium®/ Celeron® processors with Intel® HD Graphics
Intel® Core™ M with Intel HD Graphics 5300 
4th Generation Intel® Core™ Processors with Intel HD Graphics 4200, 4400, 4600, 5000, Intel Iris™ Graphics 5100 and Intel Iris Pro Graphics 5200 and select Pentium®/ Celeron® Processors with Intel® HD Graphics

https://www.intel.com/content/www/us/en/download/18388/intel-graphics-driver-for-windows-10-15-40-4th-gen.html

They might all be using the same driver from 2015

**Comment by SleepingSnakezzz** [comment]
Correct. Anything 6th gen and up get newer drivers without these issues. Anything below (that's still supported anyways) has these issues.

**Comment by vitor-k** [comment]
Yeah I don't know about matching the driver.
The last number of the driver is the relevant part on legacy drivers, but it's not guaranteed a lower number is an older driver, across the legacy and whql drivers (the broken driver is 5171, from 2021, meanwhile the latest driver for 7th-10th gen is 2125)
A legacy driver can be called something like 15.40.48.5171, meanwhile when installed it's reported as 20.19.15.5171.

Actually while I was writing this I found an explanation from Intel (<https://www.intel.com/content/www/us/en/support/articles/000005654/graphics.html>), so we can _probably_ check the second-last number and allow it if it's 100 or higher

**Comment by SleepingSnakezzz** [comment]
I generally instruct users to download this one instead: https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html (31.0.101.2115)
Since it's hard to tell whether some Pentium or Celeron chips are 6th or 7th gen. (cuz Intel doesn't always fecking tell you on their product pages like the monkeys they are).

Intel dropped driver support for 6th-10th gen all at the same time, but still created a separate driver page for 7th-10th gen afterwards. So their site randomly decides to give you either the 6th-10th gen, or the 7th-10th gen driver, when searching for your (i)GPU on their website. Since those idiots didn't think to update the driver pages for every one of their poorly named products.

**Pull request merged**
