### PR TITLE
[WIP] amiibo AppData read/write

### PR DESCRIPTION
**Pull request by celerizer**
This PR offloads reading a binary amiibo file to the NFC module instead of Qt UI, implements several NFC services for reading/writing amiibo, and corrects the branding in the UI.

Other things that might be needed:
- Automatic decryption of amiibo, if the user provides the keys; currently the amiibo needs to already be decrypted
- HLE amiibo Settings applet; currently only amiibo dumps that have already been set up on a real 3DS work
- Utilizing the current date to write back to an amiibo, rather than a dummy
- A few more services (GetTagInfo2, CommunicationGetResult, GetAppDataInitStruct, SetAmiiboSettings)
- Maybe making a pure virtual "Amiibo" class and subclassing it out to encrypted/decrypted versions? I don't think there's enough in the implementation to make that necessary 

I'm submitting this for review and to see what else should be added before merging.

Related: #5492

Video : https://www.youtube.com/watch?v=ffgp6PzEeGc

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5506)

### CODE REVIEW

**Comment by celerizer** [comment]
```
[ 151.353186] Service.NFC <Info> core\hle\service\nfc\nfc.cpp:Service::NFC::Module::Interface::LoadAmiibo:630: Loaded a decrypted amiibo from F:/msys64/home/celerizer/citra/build/src/citra_qt/corrupt.bin.
[ 151.447793] Service.NFC <Warning> core\hle\service\nfc\nfc.cpp:Service::NFC::Module::Interface::LoadAmiiboData:443: (STUBBED) called
[ 151.448027] Service.NFC <Warning> core\hle\service\nfc\nfc.cpp:Service::NFC::Module::Interface::GetAmiiboSettings:225: Failed because amiibo is not setup.
[ 151.465562] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function '0x0e0080': port='act:u' cmd_buf={[0]=0xe0080, [1]=0xfe, [2]=0xfffffffe}
[ 156.175860] Service.NFC <Warning> core\hle\service\nfc\nfc.cpp:Service::NFC::Module::Interface::Shutdown:133: (STUBBED) called, param=2
[ 156.177980] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'GetAppletProgramInfo': port='APT:A' cmd_buf={[0]=0x4d0080, [1]=0x119, [2]=0x11}
[ 156.179230] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[ 156.179545] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'PrepareToStartSystemApplet': port='APT:A' cmd_buf={[0]=0x190040, [1]=0x119}
[ 156.180176] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Module::APTInterface::AppletUtility:533: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[ 156.181007] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'SaveVramSysArea': port='gsp::Gpu' cmd_buf={[0]=0x190000}
[ 156.181854] Audio.DSP <Info> audio_core\hle\hle.cpp:AudioCore::DspHle::Impl::PipeWrite:273: Application has requested sleep of DSP hardware
[ 156.181857] Debug <Critical> audio_core\hle\hle.cpp:AudioCore::DspHle::Impl::PipeWrite:274: Unimplemented code!
[ 156.183309] Service.DSP <Info> core\hle\service\dsp\dsp_dsp.cpp:Service::DSP::DSP_DSP::RegisterInterruptEvents:259: Unregistered interrupt=2, channel=2
[ 156.183687] Service.DSP <Info> core\hle\service\dsp\dsp_dsp.cpp:Service::DSP::DSP_DSP::UnloadComponent:200: (STUBBED)
[ 156.184022] Service.GSP <Warning> core\hle\service\gsp\gsp_gpu.cpp:Service::GSP::GSP_GPU::ReleaseRight:737: called
[ 156.184469] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'ReplySleepQuery': port='APT:A' cmd_buf={[0]=0x3e0080, [1]=0x300, [2]=0x0}
[ 156.184739] Service <Error> core\hle\service\service.cpp:Service::ServiceFrameworkBase::ReportUnimplementedFunction:161: unknown / unimplemented function 'StartSystemApplet': port='APT:A' cmd_buf={[0]=0x1f0084, [1]=0x119, [2]=0x2c4, [3]=0x0, [4]=0x0, [5]=0xb10002, [6]=0xffffb50}
[ 156.185045] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::Module::APTInterface::AppletUtility:533: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[ 156.185436] Service.GSP <Warning> core\hle\service\gsp\gsp_gpu.cpp:Service::GSP::GSP_GPU::ImportDisplayCaptureInfo:692: called
```
This is what Citra outputs when trying to open the amiibo Settings applet. It looks like more base applet stuff needs to be worked in before it can be imitated.

**Comment by AbreuEfechou** [comment]
@zhaowenlan1779 This is a very requested feature. Could you take a look at this implementation please?

**Comment by celerizer** [comment]
It looks like I'll need to rebase this because of changes to main.cpp in the Qt code.

**Comment by Shideravan** [comment]
Would be nice if this can be refactored. It's really a nice improvement to the emulator and one of the main reasons to use.

**Comment by Shideravan** [comment]
> It looks like I'll need to rebase this because of changes to main.cpp in the Qt code.

Maybe now it's a more appropriate time for it, as @SachinVin is checking relevant issue fulfillment to incorporate in the main code. And let's be real: amiibo write it's very important for a lot users thinking on citra operation

**Comment by FearlessTobi** [comment]
Superseded by https://github.com/citra-emu/citra/pull/6340.

**Pull request closed without merging**
