### PR TITLE
citra_qt/system: Add N3DS mode checkbox and enable it by default

### PR DESCRIPTION
**Pull request by FearlessTobi**
This change should be fairly self-explanatory.
For all users who haven't messed with this setting before, it is no enabled by default.
Also a checkbox is added to the System settings to be able to toggle it.
I will add a screenshot as soon as I get QT Automoc to run again locally.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5117)

### CODE REVIEW

**Comment by B3n30** [comment]
the obilgatory screenshot for ui changes is missing :D

**Comment by B3n30** [comment]
Code wise looks good, but it should only get merged after #5104

**Comment by FearlessTobi** [comment]
Untagging because of conflicts.

**Comment by FearlessTobi** [comment]
UI Screenshot:
Unbenannt

**Comment by B3n30** [comment]
Please fix conflicts and add to canary

**Comment by Dragios** [comment]
Reduces performance significantly for **The Sims™ 3** and **The Sims 3 Pets** if New 3DS mode is turn on. I guess this is expected if the game rely on clockspeed entirely. Increase clock speed will result in increase processing power for host CPU.

**Pull request merged**
