### PR TITLE
Fix compilation without ENABLE_WEB_SERVICE

### PR DESCRIPTION
**Pull request by GPUCode**
Addresses https://github.com/citra-emu/citra/pull/6828#discussion_r1284331566
While at it I've also fixed https://github.com/citra-emu/citra/issues/6853 by adding a new option ENABLE_SCRIPTING that enables/disables the RPC server. It's OFF by default because scripting is not functional at the moment

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6856)

### CODE REVIEW

**Review by Steveice10 — APPROVED** [review]
LGTM except I think the boost update being included was a mistake.

**Comment by SachinVin** [comment]
Scripting is functional though?

**Comment by GPUCode** [comment]
ENABLE_SCRIPTING is now enabled by default

**Comment by dmanlfc** [comment]
just ran into this problem, it would be good to get resolved, thanks.

**Pull request merged**
