### PR TITLE
qt_themes: add two colorful themes

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
These two colorful themes are based on the Default and Dark themes, and contain icons that are colored rather than black and white. These icons come from https://icons8.com and they have been slightly revised by me. I'm pretty sure I was licensed to use them for Citra.

Screenshots:
Colorful theme:
image
lobby
initial

Colorful theme (Dark style):
image
lobby
initial

The "connected"/"disconnected" icon on the status bar has also been replaced in these two themes.

Hope you like this :)

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4004)

### CODE REVIEW

**Comment by neobrain** [comment]
https://icons8.com/license/

    The icons, sounds, and photos are free for personal use and also free for commercial use, but we require linking to our web site

**Comment by zhaowenlan1779** [comment]
@neobrain 
Nope. They don't require linking for "popular open source projects", and I have showed them the link to Citra repo. Then they issued me a license.

**Comment by j-selby** [comment]
@zhaowenlan1779 well, going to need to see something to prove that, honestly.

**Comment by zhaowenlan1779** [comment]
@j-selby I do think you are being too cautious, but never mind, I can understand it's important. Is this chat transcript enough? It is stored in my mailbox, btw.
image

**Comment by j-selby** [comment]
That is exactly the same license as what Neobrain said above - you realistically need to give attribution somewhere

**Comment by zhaowenlan1779** [comment]
@j-selby Well, I won't consider "We would appreciate if ...." as a **requirement**.
Also, they are different license types.
image

Actually I could have just used icons from different websites, but I was just too lazy. Check it above.

**Comment by j-selby** [comment]
"we would appreciate if [...]"

Feels disingenuous to be waltzing our way around that, honestly. It would be in poor taste to not.

**Comment by neobrain** [comment]
> I do think you are being too cautious

No, we are not. Licenses are difficult business, and it looks like you're not taking that seriously at all.

> Actually I could have just used icons from different websites, but I was just too lazy

That is not a good mindset for contribution.

I'll be closing this - I don't consider the icon set of high quality to begin with, and it looks like there's some very conceptual misunderstandings we'd need to clarify here to even get this PR on the right track in the first place. Our efforts need to be spent elsewhere, and I'd rather see icons designed from scratch instead.

**Comment by B3n30** [comment]
Didn't we have a readme inside the icons folder that documents the origin of each icon as well as the license? Also for stuff like the license of icon8 a link in the about msg box should be appropriate.

**Comment by B3n30** [comment]
I will reopen this since we agreed that every icon will get proper documentation of the license (even if the license doesn't require it). 
> I don't consider the icon set of high quality
 is very subjective so this is no reason to let this stay closed.

I would prefer to get #4019 merged first and then add the documentation of the origin of those files and the license to that license.md file. 

> Our efforts need to be spent elsewhere, and I'd rather see icons designed from scratch instead.
using existing icons seems like a good way to aviod spending hours in designing new icons.

@neobrain any other suggestions to get this PR `on the right track` are highly welcome

I hope that ends the discussion about licenses regarding the usage of icons/logos/pictures inside citra. But for clarification, we agreed: Every icon/logo/picture used in citra needs to be documented with origin/author and license even if the license states 100% free use. This will also affect already existing icons/logos/pictures. We will add proper documentation and remove/replace them if necessary

**Pull request merged**
