### PR TITLE
Add 3DS room support

### PR DESCRIPTION
**Pull request by Dante38490**
Support all Room 3DS

### CODE REVIEW

**Comment by yuriks** [comment]
".3ds" files are the same as ".cci" files, just with a different extension. Given we already support that, I don't know why you added a new loader, and on top of that, why it's a copy&paste of the 3dsx loader, which is completely unrelated...

**Comment by Dante38490** [comment]
I know I did a copy and paste of 2 3dsx renomant the file and modifying some online, but I just really do not understand why the 3ds file was not yet supported, whereas absolutely all the room are .3ds format.

**Comment by purpasmart96** [comment]
Ummm, the .3ds format is not the same as the .3dsx format.

**Comment by Dante38490** [comment]
I also think but hey, what I did was just so Citra opens .3ds file, I think it will change the file 2, but I think the key is already.

**Comment by purpasmart96** [comment]
@Dante38490 the .cci format is the same as the .3ds format, so there is no need for the extra loader, in fact all you had to do was change all the ".cci"s to ".3ds"

**Comment by Dante38490** [comment]
Thin Oh, if I had known I was not aware of it at the base.
But I do not know how to make the .3ds go see cci, hmm.

**Comment by purpasmart96** [comment]
@Dante38490 if you rename a ".3ds" file to ".cci". It will work

**Comment by Dante38490** [comment]
I really thought the cci, was very different from the 3ds has like a .elf and a eboot.bin for ps3.
Bad idea I think it works so, but I think it would have citra can load a 3ds file without problem, without having to rename it.

**Pull request closed without merging**
