### PR TITLE
hw/aes: Clean up key generator.

### PR DESCRIPTION
**Pull request by Steveice10**
* Remove support for parsing keys from NATIVE_FIRM.
  * This is not fully adequate for our needs and user logs sometimes indicate that their NATIVE_FIRM doesn't actually match what we're looking for, making it a no-op.
  * Additionally this was never fully implemented for New 3DS firmware, meaning we have to fall back on aes_keys.txt for certain important keys for New 3DS users anyway.
  * Even with this removed, as long as the user has at minimum the `boot9.bin` and `aes_keys.txt` from threeSD their installed titles should still function.
* Fix an issue where any text after what we look for in a key name would not be considered. Now we make sure that when we parse the key name, the full name has been parsed and not just part of it.
* Few minor cleanups and typo fixes. For example there was a function defined in the header that did not actually exist.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7143)

### CODE REVIEW

**Comment by SleepingSnakezzz** [comment]
We really should update ThreeSD to include the new key dumper then, right?

**Comment by Steveice10** [comment]
> We really should update ThreeSD to include the new key dumper then, right?

I don't really know much about getting ThreeSD updated since it's not even under our org, but currently just using threeSD dumps to get keys is not very useful for the reasons specified in the OP.

**Comment by Steveice10** [comment]
threeSD also dumps decrypted so I don't think there's necessarily an urgent need for them to be paired either.

**Comment by Steveice10** [comment]
Addressed by re-adding boot9 parsing and only removing NATIVE_FIRM parsing, which retains compatibility with encrypted titles installed using threeSD data.

**Review by FearlessTobi — COMMENTED** [review]
Code looks good.
Are the other concerns with retaining key loading functionality addressed now?

**Comment by Steveice10** [comment]
> Code looks good. Are the other concerns with retaining key loading functionality addressed now?

Yes, for launching encrypted games the bootrom and keys file provided by threeSD is sufficient.

**Pull request merged**
