### PR TITLE
cmake: Use ccache if available.

### PR DESCRIPTION
**Pull request by degasus**
This code is written by florent.castelli@gmail.com for the dolphin project.
Please see https://github.com/dolphin-emu/dolphin/commit/17187694f687a6235688f71c07c5aeb3de2b319f for more details.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3717)

### CODE REVIEW

**Comment by wwylele** [comment]
How does it interact with the existing CI script that uses ccache? For example here https://github.com/citra-emu/citra/blob/master/.travis/linux/docker.sh#L14

**Comment by liushuyu** [comment]
>How does it interact with the existing CI script that uses ccache? For example here https://github.com/citra-emu/citra/blob/master/.travis/linux/docker.sh#L14

I think it does not conflict with the CI script, it may conflict with the upcoming MinGW build PR however.

**Comment by jroweboy** [comment]
"please see ___ for more details" https://i.imgur.com/r8eBQYR.png i've been lied to! :)

**Comment by liushuyu** [comment]
>"please see ___ for more details" https://i.imgur.com/r8eBQYR.png i've been lied to! :)

That's the mechanism I used in MinGW ccache invocation

**Comment by degasus** [comment]
Might anyone pick up this task/patch? I have *no* clue about cmake, so I think I'm the one developer to patch in this feature. So I'm going to close this PR soon.

**Pull request closed without merging**
