### PR TITLE
Audio fix (Appveyor)

### PR DESCRIPTION
**Pull request by acnleditor2**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3041)

### CODE REVIEW

**Comment by BreadFish64** [comment]
no

**Comment by Jhon591** [comment]
The one sdl2.dll from the MSVC dose work strangely if 1.19mb , Anyone tested be four they knock it down like a ton of bricks ?

**Comment by acnleditor2** [comment]
ready to merge

**Comment by acnleditor2** [comment]
ready to merge

**Comment by jroweboy** [comment]
This is very much a hack and will not get merged. We do not commit compiled dependencies to the main repo. If you want to fix the sound issue, investigate *why* the new version of SDL does not work, and if you can't do that then wait for someone else to fix the issue.

**Pull request closed without merging**
