### PR TITLE
Update Telemetry Links

### PR DESCRIPTION
**Pull request by N00byKing**
Disclaimer: I have no Idea whether this is useful or not

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3695)

### CODE REVIEW

**Comment by chris062689** [comment]
As a follow up PR, it may also be useful to remove all of these configuration keys and instead make a single endpoint URL that points to https://api.citra-emu.org and the actual endpoints are hardcoded? 
It just doesn't make much sense to have these all as different config items.

**Comment by wwylele** [comment]
Any response to my concern? I want to say that if we just change the default like this, and the other day we forget about old users and block the access to the old URL, we would be confused by the mystery failure, thinking that we have updated the URL.

**Comment by N00byKing** [comment]
I wouldn't know how to fix that, sorry

**Comment by jroweboy** [comment]
This is just a stop gap to the bigger problem that citra has no way to update default settings values. As such, I'm just going to close this for the time being, and when we build a better settings that supports versioning, then we can get this merged. Thanks for doing this though, really appreciate it! ❤️

**Pull request closed without merging**
