### PR TITLE
Port C++20 concept support and designated initializer changes from yuzu

### PR DESCRIPTION
**Pull request by FearlessTobi**
See https://github.com/yuzu-emu/yuzu/pull/4465, https://github.com/yuzu-emu/yuzu/pull/4471, https://github.com/yuzu-emu/yuzu/pull/4501, https://github.com/yuzu-emu/yuzu/pull/4547 and https://github.com/yuzu-emu/yuzu/pull/4477 respectively.

This needs the C++20 support PR to be merged first.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5540)

### CODE REVIEW

**Comment by B3n30** [comment]
I don't think we will enable C++20 on Citra anytime soon, since we will loose Mac support... And not sure about Android

**Comment by FearlessTobi** [comment]
As you can see, CI passes fine on the PR migrating to C++20: https://github.com/citra-emu/citra/pull/5459

**Comment by B3n30** [comment]
Maybe I should have worded my comment a bit different: None of the stl changes will work. So having C++20 enabled but can't use 80% of it's features and might be a big hassle.

**Comment by FearlessTobi** [comment]
Closing until we actually support C++20.

**Pull request closed without merging**
