### PR TITLE
Port yuzu-emu/yuzu#2473: "CMakeLists: Handle VS 2019 in a less annoying manner"

### PR DESCRIPTION
**Pull request by FearlessTobi**
See yuzu-emu/yuzu#2473 for more details.

**Original description**:
VS 2019 is binary compatible with VS 2017, so we can safely use the prebuilt libraries for VS 2017 with VS 2019 toolchains. This makes it less annoying to build yuzu with the most up to date toolchain.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4776)

### CODE REVIEW

**Comment by adityaruplaha** [comment]
If I recall correctly, you need to include certain headers, like `<complex>` in citra/citra.cpp

Might have changed though. I no longer use Windows, so can't check.

**Comment by FearlessTobi** [comment]
I'm not really sure what you mean by that?

**Comment by adityaruplaha** [comment]
I mean, VS 2019 does something strange, which makes including those headers necessary. Otherwise compilation fails.

**Comment by Mates1500** [comment]
I've downloaded VS 2019 on my PC yesterday and after fighting CMake for about 30 minutes (the delta of the proposed commit) I had no trouble compiling and running Citra without any additional changes.

**Pull request merged**
