### PR TITLE
Pica: Implement texture type 3 (Projection2D)

### LINKED ISSUE #1664: Kokuga - Graphical bugs
Nothing useful in log...

**3DS**

kokuga 2

kokuga 4

**Citra**

kokuga 1

kokuga 3

### PR DESCRIPTION
**Pull request by JayFoxRox**
Texture 0 (according to 3DBrew - maybe also other TUs?) supports [various texture types](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_TEXUNITi_PARAM).
`master` only implements a 2D texturing mode so far (type 0).

This PR implements projection (type 3) which does the lookup at (u,v)/w.
There are 2 seperate commits, one for the HW renderer and another one for the SW rasterizer.

This was not HW tested but this is what's commonly referred to as texture projection. The results also look fine in Kokuga.

This fixes #1664
(SW rasterizer still partially broken (green faded background displayed as solid green area) but it's probably due to missing texture filtering in the rasterizer [Outputting `fmodf(texcoord * texsize, 1.0)*255` makes parts of the fade visible])

(Note that GL `textureProj()` will divide by the last texcoord component and might be faster than dividing manually)

---

We probably have to refactor the rasterizer texture lookup to implement some other modes. For example: shadow lookups will probably be the same as projection lookup but the read depth value will then be compared against a fourth component (and the return value is the pixel coverage instead of a pixel color).
\- However, that is something for another PR (probably one which would also implement sw texture filtering?)

### CODE REVIEW

**Comment by JohnGodgames** [comment]
Hmm I've found a regression on Ridge Racer 3D 

rr tex type 3 1

**Comment by JayFoxRox** [comment]
The log in Ridge Racer shows that this is due to the game using a cubemap texture (probably to store reflections).

Cubemap texturing is handled by a 2D texture lookup in master (which is wrong).
This PR gives a warning (both SW/HW renderer) and also creates a buggy GLSL shader (for HW renderer) if an unsupported type (such as cubemap) is used.
As the SW renderer will only modify (u,v) that should still render as before (albeit very slow due to printf per pixel).

I knew about this before and thought not handling it at all is fine. However I realize that it might have been a bad idea. I'll probably add a fallback Texture2D lookup to the HW renderer.
We have no way of a deferred or one-shot error in the SW renderer so I probably won't change that.

**Comment by JayFoxRox** [comment]
I've updated this (fallback to 2D texturing + debug message in rasterizer) but it still has the same issues as #1621 (padding causes shader regeneration which causes high memory footprint). I have more branches with that problem so I'll also try to look for a solution because I don't like the proposals so far.

**Comment by Subv** [comment]
LGTM

**Comment by hrydgard** [comment]
This should be fine now that #1621 is merged, just needs a rebase

**Comment by JayFoxRox** [comment]
I'm waiting for #1621 to go through first because we'll need to rebase this afterwards and #1621 is more important.

**Comment by JayFoxRox** [comment]
I've rebased this, should be good to go. No idea why travis was ignored..?

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
