### PR TITLE
video_core: Add MMPX texture filter

### PR DESCRIPTION
**Pull request by stuken**
Adds texture filter implementation of MMPX https://casual-effects.com/research/McGuire2021PixelArt/
None
A-Train 3D City Simulator_23 05 23_17 05 14 449
xBRZ
A-Train 3D City Simulator_23 05 23_17 05 21 802
MMPX
A-Train 3D City Simulator_23 05 23_17 05 33 236

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6564)

### CODE REVIEW

**Comment by Steveice10** [comment]
This seems to not compile in canary:

```
[1095/1627] Generating include/video_core/host_shaders/texture_filtering/mmpx_frag_spv.h
FAILED: src/video_core/host_shaders/include/video_core/host_shaders/texture_filtering/mmpx_frag_spv.h /__w/citra-canary/citra-canary/build/src/video_core/host_shaders/include/video_core/host_shaders/texture_filtering/mmpx_frag_spv.h 
cd /__w/citra-canary/citra-canary/build/src/video_core/host_shaders && /usr/sbin/glslangValidator --target-env vulkan1.1 --glsl-version 450 --quiet -Dgl_VertexID=gl_VertexIndex --variable-name MMPX_FRAG_SPV -o /__w/citra-canary/citra-canary/build/src/video_core/host_shaders/include/video_core/host_shaders/texture_filtering/mmpx_frag_spv.h /__w/citra-canary/citra-canary/src/video_core/host_shaders/texture_filtering/mmpx.frag
ERROR: /__w/citra-canary/citra-canary/src/video_core/host_shaders/texture_filtering/mmpx.frag:18: 'sampler/image' : cannot construct this type 
ERROR: /__w/citra-canary/citra-canary/src/video_core/host_shaders/texture_filtering/mmpx.frag:18: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

**Comment by stuken** [comment]
Pushed a fix for the canary compile error. It compiles and runs fine on OpenGL. Can't verify if it actually works under vulkan though as the texture filters don't appear to be fully implmented in it yet.
I also added a small change that cleans up the missing pixels. It is slightly different than the base mmpx implementation but it handles texture alpha better that the more screenspace orientated original.

**Comment by SachinVin** [comment]
Hello , seems like compilation fails on gles, could you take a look.

```
Error compiling fragment shader:
ERROR: 0:23: 'tex' : Only consts can be used in a global initializer 
ERROR: 0:24: 'tex_coord' : Only consts can be used in a global initializer 
ERROR: 0:24: 'source_size' : Only consts can be used in a global initializer 
ERROR: 0:25: 'tex_coord' : Only consts can be used in a global initializer 
ERROR: 0:25: 'pos' : Only consts can be used in a global initializer 
ERROR: 0:25: 'source_size' : Only consts can be used in a global initializer 
ERROR: 0:29: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:33: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
ERROR: 0:33: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 9 compilation errors.  No code generated.
```

**Comment by sakuramipha** [comment]
Hi! Sorry for commenting after this has been merged, I'm not sure where else to contact you as I don't see any contact information on your profile.
I'm looking to include these images here in our upcoming progress report to showcase this awesome change you've added. However, the pictures here do include your name. 
Do I have your permission for them to be added, or would you rather I find something else to use?

Thank you for your contribution!

**Comment by stuken** [comment]
Go ahead.

**Pull request merged**
