### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Translated untranslated words/fixed several ones that were wrong or likely had their source text changed.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5773)

### CODE REVIEW

**Comment by JohelEGP** [comment]
I think you should go through this: https://github.com/citra-emu/citra#development. Particularly
> If you want to contribute to the user interface translation, please check out the [citra project on transifex](). We centralize the translation work there, and periodically upstream translations.

**Comment by B3n30** [comment]
Sorry. But That’s not the workflow to update translations. Update the translation in transiflex and it will be automatically be included in our regular updates

**Comment by Felipefpl** [comment]
Ok, thanks for the reply and sorry for submitting it here.

**Comment by Felipefpl** [comment]
It's been weeks since i requested to join transifex and nothing happened, what happened?

**Pull request closed without merging**
