### PR TITLE
More cleanups

### PR DESCRIPTION
**Pull request by yuriks**
Several misc. cleanups (mostly managing dependencies between files).

Each commit is standalone, so it's probably best to review them individually.

### CODE REVIEW

**Comment by archshift** [comment]
LGTM once you fix Travis

**Comment by yuriks** [comment]
In the process of fixing Travis I actually ended up making some major changes to it, so please re-review.

**Comment by archshift** [comment]
Still LGTM!

**Comment by linkmauve** [comment]
This is very nice!  I had a local branch aiming at the removal of common.h, but yours do a much better job at it, thanks!
LGTM.

**Comment by bunnei** [comment]
LGTM. Feel free to fix some of the indentation issues that @linkmauve pointed out, otherwise this is good to be merged...

**Pull request merged**
