### PR TITLE
Loader: Add support for loading NCCH ROMs with the .3DS extension

### PR DESCRIPTION
**Pull request by Dante38490**
Support room format .3ds files

### CODE REVIEW

**Comment by Dante38490** [comment]
@purpasmart96 It's good like that?

**Comment by archshift** [comment]
The code is correct, but know that we use 4 spaces for a tab. Just amend the commit and force push.

**Comment by Dante38490** [comment]
Oops sorry, it is fixed

**Comment by purpasmart96** [comment]
Just squash into one commit and then it will be fine.

**Comment by yuriks** [comment]
LGTM, but the commit message has a typo ;)

**Comment by Dante38490** [comment]
@yuriks Oh, what fault? ^^
I am French I see no ^^

**Comment by purpasmart96** [comment]
@Dante38490
It should like this "Add support to load .3ds files" or something like that

**Comment by Dante38490** [comment]
@purpasmart96 May be.

**Pull request merged**
