### PR TITLE
Fix dll destination set to the wrong path

### PR DESCRIPTION
**Pull request by Dragios**
Every single time when the compiler build successfully for the first time it will complain about this:
dll

This corrects the dll destination path while doing local compile with MSVC.
I have no idea why `$<CONFIG>` parameter exist in the first place.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5323)

### CODE REVIEW

**Comment by vvanelslande** [comment]
after this change, this happened
image
I have Visual Studio Build Tools 2019 16.5.4 (not preview).

**Comment by Dragios** [comment]
> 
> 
> after this change, this happened
> image
> I have Visual Studio Build Tools 2019 16.5.4 (not preview).

Are you sure about this? Location of `SDL2.dll` located after local compile? It is supposed to appear as the same directory as the executable file.

**Comment by vvanelslande** [comment]
@Dragios
```
C:\Projects\vvctre\build\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 18D9-12C9

 Directory of C:\Projects\vvctre\build\bin

02/05/2020  08:02 a. m.    <DIR>          .
02/05/2020  08:02 a. m.    <DIR>          ..
02/05/2020  08:02 a. m.    <DIR>          Release
10/03/2020  08:39 p. m.         1,471,488 SDL2.dll
               1 File(s)      1,471,488 bytes
               3 Dir(s)  135,974,428,672 bytes free

C:\Projects\vvctre\build\bin>dir Release
 Volume in drive C has no label.
 Volume Serial Number is 18D9-12C9

 Directory of C:\Projects\vvctre\build\bin\Release

02/05/2020  08:02 a. m.    <DIR>          .
02/05/2020  08:02 a. m.    <DIR>          ..
02/05/2020  08:02 a. m.        10,003,968 vvctre.exe
02/05/2020  08:02 a. m.        76,115,968 vvctre.pdb
               2 File(s)     86,119,936 bytes
               2 Dir(s)  135,974,428,672 bytes free
```

**Comment by Dragios** [comment]
So if without my change, just master branch alone, does it compile and launch the exe within MSVC?

**Comment by vvanelslande** [comment]
@Dragios master launches, doesn't launch after this change.
```
C:\Projects\citra\build\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 18D9-12C9

 Directory of C:\Projects\citra\build\bin

02/05/2020  08:36 a. m.    <DIR>          .
02/05/2020  08:36 a. m.    <DIR>          ..
02/05/2020  08:36 a. m.    <DIR>          plugins
02/05/2020  08:36 a. m.                 0 qt.conf
06/04/2018  08:01 a. m.         6,149,632 Qt5Core.dll
06/04/2018  08:07 a. m.         6,396,928 Qt5Gui.dll
06/04/2018  08:28 a. m.           781,312 Qt5Multimedia.dll
06/04/2018  08:02 a. m.         1,075,200 Qt5Network.dll
06/04/2018  08:18 a. m.           328,704 Qt5OpenGL.dll
06/04/2018  08:14 a. m.         5,604,864 Qt5Widgets.dll
02/05/2020  08:36 a. m.    <DIR>          Release
24/07/2019  11:36 p. m.         1,401,344 SDL2.dll
               8 File(s)     21,737,984 bytes
               4 Dir(s)  135,544,135,680 bytes free

C:\Projects\citra\build\bin>dir Release
 Volume in drive C has no label.
 Volume Serial Number is 18D9-12C9

 Directory of C:\Projects\citra\build\bin\Release

02/05/2020  08:36 a. m.    <DIR>          .
02/05/2020  08:36 a. m.    <DIR>          ..
02/05/2020  08:36 a. m.        15,957,504 citra-qt.exe
02/05/2020  08:36 a. m.       152,629,248 citra-qt.pdb
26/04/2020  09:26 p. m.    <DIR>          user
               2 File(s)    168,586,752 bytes
               3 Dir(s)  135,544,135,680 bytes free
```

**Comment by Dragios** [comment]
It seems like I know what is going wrong. My executable was located outside the `$<CONFIG>` parameter, hence causes the dll directory to be misplaced. Looks like *Visual Studio 2019* that have *C++ CMake tools for Windows* installed, by default creates an additional folder before `bin` via `${name}` parameter.
image

So long did not do local compile, which is why I did not realise this. I'm going to close this PR as it seems irrelevant for most users (until of course if they use the built in *CMake tool in Visual Studio*).
I might create another PR to address this issue instead.

**Pull request closed without merging**
