### PR TITLE
Band-aid solution for 'Disk Shader Cache'

### LINKED ISSUE #5204: Disk Shader Cache bug when Accurate Multiplication is disabled
For awhile now we have gotten many reports regarding crashes when users try to start their games when it has been fine before.

It appears when `Accurate Multiplication` is turned off(default setting) the `Disk Shader Cache` will always slowly load shaders from zero from `transferable` into the `precompiled` folder, ignoring what is already precompiled and keep growing and growing.

I tested on Nightly 1465 in Windows 10 on an i7-3770K using its iGPU Intel HD 4000 on the latest drivers(5129) since I saw a user had the issue with the same iGPU on these drivers so I could try replicate it.

Game tested was Tomodachi Life, at first I had `Accurate Multiplication` turned on and saw no issues with `Disk Shader Cache`. When my transfer cache grew larger than the user's(54MB) there were still no issues, the precompiled was only ~36MB while the user's had close to 1GB. The game still loaded the shaders very fast that were already in precompiled.

I went back to check their first log and saw they had `Accurate Multiplication` turned off so I did the same. This time the shaders loaded slowly from zero as if I had no precompiled cache. When it finished loading the precompiled cache grew to ~73MB, on the third load it grew to 110MB, fourth to 147MB, firth to 183MB.

On my computer it already crashed at 367MB precompiled cache with:
```
Unhandled exception at 0x00007FFE4055DB8E (ucrtbase.dll) in citra-qt.exe: Fatal program exit requested.
```
Below you can see a stack trace:
```
ucrtbase.dll!00007ffe4055db8e()
ucrtbase.dll!00007ffe4055d2cf()
vcruntime140.dll!00007ffe2d832e06()
vcruntime140.dll!00007ffe2d833dac()
vcruntime140.dll!00007ffe2d83ed01()
ntdll.dll!00007ffe4320121f()
ntdll.dll!00007ffe431ca289()
ntdll.dll!00007ffe431ffe8e()
KernelBase.dll!00007ffe4077a859()
vcruntime140.dll!00007ffe2d8361e0()
citra-qt.exe!boost::container::throw_bad_alloc() Line 107
	at C:\Programming\citra\externals\boost\boost\container\throw_exception.hpp(107)
[External Code]
[Inline Frame] citra-qt.exe!std::_Default_allocate_traits::_Allocate(const unsigned __int64) Line 51
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory(51)
[Inline Frame] citra-qt.exe!std::_Allocate_manually_vector_aligned(const unsigned __int64) Line 94
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory(94)
[Inline Frame] citra-qt.exe!std::_Allocate(const unsigned __int64) Line 175
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory(175)
[Inline Frame] citra-qt.exe!std::allocator<unsigned char>::allocate(const unsigned __int64) Line 784
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xmemory(784)
[Inline Frame] citra-qt.exe!std::vector<unsigned char,std::allocator<unsigned char>>::_Buy_raw(const unsigned __int64) Line 1642
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vector(1642)
[Inline Frame] citra-qt.exe!std::vector<unsigned char,std::allocator<unsigned char>>::_Buy_nonzero(const unsigned __int64) Line 1663
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vector(1663)
[Inline Frame] citra-qt.exe!std::vector<unsigned char,std::allocator<unsigned char>>::_Construct_n_copies_of_ty(const unsigned __int64) Line 459
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vector(459)
[Inline Frame] citra-qt.exe!std::vector<unsigned char,std::allocator<unsigned char>>::{ctor}(const unsigned __int64) Line 471
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vector(471)
citra-qt.exe!Common::Compression::CompressDataZSTD(const unsigned char * source, unsigned __int64 source_size, int compression_level) Line 17
	at C:\Programming\citra\src\common\zstd_compression.cpp(17)
citra-qt.exe!Common::Compression::CompressDataZSTDDefault(const unsigned char * source, unsigned __int64 source_size) Line 33
	at C:\Programming\citra\src\common\zstd_compression.cpp(33)
citra-qt.exe!OpenGL::ShaderDiskCache::SaveVirtualPrecompiledFile() Line 424
	at C:\Programming\citra\src\video_core\renderer_opengl\gl_shader_disk_cache.cpp(424)
citra-qt.exe!OpenGL::ShaderProgramManager::LoadDiskCache(const std::atomic<bool> & stop_loading, const std::function<void __cdecl(enum VideoCore::LoadCallbackStage,unsigned __int64,unsigned __int64)> & callback) Line 619
	at C:\Programming\citra\src\video_core\renderer_opengl\gl_shader_manager.cpp(619)
citra-qt.exe!EmuThread::run() Line 51
	at C:\Programming\citra\src\citra_qt\bootmanager.cpp(51)
[External Code]
```

log file: [citra_log.zip](https://github.com/citra-emu/citra/files/4469494/citra_log.zip)

#5188 is an attempt to workaround the problem by disabling `Disk Shader Cache` until we could figure out what is wrong but now that we know we should be able to work on a solution.

### PR DESCRIPTION
**Pull request by tywald**
#4923 added a nice feature, however many users are experiencing crashes when they try to start a game with it turned on and are making many topics on the forums about it or seek for help on Discord almost daily. The fix has been to tell users to turn it off. We should disable it by default for now until its bugs have been ironed out.

Edit*
PR changed to instead enable `Accurate Multiplication` by default and to prevent `Disk Shader Cache` to be enabled if `Accurate Multiplication` is disabled. This is a band-aid solution to fix #5204 
Suggestion by @B3n30 

Edit 2020-10-10*
It was agreed on Discord that we move `Disk Shader Cache` to the `Advanced` tab in order to for the UI to show feedback to the user the relationship that `Disk Shader Cache` has with `Enable Hardware Shader` and `Accurate Multiplication`

UI changes:
image
image
image
image
image

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5188)

### CODE REVIEW

**Comment by B3n30** [comment]
is there an issue created for those crashes? Are logs available for this? stacktraces?

**Comment by tywald** [comment]
Logs can be found from various topics, they all pretty much have the log cut off. Examples: 
<https://community.citra-emu.org/t/animal-crossing-makes-citra-instant-exit/201871/3>: <https://community.citra-emu.org/uploads/short-url/7B43QOoCpEmLC4XvlQVvgts9ucA.txt>

<https://community.citra-emu.org/t/citra-crash-when-loading-pokemon-x/205706/3>: <https://community.citra-emu.org/uploads/short-url/qpHOWTmT0mPp5EhaupFsDB4N08Q.txt>

<https://community.citra-emu.org/t/citra-crashes-pc-during-the-black-loading-screen/209050/3>: <https://community.citra-emu.org/uploads/short-url/jYLLIyRIBSaOWzfRTBQyobmKiTO.txt>

I don't believe there is an issue open yet. I can try to reproduce it on my end with my iGPU as someone else with Intel HD 4000 had the issue to try get a stack trace.

**Comment by B3n30** [comment]
I agree we should set it off on default for now. I just want to have as much as documentation about it as possible before we merge this

**Comment by jroweboy** [comment]
> no one seems eager to fix it.

I'm the one who wrote the code and I've tried several times to replicate any of the issues. No luck. Its not a lack of interest, its a lack of reproducibility from the only interested party

**Comment by tywald** [comment]
I'm in the process to try replicate these crashes on my iGPU(Intel HD 4000), but it will take awhile since it looks like I will need to play a lot of like Pokémon :P

If I'm able to I will open a new issue with stack trace and an estimation how many shaders need to be cached for this to happen. Right now ~650 is not enough to trigger it.

**Comment by M220** [comment]
I'm curious, can it be something not straight citra related? Like an aggressive Anti-virus Real-time scanner finding out that the cache files are going to be used, so it starts to scan them and takes it's time, meanwhile Citra expects to have the files ready instantly but it doesn't get to access the files while the Antivirus is scanning to make sure it's not a virus, so it tries infinitely to access the same file with no result and thus crash ( or even maybe a desync happens because of that )? I haven't dived into it, but if it's happening on different hardwares and some people can reproduce it and some can't, maybe that's the reason 🤷‍♂️

**Comment by B3n30** [comment]
I wonder if we should change this to have accurate multiplication always enabled when shader disk cache is enabled, and force shader disk cache disabled if accurate multiplication gets disabled?

**Comment by tywald** [comment]
Hm, probably is a good band-aid solution.

**Comment by zhaowenlan1779** [comment]
I feel the UX isn't the most friendly here right now, should probably update the checkbox enable states when Accurate Multiplication is toggled (i.e. uncheck and disable shader cache when accurate mul is turned off, enable when accurate mul is turned on)

**Comment by tywald** [comment]
@jroweboy had some issues in #5072 where it was "wonky" due to the settings being in different tabs. If I try to mimic what's done for preload custom textures it will simply say: `class "Ui::ConfigureEnhancements" has no member "toggle_accurate_mul"`. Trying to include the header files doesn't work.

**Comment by zhaowenlan1779** [comment]
Ah well, I didn't think of that. If these two options have dependency relations, I would say they *must* be on the same tab.
I'm not sure whether we should move accurate mul to enhancements or shader cache to advanced, though.

**Comment by Schplee** [comment]
Merging as there have been no reports of issues in Canary, and no developers have disagreed / added additional comments.

**Pull request merged**
