### PR TITLE
Pica/VertexShader: Implement JMPC/JMPU/CALLC/CALLU.

### PR DESCRIPTION
**Pull request by archshift**
@neobrain's code from his pica_progress3 branch.

### CODE REVIEW

**Comment by neobrain** [comment]
LGTM

**Comment by purpasmart96** [comment]
Does this compile on windows? Or did you already fix those issues?

**Comment by archshift** [comment]
Yep, we now have a CI service called AppVeyor enabled which builds on Windows.

**Comment by purpasmart96** [comment]
Oh ok, that's nice. LGTM

**Comment by neobrain** [comment]
GitHub is giving me a hard time following the commit order... did you first update nihstro and then cherry-pick, or did you do it the other way around? Either way, both commits can just be squashed together.

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
