### PR TITLE
core: fix removed AddTicks

### PR DESCRIPTION
**Pull request by wwylele**
Another regression from #2343 (4fc8b82, issue #2371). The `AddTicks(4000);` hack didn't get moved to the new function. Plus the old `hle.cpp` wasn't removed (it even get edited in the next commit...).

### CODE REVIEW

**Comment by Dragios** [comment]
Although this fix speed up game but I encounter a problem with a game.
*Nano Assault EX* will occasionally stuck at black screen upon starting the game mode with the `AddTicks(4000);` hack.

Although a restart will be able to bypass it at certain time and will play a very short video after that.
Left side shows the black screen freezes while right side shows that it managed to load properly

Nano Assault EX
I have to slow down the FPS to 10 in order to screenshot "loading" as it disappear too quick.

**Comment by wwylele** [comment]
@Dragios before I look into it, I want to make sure that this issue didn't happen before#2343, right?

**Comment by Dragios** [comment]
Actually it is the opposite. It happens before #2343 is merged. After #2343 is merged it does not happen.

**Comment by wwylele** [comment]
@Dragios then filing a new issue after this is merged. #2343 didn't mean to change the behaviour (= fix anything). This PR is mean to restore the old behaviour that is changed by mistake.

**Comment by Dragios** [comment]
Will do.

**Comment by bunnei** [comment]
Sorry, but this wasn't a "regression" ... It was intentionally removed. I'm not sure this does anything useful anymore. It was added at the time (as a hack) because it seemed to fix hangs in several games. That does not seem to be the case anymore. This is effectively just resulting in a vsync happening more frequently in areas of games that aren't GPU bound .. effectively the same as underclocking the CPU, but even more hacky IMO.

**Pull request closed without merging**
