### PR TITLE
gl_rasterizer: HP Bar Fix for some games

### LINKED ISSUE #5139: (Puzzle & dragons Z - Super Mario Edition) - Grey health bars on ennemies
issueGreyBar

Citra Nightly 1444 (also tested on Canary 1607 FYI)
i5-7300HQ
GeForce GTX 1050
8Go RAM
[citra_log.txt](https://github.com/citra-emu/citra/files/4371623/citra_log.txt)

Ennemies health bar stay completely grey instead of a green bar decreasing as they take damage. Found out that issue is resolved when Hardware Renderer isn't enabled, but it makes the game unplayable as it then runs at like 2FPS.

### PR DESCRIPTION
**Pull request by Polar-Zero**
give ability to gl_rasterizer to trying control 4x4 (or 8x4) texture (without usage of mipmap)
BEFORE they throwing error

Can fix #5139 #5563 (or more) and related log spam "Texture size (8x4) is not multiple of 8"
in [Metal Max 4] or [Puzzle & Dragons Super Mario Bros Edition]

but the code can affect other game negatively, so if code has error, please notify me

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6334)

### CODE REVIEW

**Comment by vitor-k** [comment]
For more context on this you can refer to [this comment](https://github.com/citra-emu/citra/issues/5139#issuecomment-747208091), but basically this seems to re-add the code that was removed with the reason of:
> The original code that deals with texture with unaligned size is removed because PICA simply doesn't support this.
The code itself _probably_ shouldn't break any games, but ideally we should get some hardware testing or someone with experience RE-ing the PICA to weight in.

**Comment by Polar-Zero** [comment]
I just think
processing unaligned memory is better then 1kb+ log spam & graphic issues
that is because of submit push reports.

but if i can found better way to progress hp bar, I will submit later :)

**Comment by Polar-Zero** [comment]
Oops
I will reopen this PR but can freely close if had problems

**Comment by wwylele** [comment]
Given this kind of weird texture size is not well-tested on hardware, let's add a TODO comment in the code that this implementation might not be accurate and needs further testing

**Comment by Polar-Zero** [comment]
> Given this kind of weird texture size is not well-tested on hardware, let's add a TODO comment in the code that this implementation might not be accurate and needs further testing

Great idea :) and I also fix this code only work to less then 8x8 texture size

**Pull request merged**
