### PR TITLE
kernel: Partially emulate svcArbitrateAddress timing

### PR DESCRIPTION
**Pull request by GPUCode**
This fixes slow FMV performance in my testing. When playing these FMVs, Capcom games appear to busy loop calling svcArbitrateAddress with ArbitrationType::Signal. This causes large slowdowns as SVCs, except svcGetSystemTicks, consume only 8 cycles resuling in dozens of iterations. This is also why more accurate cycle counting helped improve the performance. So in a similar fashion to https://github.com/citra-emu/citra/pull/1072 we can emulate the instruction timing of the call to boost the performance further.

Measurement of the cycles was done on a n3DS running firmware 11.17. The homebrew creates a few threads on core 2. This is done so the timer of the appcore is not influnced by instructions executed in those threads as svcArbitrateAddress will cause a reschedule. 10 timing tests are performed at a time and the average is calculated at the end.

The tests show that the SVC (called with ArbitrationType::Signal) has a base overhead of 2600-3000 cycles and an additional overhead of 200 cycles per thread woken up. This makes sense to me as the kernel spends some additional time looping each thread in the linked list. If anyone can spot inaccuracies or mistakes in the mesurement process, feel free to point them out.

In the future it would be nice to create a timing framework for SVC so we don't have to call AddTicks manually for each one.

Fixes
https://github.com/citra-emu/citra/issues/6550

[thread-basic.zip](https://github.com/citra-emu/citra/files/12619455/thread-basic.zip)

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6977)

### CODE REVIEW

**Comment by tywald** [comment]
Greatly speeds up Monster Hunter 3 Ultimate, Super Street Fighter IV and Zero Escape: Virtue's Last Reward(this one went from 16ms down to <4ms on my machine) FMVs.

**Comment by Dragios** [comment]
This PR renders all _Japanese Rail Sim_ games unplayable by preventing them from launching. I've personally tested the following titles:

- _Japanese Rail Sim: Journey to Kyoto_
- _Japanese Rail Sim: Monorail Trip to Okinawa_
- _Japanese Rail Sim: Rail Sim in Suburbs # 1_

**Comment by GPUCode** [comment]
Hm will need to investigate why these games are so timing sensitive

**Comment by Dragios** [comment]
I'm not sure if these last few log lines is any useful for diagnostic but I provide it anyway:
```C++
Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:719: (STUBBED) called, must_be_one=1, value=30
Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:2318: unimplemented SVC function GetThreadIdealProcessor(..)
Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:698: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
Service.APT <Warning> core/hle/service/apt/apt.cpp:GetAppCpuTimeLimit:734: (STUBBED) called, must_be_one=1
Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:2318: unimplemented SVC function GetThreadIdealProcessor(..)
```
These log entries also appear in Nightly version but the game is bootable.
```C++
Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:719: (STUBBED) called, must_be_one=1, value=30
Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:2315: unimplemented SVC function GetThreadIdealProcessor(..)
Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:698: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
Service.APT <Warning> core/hle/service/apt/apt.cpp:GetAppCpuTimeLimit:734: (STUBBED) called, must_be_one=1
Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:2315: unimplemented SVC function GetThreadIdealProcessor(..)
```
Continuation of log entries when it reached the main menu:
```C++
Kernel.SVC <Error> core/hle/kernel/svc.cpp:CallSVC:2315: unimplemented SVC function GetThreadIdealProcessor(..)
Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default
Service.MIC <Warning> core/hle/service/mic/mic_u.cpp:SetClientVersion:354: (STUBBED) called, version: 0x0B0100C8
Kernel.SVC <Warning> core/hle/kernel/svc.cpp:CreateMemoryBlock:1675: called addr=0x0029B000
Audio <Error> audio_core/cubeb_input.cpp:StartSampling:57: Application requested unsupported unsigned pcm format. Falling back to signed.
Audio <Critical> audio_core/cubeb_input.cpp:StartSampling:97: Error creating cubeb input stream.
```

**Comment by SachinVin** [comment]
How log does it generally take to run the test? 
10 runs doesn't feel like a lot to arrive at an average

**Comment by GPUCode** [comment]
Each test is measuring the cycles arbitrateaddress call takes. After each measurement there is a 100ms sleep to ensure all the threads have re-entered the waiting state and they are signaled again for 10 times. So in total each round of tests takes < 3 seconds

**Comment by GPUCode** [comment]
Seems that always adding 2000 ticks to ArbitrateAddress fixes the Japanese Rail Sim games on New 3DS mode. Will need to decompile the game though to be sure on why that is

**Pull request closed without merging**
