### PR TITLE
Support mingw cross-compilation

### PR DESCRIPTION
**Pull request by JayFoxRox**
This involves 3 kind of changes:

- Lowercase spelling for includes (`Windows.h` and `WinSock2.h`)
- Use of gcc intrinsics (Old check was for `_WIN32`, not the compiler)
- Use of forward slashes as path seperator (present in *.rc files, used for exe icon path)

Additionally I decided to update the icon name in the rc files.
One was kind of arbritrary, the other one referenced GLFW which we aren't even using anymore.

---

This currently does not pack SDL2 or Qt5 dependencies properly (which is done conditionally for MSVC builds). I intend to do this in a follow-up PR as we still have various Qt version checks which I'd like to remove anyway (as chances are very slim we'll ever support Qt4 or below again).
It's also not a cross-compile issue, but rather a lack in the original mingw support.

### CODE REVIEW

**Comment by MerryMage** [comment]
LGTM

**Comment by MerryMage** [comment]
Due to f120e78, clang-format complains about header ordering.

Suggestion is to do something akin to this: https://github.com/citra-emu/citra/blob/f120e78b5692e1c710f2335d36fd0593c447a613/src/common/file_util.cpp#L13

**Comment by lioncash** [comment]
You can just do

```cpp
// clang-format off
#include <windows.h>
// clang-format on
```

**Comment by yuriks** [comment]
Adding a comment between blocks of includes already instructs clang-format that it shouldn't reorder includes across that comment, so I think it's not necessary to fully disable it.

**Comment by JayFoxRox** [comment]
I've done what merry suggested and based my reasoning on http://www.cplusplus.com/forum/windows/112014/ and http://stackoverflow.com/questions/5971332/redefinition-errors-in-winsock2-h .

I've also noticed that there was a `common/abi/` include specifically for windows and decided to remove it. It still compiles fine for me in mingw. I believe this was a copy/paste error or leftover?

**Comment by linkmauve** [comment]
LGTM.

**Pull request merged**
