### PR TITLE
Fixes Mali perf in open GL (tested)

### PR DESCRIPTION
**Pull request by Ishan09811**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7365)

### CODE REVIEW

**Comment by GPUCode** [comment]
If you tested it, can you provide a screenshot of the performance improvement?

**Comment by Ishan09811** [comment]
> If you tested it, can you provide a screenshot of the performance improvement?

Yes I tested it and it's really improve some performance and stability in Mali devices

**Comment by GPUCode** [comment]
Please a take some comparison screenshots then

**Comment by Ishan09811** [comment]
> Please take some comparison screenshots then to make sure

You can re compile it because I fixed the compile error recently and I will also provide you the comparison

**Comment by Ishan09811** [comment]
> Please take some comparison screenshots then to make sure

when I test canary letest build but it's causes instant crashes if I use the open GL ES but when I use my pr build then it's running fine and better than Vulkan in my Mali device.
tested game : Pokemon X

**Comment by SleepingSnakezzz** [comment]
I cannot reproduce the crash you've spoken of with my Mali device. Can you retest? If the issue persists, please upload a log file.

**Comment by GPUCode** [comment]
I'm waiting to the requested screenshot. The improvement seems nice but citra already takes measures to respect the maximum texel buffer size so I'm hesitant to believe it unless proven otherwise

**Comment by GPUCode** [comment]
Does it crash with Nightly as well?

**Comment by Ishan09811** [comment]
> Does it crash with Nightly as well?

@GPUCode 
I didn't test Citra nightly but when I use the Citra canary build then it's crashing in Open GL but didn't crash in Vulkan and low performance.

**Comment by Ishan09811** [comment]
> Does it crash with Nightly as well? If yes, then send a log file like snake said

@GPUCode 
So What's your decision ?

**Comment by GPUCode** [comment]
I don't have a mali device on hand, otherwise I would have tested this myself. Can you install the latest nightly and compare between this build and that? If there is a notable difference then this would seem reasonable, but the magic numbers might need to replaced with something more readable

**Comment by SleepingSnakezzz** [comment]
Can confirm around a 50% performance improvement vs latest Canary. 
Canary: 100-140%
PR: 180-200%
However, we need to figure out why exactly this is happening before these changes can be merged. Since, as far as we knew, we already had a more proper way to address this implemented.

**Comment by Ishan09811** [comment]
> I don't have a mali device on hand, otherwise I would have tested this myself. Can you install the latest nightly and compare between this build and that? If there is a notable difference then this would seem reasonable, but the magic numbers might need to replaced with something more readable

@GPUCode 
but @SleepingSnakezzz already confirmed that the changes are really improved the performance in mali devices.

**Comment by Ishan09811** [comment]
> I don't have a mali device on hand, otherwise I would have tested this myself. Can you install the latest nightly and compare between this build and that? If there is a notable difference then this would seem reasonable, but the magic numbers might need to replaced with something more readable

@GPUCode 
which magic numbers ?

**Comment by GPUCode** [comment]
This PR proposes we hardcode the texture buffer size to 11264 for all Mali GPUs. _Why_ was this number chosen however? Also applying it for all Mali gpus, even the newer chips is probably not a good idea. I suspect this only has an effect on chips with the minimum texture buffer size limit. Something to try, does the existing size divided by 2 provide similar performance benefit?

**Comment by Ishan09811** [comment]
> Can confirm around a 50% performance improvement vs latest Canary with my Mali device. Canary: 100-140% PR: 180-200% However, we need to figure out why exactly this is happening before these changes can be merged. Since, as far as we knew, we already had a more proper way to address this implemented.

@SleepingSnakezzz 
If the GPU is Mali, the textures are allocated with fixed sizes (11264 and 525312, respectively), otherwise, they are allocated with the value of texture_buffer_size so the sizes are specially for mali to increase the performance and it actually increases performance.

**Comment by GPUCode** [comment]
Given this increases performance I'm fine with merging it, but you will also need to check that GL_MAX_TEXTURE_BUFFER_SIZE is 65536 so it gets only applied for these older gpus

**Comment by Ishan09811** [comment]
> Given this increases performance I'm fine with merging it, but you will also need to check that GL_MAX_TEXTURE_BUFFER_SIZE is 65536 so it gets only applied for these older gpus

@GPUCode 
You are sure it will cause any issues with newer Mali GPUs.

**Comment by GPUCode** [comment]
Newer mali gpus have a higher texture buffer size limit so I don't think this workaround matters for them

**Comment by Ishan09811** [comment]
> Newer mali gpus have a much higher texture buffer size limit so I don't think this workaround matters for them.

@GPUCode 
so i will add a check but for which one or both ?

**Comment by GPUCode** [comment]
Don't check against the macro itself, but query it from opengl like the above TextureBufferSize function. I'd also suggest you move all this logic inside that function to make it more clear

**Comment by GPUCode** [comment]
I would suggest the following instead
```
constexpr std::size_t MIN_TEXTURE_BUFFER_SIZE = 65536;

[[nodiscard]] GLsizeiptr TextureBufferSize(Vendor vendor) {
    GLint max_texel_buffer_size;
    glGetIntegerv(GL_MAX_TEXTURE_BUFFER_SIZE, &max_texel_buffer_size);
    // Old Mali GPUs that report the minimum texture buffer size mandated by the standard
    // experience slowdown when approaching said limit, use a smaller size for these buffers.
    if (vendor == Vendor::ARM && max_texel_buffer_size == MIN_TEXTURE_BUFFER_SIZE) {
        return 16_KiB;
    }
    return std::min<GLsizeiptr>(max_texel_buffer_size * 8ULL, TEXTURE_BUFFER_SIZE);
}
```
This makes it clear we are adding a mali workaround and gives an explanation of the reasoning for it. Also I've hardcoded both buffers to 16KiB which is a power of 2 very close to the number this PR proposes (please test if the performance is the same).

**Comment by Ishan09811** [comment]
@GPUCode 
I used the existing ``IsVendorMali`` instead of 
``vendor == Vendor::ARM`` and it's compiled successfully so now I need to test it

**Comment by Ishan09811** [comment]
@GPUCode 
no the your alternative idea causes instant crashes like the canary builds while using the open GL ES but the Vulkan is running fine

**Comment by GPUCode** [comment]
Can you send a debug renderer log file for the crashes? We are only changing the size of the buffer here (and in fact this is less than the unofficial build you have sourced this from). So I'm not sure why it would be crashing

**Comment by Ishan09811** [comment]
@GPUCode 
I added your alternative method which the function returns a smaller buffer size of 16 KiB (16 * 1024) as you said but it's causes instant crashes like the canary builds.

**Comment by FearlessTobi** [comment]
How did you even get your magic numbers in the first place? Random guessing?

**Comment by Ishan09811** [comment]
@FearlessTobi 
what??? magic number means ? 😶

**Comment by LoSmarrito** [comment]
> @FearlessTobi what??? magic number means ? 😶
@Ishan09811 : They're asking you how you knew those number were the good ones. Have you read them in some documentation? Has anyone suggested you? Have you casually tried numbers until you got a good result?

**Comment by Ishan09811** [comment]
@LoSmarrito 
Just I see in a fork so i tried to implement it on Citra official and it's really implemented successfully and also fixes the performance in Mali devices.

**Comment by LoSmarrito** [comment]
> @LoSmarrito Just I see in a fork so i tried to implement it on Citra official and it's really implemented successfully and also fixes the performance in Mali devices.

@Ishan09811 Ok, thank you for the answer.

**Comment by FearlessTobi** [comment]
This has been sitting stale for a while and some questions like why these numbers have been chosen have still not been answered.

Since this change could potentially break rendering, I'd rather leave this to a maintainer who can document it better and take responsibility if something breaks.

Thanks for your understanding

**Pull request closed without merging**
