### PR TITLE
Multiplayer version 4

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
This is a mega PR for the 4th multiplayer version. When the sub-PRs are reviewed, they should be force pushed to here. (Maintainers can push to my branch)

Current plans (All Done!):

Features:
- [X] ~~**(Done #4378)** Web services authentication~~
- [X] ~~**(Done #4379)** #3677~~
- [X] ~~**(Done #4466)** Basic moderation~~
- [X] ~~**(Done #4393)** #3721~~
- [X] ~~(Deferred after discussion) #3681~~
- [X] ~~**(Done #4390)** Protect multiple users with the same Console ID from connecting to the same room~~
- [X] ~~**(Done #4394)** #4177 server side validation~~
- [X] ~~**(Done #4417)** "XXX Joined" and "XXX Left" status message like IRC~~
- [X] ~~**(Done #4477)** User pings while chatting~~

Bug fixes:
- [X] ~~**(Done #4407)** "Connected" message does not appear on first connection to a room~~

... and more (request for comments)

Before merging:
- [x] #4507 
- [x] #4516 
- [x] Test this out with the mods
- [x] Change the lobby endpoint to `/lobby`
- [ ] @chris062689: 1. Switch `/lobby2` to `/lobby` api side; 2. Push an update to citra-emu/citra-multiplayer-dedicated

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4468)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Reminder to self: when there's no description/player username, should not pass `description` and `username` as empty string (would return 400), but instead do not pass them at all

**Comment by wwylele** [comment]
@valentinvanelslande 
Before @zhaowenlan1779 replies I have to say this first: no, I won't accept a PR adding image support. We are not building a discord.

**Comment by zhaowenlan1779** [comment]
as @wwylele said, I'm not going to do thaf.

**Comment by edoaxyz** [comment]
Is it possible to add UI sounds triggered whenever an user pings you or an user enters your same room? Obviously these must be selectable in options with enabled ping as default (I think).

**Comment by zhaowenlan1779** [comment]
@edoaxyz Did not look into that, but we can add that later if we decided we need it, as it is a frontend change that is unrelated to the multiplayer protocol anyway.

**Pull request merged**
