### PR TITLE
UDS: Added a hook for updating the connection status when a client connects to the network.

### PR DESCRIPTION
**Pull request by Subv**
This hook will be called by whoever creates the AssociationResponse frame, which contains the assigned network node id.

So far AssociationResponse is intended to be created inside NWM itself, as a response to an AssociationRequest frame.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2779)

### CODE REVIEW

**Comment by B3n30** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 554 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2779#-KmaMhamSY1sG7BBvmTg:-KmaMhanu38z-jMJuHoA:bsl8eho) ([raw file](https://github.com/citra-emu/citra/blob/036b4e216a0b414f1600136d41146b596a933d0d/src/core/hle/service/nwm/nwm_uds.cpp#L554)):*
> ```cpp
>                "Can not accept clients if we're not hosting a network");
> 
>     for (unsigned index = 0; index < UDSMaxNodes; ++index) {
> ```

nit: Loop should only go up to connection_status. max_nodes which is also catched in OnClientConnected. Besides that :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2779)*

**Comment by Lord-Haji** [comment]
*[src/core/hle/service/nwm/nwm_uds.cpp, line 554 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2779#-KmaMhamSY1sG7BBvmTg:-KmaeScuiM4nl1eqFjdd:b-l4jpsd) ([raw file](https://github.com/citra-emu/citra/blob/036b4e216a0b414f1600136d41146b596a933d0d/src/core/hle/service/nwm/nwm_uds.cpp#L554)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

nit: Loop should only go up to connection_status. max_nodes which is also catched in OnClientConnected. Besides that :lgtm:
</blockquote></details>

right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2779)*

**Comment by Subv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 554 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2779#-KmaMhamSY1sG7BBvmTg:-Kmb17A5vEk1VONK-pry:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/036b4e216a0b414f1600136d41146b596a933d0d/src/core/hle/service/nwm/nwm_uds.cpp#L554)):*
<details><summary><i>Previously, Lord-Haji (Haji Sama) wrote…</i></summary><blockquote>

right
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2779)*

**Comment by B3n30** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2779#-:-Kmc-yoZmcl-I2_DaW40:bnfp4nl)*

**Comment by wwylele** [comment]
These functions should be `static` (or at least for `GetNextAvailableNodeId`)? otherwise LGTM

Question (no need to change the code): will this be called by another thread, meaning we need to take care of synchronization?

**Pull request merged**
