### PR TITLE
Create string.xml for values-ru

### PR DESCRIPTION
**Pull request by 6lackmag3**
Adding Russian translation

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7022)

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Thanks a lot for your contribution!
Our translation is managed on [Transifex](https://app.transifex.com/citra/citra/android/).
Please sign up and add your translations there.

**Comment by 6lackmag3** [comment]
@FearlessTobi ok, I've added translation on Transifex. Unfortunately, source file looks outdated with many strings missing.

**Comment by FearlessTobi** [comment]
@6lackmag3 Thanks for making me aware of this. All the strings should be on Transifex now :)

**Comment by 6lackmag3** [comment]
@FearlessTobi  Sorry for pinging you. I've finished working on translation some time ago. Currently, it's 100% on Transifex but hasn't been merged yet. I've tried to reach out someone on Citra Discord but got no replies in #translation. Can you help please?

**Pull request closed without merging**
