### PR TITLE
codec: Fix ADPCM distortion caused by incorrect nibble order

### LINKED ISSUE #2049: ADPCM decoding distortion caused by incorrect nibble order
Compare:

- https://github.com/citra-emu/citra/blob/master/src/audio_core/codec.cpp#L61
- https://github.com/kode54/vgmstream/blob/master/src/coding/ngc_dsp_decoder.c#L28

After correcting the order in which the two nibbles are decoded, ADPCM decoding distortion was noted to have been eliminated.

```diff
@@ -56,15 +56,15 @@ StereoBuffer16 DecodeADPCM(const u8* const data, const size_t sample_count, cons
         };
 
         size_t outputi = framei * SAMPLES_PER_FRAME;
         size_t datai = framei * FRAME_LEN + 1;
         for (size_t i = 0; i < SAMPLES_PER_FRAME && outputi < sample_count; i += 2) {
-            const s16 sample1 = decode_sample(SIGNED_NIBBLES[data[datai] & 0xF]);
+            const s16 sample1 = decode_sample(SIGNED_NIBBLES[data[datai] >> 4]);
             ret[outputi].fill(sample1);
             outputi++;
 
-            const s16 sample2 = decode_sample(SIGNED_NIBBLES[data[datai] >> 4]);
+            const s16 sample2 = decode_sample(SIGNED_NIBBLES[data[datai] & 0xF]);
             ret[outputi].fill(sample2);
             outputi++;
 
             datai++;
         }
```

### PR DESCRIPTION
**Pull request by MerryMage**
Closes #2049.

### CODE REVIEW

**Comment by yuriks** [comment]
LGTM

**Comment by Dragios** [comment]
Somehow the one I downloaded on citra-emu.org has no audio output after this is merged.
But the one I compiled myself has audio output. This is strange.
Could you guys have a look?

**Comment by JayFoxRox** [comment]
Maybe you are using different configs? (One with enabled, the other with disabled audio?)
Unless something went bad during compilation (highly unlikely) it can't possibly affect it this way.

**Comment by Dragios** [comment]
I have not changed any config after unzipping the files. I have it unzipped to an empty folder. Besides I even triple checked to make sure the audio is enabled in the settings.

**Comment by Dragios** [comment]
Issue solved. Please remove the irrelevant comments.

**Pull request merged**
