### PR TITLE
Cro

### PR DESCRIPTION
**Pull request by roxoa**

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-01-29T21:48:35Z: https://github.com/citra-emu/citra/compare/3ab6d77c206c33e5036fcde1de0663c2f72777ea...Subv:943ce6f6f5c220edc1b7f9a47a10412410eb43ae

**Comment by yuriks** [comment]
No.

**Comment by WinPack** [comment]
@yuriks Why didn't this get merged?

**Comment by neobrain** [comment]
@WinPack Why should it have been merged?

**Comment by WinPack** [comment]
@neobrain Well, what I meant to ask is why @yuriks said "no" and closed the PR without reason or anything. Of course I don't know if this has been discussed on IRC, since I wasn't and am not a member, but please enlighten me as to why a "no" was posted along with closing this PR.

**Comment by wwylele** [comment]
@WinPack PR's author and commits' author are even not the same person. It is obvious that CRO was WIP and Subv didn't want to PR it, but another one just couldn't wait and opened this PR.

**Comment by MerryMage** [comment]
Locking conversation since this isn't even a valid PR.

**Pull request closed without merging**
