### PR TITLE
[WIP] fastmem

### PR DESCRIPTION
**Pull request by MerryMage**
OS status:
* Windows TBD - currently unsupported
* macOS tested and working
* Linux partially tested

fastmem:
* We remove `Special` regions since they're currently unused except for tests.
* We currently only fastmem fcram, vram, n3ds_extra_ram - other memory types TBD.
* We currently don't deallocate memory regions so we're leaking 4 GiB of virtual address space per emulated process.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4750)

### CODE REVIEW

**Comment by MerryMage** [comment]
Just realized we can temporarily `VirtualProtect` host virtual memory addresses with 4KiB granularity, which saves having to map/unmap file sections at 64KiB granularity.

**Comment by Patrykq** [comment]
Hmmm, interesting. Looking forward to the Windows support.

**Comment by B3n30** [comment]
please resolve conflict? Can this move from WIP to a proper PR?

**Comment by Subv** [comment]
I'm closing this one in favor of #5206

**Pull request closed without merging**
