### PR TITLE
citra_qt/configuration: make bg color only configurable when game is not running

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
follow up of #4047 (@jroweboy merged it without letting me address the problem)

There's no visual difference if I just make the push button disabled, so I added another button called "Change". Slightly revised the look of the color display button too. The original button still has the functionality to change the color when clicked.
image

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4050)

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Tbh it would be a better UX if changing the bg while the game is running would be possible. Is it so hard to implement?

**Comment by jroweboy** [comment]
thats what i was going to suggest. just add another atomic to video_core
with the bg_color tuple and let it change while running if you want

**Comment by zhaowenlan1779** [comment]
@jroweboy let me have a look.. not sure if I can do it though.

**Comment by zhaowenlan1779** [comment]
@jroweboy seems like I found out how to do it..

**Pull request closed without merging**
