### PR TITLE
Fragment lighting: implement geometric factor

### PR DESCRIPTION
**Pull request by wwylele**
Reference formula on 3dbrew: http://mathb.in/64694. G0 and G1 are geometric factors

The test result shows that the formula for geometric factors in 3DS is not [the standard Cook-Torrance one](http://ruh.li/images/CookTorranceGeometricAttenuation.png). To get the correct formula, [a testing program](https://github.com/wwylele/ctrhwtest/tree/master/geo_factor) is used. Some assumptions are made when finding the formula:
 - the formula on 3dbrew is correct
 - G only depends on normalized vector N (normal), V (view) and L (light), and can contain half-angle vector H (still depends on V and L)
 - spherical symmetry, as in, rotating N, V and L by the same angle won't change G value 

Based on these assumptions, G value is sampled for different combinations of N, V and L (with two-sided-diffuse on). Because of the symmetry, V and L is confined on the xy plane and are symmetrical about x-axis (so that the potentially used vector H is always (+/-1, 0, 0)). A result of ~65600 samples is [here](https://www.dropbox.com/s/j7cycr7hn9wpuch/geo_factor_big.txt?dl=1). 

The nearest formula found is `G = min(1.0, 0.5 * abs(L * N) / (1 + L * V))`. For the case `1 + L * V == 0` G is set to 0. The overall error of this formula is +/- 0.01, which is negligible considering the measurement is taken by dividing two u8 integer. It is also shown in later tests that G does respect to the two-sided-diffuse bit, which means `abs(L * N)` part is actually `dot_product`.

Fixes the lighting issue of Smash Bros. Probably also fixes other games in #2477 but not tested yet.

Side note: after this PR and the tangent map one, the only known unimplemented feature in lighting is the shadow mapping.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2776)

### CODE REVIEW

**Comment by yuriks** [comment]
The paper "Primitive Processing and Advanced Shading Architecture for Embedded Space" (both actual paper as well as [presentation slides](http://highperformancegraphics.org/previous/www_2011/media/Papers/HPG2011_Papers_Kazakov.pdf)) have the formula `(L * N) / |L + V|^2` (aka `dot(L, N) / dot(H, H)`) for their approximation. This produces exactly the same results as the formula you found, but we should probably use that since it's easier to find a source for and slightly cheaper to compute.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2776#-:-Kmt96fKiGnfYtnY1kpP:b77mxzz)*

**Comment by wwylele** [comment]
Changed to what @yuriks suggested, and slightly refactored out the half-angle vector computation.

**Comment by yuriks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 524 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3oBVNJ7bg8DdtDkK:-Kmu3oBVNJ7bg8DdtDkL:b-eku8ri) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L524)):*
> ```cpp
>            "vec3 refl_value = vec3(0.0);\n"
>            "vec3 spot_dir = vec3(0.0);\n"
>            "vec3 half_angle = vec3(0.0);\n"
> ```

`half_vector` is a more common name for it.

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 568 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3VGcCkXrd97c2Kw3:-Kmu3VGcCkXrd97c2Kw4:bsghwr3) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L568)):*
> ```cpp
>     auto GetLutIndex = [&lighting](unsigned light_num, LightingRegs::LightingLutInput input,
>                                    bool abs) {
>         const std::string half_angle = "normalize(half_angle)";
> ```

For `view` we repeat the `normalize(view)` on every usage below. I think it would make sense to do the the same for `half_angle` which would turn all the strings below into constant strings with no concatenation (easier to read).

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 645 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3vV2gzsYh-qHYNRZ:-Kmu3vV3VVMJJhFXpSaG:box5m8b) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L645)):*
> ```cpp
> 
>         out += "spot_dir = " + light_src + ".spot_direction;\n";
>         out += "half_angle = normalize(view) + light_vector;\n";
> ```

You should declare the variable here instead of at the top so we don't accidentally use it before it has a value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2776#-:-Kmu43Z1eX_tyFsULFMj:bnfp4nl)*

**Comment by wwylele** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 524 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3oBVNJ7bg8DdtDkK:-Kmu5jsfBNb47ysbObUo:bb7f2mf) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L524)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

`half_vector` is a more common name for it.
</blockquote></details>

done

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 568 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3VGcCkXrd97c2Kw3:-Kmu5lbVob8DgkPhRON1:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L568)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

For `view` we repeat the `normalize(view)` on every usage below. I think it would make sense to do the the same for `half_angle` which would turn all the strings below into constant strings with no concatenation (easier to read).
</blockquote></details>

Done.

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 645 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3vV2gzsYh-qHYNRZ:-Kmu5m9UBlRivCksUnPQ:bdrqnw2) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L645)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

You should declare the variable here instead of at the top so we don't accidentally use it before it has a value.
</blockquote></details>

We declare all these variable (`light_vector`, `spot_dir`, etc) above because these lines are in a c++ loop but not in a GLSL loop. If they get declared here, they will be declared multiple times. Is this allowed in GLSL? or does GLSL support plain scope `{}` so we can move them into individual scope?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2776)*

**Comment by yuriks** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video_core/renderer_opengl/gl_shader_gen.cpp, line 645 at r2](https://reviewable.io:443/reviews/citra-emu/citra/2776#-Kmu3vV2gzsYh-qHYNRZ:-Kmu7wdGmhZjYVCsc2TB:b-xprzu) ([raw file](https://github.com/citra-emu/citra/blob/0136b9a1e72a4086dc7345941d38799f9360d96b/src/video_core/renderer_opengl/gl_shader_gen.cpp#L645)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

We declare all these variable (`light_vector`, `spot_dir`, etc) above because these lines are in a c++ loop but not in a GLSL loop. If they get declared here, they will be declared multiple times. Is this allowed in GLSL? or does GLSL support plain scope `{}` so we can move them into individual scope?
</blockquote></details>

Ah, I didn't realize that. From a quick test in shadertoy.com it seems that at least my drivers are fine with a stand-alone scope, but I don't know if that'll work with all vendors. I think it's fine to leave this as is then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2776)*

**Pull request merged**
