### PR TITLE
gl_rasterizer: call glTextureBarrier when an image is bound to both texture and framebuffer

### LINKED ISSUE #3731: [Monster Hunter XX] Artifacts due to Nvidia GPU's tiled cache (workaround available)
Edit: Workaround courtesy of /u/FIocker and @Krusher97 
https://www.reddit.com/r/cemu/comments/6qwmon/got_blocky_artifacts_in_lava_water_and_other/
Edit 2: Workaround only works on (non-native) 2x rendering and above.

Artifacts started showing up in Monster Hunter XX on canary-481-2763adf (last issue-free version tested is canary-478-db43205, no windows build was made available for 479 and 480 so i can't confirm)
image

Apparently it was a long standing issue for Nvidia cards that was pseudo-fixed for a while but came back.

Details from wwylele @ https://github.com/citra-emu/citra/pull/3499#issuecomment-387960317
"@Hoshiyuu that kind of artifact has been there for some Nvidia GPU since the first time citra was able to run Monster Hunter. It is in the texturing/rasterizer and is about the tiled cache. It was somehow "fixed" by the original version of this PR. However, it is likely that this PR didn't fix it, because this PR didn't touch the texturing/rasterizer part; instead, it was some unusual GPU usage, such as sharing different data in the same buffer, that disabled the (erroneous?) Nvidia optimization and removed the artifact. In recent commits I changed the code so that it worked in a more common way, which might enable the optimization again, and therefore the artifact is back."

### PR DESCRIPTION
**Pull request by wwylele**
The initial test of always calling glTextureBarrier fixes #3731. This version only calls glTextureBarrier on image bound to texture and framebuffer, which should be enough. More test are welcome

The game, Monster Hunter Gen/X/XX binds an image of the entire rendered screen to both texture and framebuffer to do gamma correction and stuff.

`CheckBarrier` is not applied to TextureCube because in the current texture cache module it can never be the same texture as the one attached to the framebuffer.

Thanks @degasus for finding this.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3926)

### CODE REVIEW

**Comment by wwylele** [comment]
Going to merge this if no more comments.

**Comment by AmbientMalice** [comment]
This PR also fixes distortion on the black and white flashback scenes in Phoenix Wright: Dual Destinies.

**Comment by Dragios** [comment]
What kind of distortion? Preview of both glitched and fixed?

**Comment by degasus** [comment]
Merge it!

**Pull request merged**
