### PR TITLE
savestates: save the build name to be displayed when there's a version mismatch

### PR DESCRIPTION
**Pull request by vitor-k**
This will help in the future when people have savestate issues.

The build_name field is added to the CST header, holding 20 characters, with the last one being reserved for null termination.
The number of characters was chosen arbitrarily with some leeway for future naming changes. For the current release channels of citra, only 14 characters would be necessary for the foreseeable future.

This implementation was chosen due to the relative simplicity and ease of implementation.
The alternative would be having 2 variables, one for the build "flavor" (head, canary, nightly), and one for the build version numbering. This would take less space but require some CI changes.

I am open to opinions on these implementation details, and all concerns should be resolved before this is merged, as we should try not to change this header once it's deployed.

When there's a revision mismatch, the build_name of the state will be shown in the UI and printed to the log, if it exists.
UI changes mockup:
image

Additionally, it seems like the zstd version was accidentally reverted in an unrelated change. Updated back to v1.5.5.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6493)

### CODE REVIEW

**Review by Steveice10 — APPROVED** [review]
This approach LGTM. I assume if we did need to expand the build name field for whatever reason we can just move the zero field? As I'm not sure we necessarily need to be that conservative with the max size.

**Comment by Steveice10** [comment]
Any updates on this?

**Comment by vitor-k** [comment]
Rebased and added a list of previous canary and nightly versions with save states, starting from when the PR was merged into master.

I hadn't marked it as ready for review until now because I wanted to think a bit more about the file structure, but I didn't have a lot of time for that on these months, and the current format should be fine.

**Comment by Steveice10** [comment]
LGTM still, could you get the latest few releases added to that list? Should be good to go ahead and merge after that, before it falls behind again.

**Pull request merged**
