### PR TITLE
AppVeyor: Upload build to Mega upon build completion

### PR DESCRIPTION
**Pull request by chinhodado**
This PR will upload the build to Mega upon build completion on AppVeyor. Specifically, it will copy over the required Qt dlls to the build folder, remove the junk files, then compress the build folder into a `.7z` file, and upload that file into a Mega folder.

Why Mega? It provides free 50GB storage, no bandwidth limit for upload/download, no wait for download, has the ability to create folders, can share a whole folder, and the interface is nice. [An example](https://mega.co.nz/#F!HR0CzZKZ!fLqLt_7xO7aKqmeVxwkRKQ).

The name of the result file will be

    <first 8 characters of the commit hash> - <first 100 characters of the commit message>.7z

The date of the commit is not included in the file name, since Mega can sort files based on upload date already (see my example folder above)

This will only run on the master branch. It will not run on pull requests or on other branches.

What @bunnei needs to do:

1. Create a Mega account
2. Create a `Citra` folder and a `Windows` folder inside that `Citra` folder. The idea is that later on we will have other folders for osx and Linux.
3. On AppVeyor, encrypt the Mega account password and get a string that looks like this: `ozgp54EZj98kcbD/O+Xl5Q==`. The encrypted string will be decrypted by AppVeyor during the build process, and it can only be decrypted on the original AppVeyor account that created it.
4. Post the email address of the Mega account and the encrypted string of the password here, so I can put it in my PR.
5. Profit

### CODE REVIEW

**Comment by archshift** [comment]
Is there a way for us to disable the packaging and uploading for PR builds? It would probably be bad for us to blindly distribute those, not to mention the fact that we don't want random people downloading the PR builds and asking for support for them, not to mention the fact that if we upload those it'll probably take up a huge portion of the 50GB.

**Comment by neobrain** [comment]
Why do we want this?

**Comment by chinhodado** [comment]
Why not? It's like a build bot.

**Comment by yuriks** [comment]
This is pretty awesome.

**Comment by neobrain** [comment]
@chinhodado I foresee a flood of random support requests coming in our direction once we start distributing official builds.

Anyway, as far as the code in this PR goes, it looks nice indeed. In the long run I'd prefer hosting builds ourselves though.

**Comment by chinhodado** [comment]
We don't need to say that these are official builds. We can just tuck the link somewhere in the wiki and say that we don't provide support for these builds.

Anyway, this is just a way to make use of the by-product of the CI process that is the result build. Everything is free, so why not? :)

**Comment by neobrain** [comment]
I remain unconvinced, but I don't really care either way. Passing the ball to the other team members :p

**Comment by mattvail** [comment]
I agree with @neobrain. Value-added for Citra is nothing. The team is not gonna use any of those builds. The only thing that can result from this is additionnal support requests for unsupported stuff.

Especially since the build alone will not run any commercial games without the required dumped files ...

@bunnei?

**Comment by chinhodado** [comment]
This essentially turns CIs into buildbots. Maybe right now the build doesn't have much value but isn't a buildbot what we would eventually want anyway?

Up to you guys.

**Comment by mattvail** [comment]
The main goal is to validate that a PR or commit does not break the build on Windows (which Travis doesn't do). Other than that... don't think there's a need. bunnei will have the final say I guess. Just my 2c

**Comment by archshift** [comment]
I think that this is pretty useful in the long run, it could potentially help with testing different revisions and it's nice while we don't have our own buildbot and server to host the builds on.

**Comment by purpasmart96** [comment]
I like it,  I see nothing wrong with it at all, the average clueless user is too dumb to find it anyway.

**Comment by neobrain** [comment]
Controversial-ish feature => let bunnei decide

**Comment by bunnei** [comment]
I don't see the harm. We aren't going to publicize that these even exist, and they aren't official releases that require support. My only gripe is that I would prefer not to use an account tied to a single developer (e.g. 'chin.bimbo@gmail.com'). Can you create an email purely for this (e.g. 'citra.appveyor.builds@gmail.com') and share the pwd with me or one of the other devs? Thanks

**Comment by chinhodado** [comment]
Done

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
