### PR TITLE
externals: allow user to use system fmt

### PR DESCRIPTION
**Pull request by Castor215**
I had to change the `target_link_libraries()` to use the alias `fmt` over `fmt::fmt` in order to get this to work. I hope this is ok.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7052)

### CODE REVIEW

**Comment by GPUCode** [comment]
I think fmt::fmt should be provided in the externals repo as well? What error did it give you?

**Comment by Steveice10** [comment]
> I think fmt::fmt should be provided in the externals repo as well? What error did it give you?

It’s so the system one can be aliased from the externals file, I think. The only way (IIRC) to propagate the found library out is to create an alias library and link to it.

**Comment by GPUCode** [comment]
It should work with find_package I believe, I did that in my old build system PR https://github.com/citra-emu/citra/blob/f345428b13ee6c36a8cced0044d63acd17228951/CMakeLists.txt#L206
And you can retain the newer target

**Comment by Castor215** [comment]
> I think fmt::fmt should be provided in the externals repo as well? What error did it give you?

You are correct. It does indeed probide the `fmt::fmt` target. But if I do this in externals/CmakeLists.txt
```
if(USE_SYSTEM_FMT)
    find_package(fmt REQUIRED)
else()
...
```
and have `citra_core` and `citra_common` link to `fmt::fmt`, I get this during configuration:
```
CMake Error at src/common/CMakeLists.txt:176 (target_link_libraries):
  Target "citra_common" links to:

    fmt::fmt

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I have tried creating `fmt::fmt` as an IMPORTED target, but that doesn't work either.

**Comment by Steveice10** [comment]
> It should work with find_package I believe, I did that in my old build system PR
> 
> https://github.com/citra-emu/citra/blob/f345428b13ee6c36a8cced0044d63acd17228951/CMakeLists.txt#L206
> 
> 
> And you can retain the newer target

That’s in the main CMakeLists, not the externals one. I honestly prefer this approach since it allows us to consolidate all the externals there instead of splitting the bundled and system externals into two places.

**Comment by GPUCode** [comment]
Yeah I agree on that point

**Review by Steveice10 — APPROVED** [review]

**Pull request merged**
