### PR TITLE
Remove unused Copy, CopyDir and GetThemeDir functions from FileUtil

### PR DESCRIPTION
**Pull request by linkmauve**

### CODE REVIEW

**Comment by yuriks** [comment]
Is there any chance we might want to use these to implement some functions in FS?

**Comment by archshift** [comment]
`Copy` and `CopyDir` could definitely come in handy in the future, IMO. I don't think they should be removed.

**Comment by mailwl** [comment]
Agreed. emulator must be similar to real hardware

**Comment by lioncash** [comment]
That has nothing to do with emulation itself lol

**Comment by mailwl** [comment]
Ah! sorry. i think the talk about fs service

**Comment by neobrain** [comment]
Ew, the implementation of these looks kind of ugly to begin with. But they will sooner or later be needed, and if they are deemed too ugly they can still be rewritten at that point.

**Comment by neobrain** [comment]
That said, feel free to reopen this PR with only GetThemeDir removed.

**Pull request closed without merging**
