### PR TITLE
dumping/ffmpeg_backend: Various fixes

### LINKED ISSUE #5410: Rhythm Heaven Megamix - Music starts 4 frames ahead than it should
Citra https://github.com/citra-emu/citra/commit/16913feb4441ffba1a57347953a8a6aa0103e5c5
Windows 10 x64 build 1809

Using the 'Dump Video' feature from Citra (recording from the very start of the game to avoid any desynching) I aligned the footage frame-perfectly with footage from real hardware.
I audio panned Citra on the left, and real 3DS on the right.
https://youtu.be/pQ8j0tHx8iU

Opening the audio from the video in audacity reveals that Citra starts the song earlier than it should.
| image |
|:--:| 
| Top: Citra - Bottom: 3DS |

By how much? With my video editor I moved back the real hardware footage by 4 frames. This seems to align the music perfectly.
| image |
|:--:| 
| Top: Citra - Bottom: 3DS |

Video adjusting the 3DS audio to match Citra. Using the '.' and ',' keys to frame advance you can see now that due to this compensation visuals are running ahead on the 3DS footage.
https://youtu.be/ui7ngECImu0

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
Fixes some issues with the FFmpeg backend. Please refer to the commit messages for details.

cc @xperia64 @oddMLan

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5411)

### CODE REVIEW

**Comment by oddMLan** [comment]
@zhaowenlan1779 with this PR I just hear static whenever AAC audio plays with HLE, across all backends. Using Windows 10 x64 1809. LLE is unnafected.

**Comment by xperia64** [comment]
> @zhaowenlan1779 with this PR I just hear static whenever AAC audio plays with HLE, across all backends. Using Windows 10 x64 1809. LLE is unnafected.

How are you testing this? If you're testing a Mingw build, those are likely broken.

**Comment by oddMLan** [comment]
> How are you testing this? If you're testing a Mingw build, those are likely broken, and have nothing to do with the PR.

Correct, sadly that's the only build that compiled in the buildbot. The rest are failing. Do I have to compile Citra myself?

**Comment by xperia64** [comment]
> > How are you testing this? If you're testing a Mingw build, those are likely broken, and have nothing to do with the PR.
> 
> Correct, sadly that's the only build that compiled in the buildbot. The rest are failing. Do I attempt to compile Citra myself?

Yes. But I can assure you this makes no changes to the AAC framework. I promise.

**Comment by pokeysoda** [comment]
ok, so im incredibly new here, i just learned how to build citra from the repository _today_ and its my first foray into anything of this sort, so im not exactly sure how to word my response to this, or if im leaving any information out... my point is, i was able to get this to work and it seems to have fixed the issue

**Comment by oddMLan** [comment]
Eureka! @zhaowenlan1779 
This does fix the video desync problem with Dump Video in the referenced ticket. owever with the libx264 codecs it makes the video Black and White. libvp9 is incredibly slow now. And with raw video (avi+uncompressed or mkv+raw video) the audio seems to skip frames at random.

Here's a video comparison to confirm indeed the audio and video are well synched now.
I was able to record this fine with mp4+h264 qsv.
https://youtu.be/yvUmlCYODxs

If you look closely (using . and , to frame advance) there are still cuts that are 1-2 frames off, but the inputs of emu vs hardware aren't identical here so I can chalk it up as the timing being different there because the intputs are different. Who knows.

BTW is there like a "Skip XFB" option like in Dolphin? There's a 2-frame delay since the button is pressed. It's the same in Dolphin, but with that option the delay becomes only 1 frame.

**Comment by zhaowenlan1779** [comment]
Huh, I think I made this on wrong assumptions and it just happened to fix the issue. I dropped that commit. More investigation is required.

Meanwhile the video black and white issue should now be fixed. I can't reproduce the performance issue with VP9 - apparently it's not visibly slower for me

**Comment by zhaowenlan1779** [comment]
Untagging to diagnose build issues

**Comment by SachinVin** [comment]
Any reason to not merge this ? It's been in canary for... a while

**Comment by fsvgm777** [comment]
The dumps should be at the console's native framerate (268111856/4481136 FPS or roughly 59.83122493939037 FPS), not a flat 60 FPS. The latest nightlies are fine in that regard (as in, they dump at 268111856/4481136 FPS).

**Comment by FearlessTobi** [comment]
Untagging because of MSVC compilation issues.

**Comment by Yaboyleo** [comment]
wait dosen't this work on retroarch as well? i mean you can emulate 3ds roms on the application.

**Comment by FearlessTobi** [comment]
Superseded by https://github.com/citra-emu/citra/pull/6528.

**Pull request closed without merging**
