### PR TITLE
[WIP] Decrease maximum circle pad range

### LINKED ISSUE #2066: Theatrhythm: Curtain Call Input not working while playing a music stage
While in the menu every key works flawlessly, but in a music stage the key for "up" and "left" don't work at all, which is critical for a game like this. Up and left refer to the 3ds' analog stick and strangely when pressing something in between, for example right and up, the game sees that as a valid input for "up" - even though up alone does nothing.

### PR DESCRIPTION
**Pull request by xperia64**
Fixes #2066.

I stepped through various circle pad scaling factors until I found the largest one that still worked in FF Theatrhythm CC. This value also coincides with this suggestion here: https://github.com/citra-emu/citra/issues/2066#issuecomment-246687795

This is [WIP] because it should be verified that it doesn't break other games, it should be tested on hardware more, and the issue tracker should be searched in case there are other games with circle pad issues to verify that this value works for them too.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5272)

### CODE REVIEW

**Comment by BreadFish64** [comment]
User is reporting strange sneaking behavior in pokemon.
https://discordapp.com/channels/220740965957107713/220742362740162560/705078548284833824

**Comment by tywald** [comment]
I can confirm that user report. If you walk around "normally" in Pokémon Alpha Sapphire/Omega Ruby it would change to a faster sneak animation while moving diagonally, happens on both keyboard and controller.

**Comment by B3n30** [comment]
@xperia64 Did you made any progress here?

**Comment by xperia64** [comment]
> @xperia64 Did you made any progress here?

Not yet. This PR in itself is probably not the solution, so I may close it and open something else when I can verify for sure.

**Comment by xperia64** [comment]
This PR is clearly wrong, so I'm closing it. I have another potential fix that shouldn't break things.

**Pull request closed without merging**
