### PR TITLE
armdefs: Remove unnecessary extern C

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by yuriks** [comment]
Shouldn't you also remove these from wherever the function definition is?

**Comment by lioncash** [comment]
I'll be cleaning the function externs up in another PR, since almost all funcs in the dyncom that are visible outside translation units use extern.

**Comment by yuriks** [comment]
I'm pretty sure removing `extern "C"` only in one place is supposed to break linking, at least in some platforms.

**Comment by lioncash** [comment]
This would have happened a long time ago then (I removed several other extern Cs in past cleanups). So far it hasn't been an issue.

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
