### PR TITLE
vector_math: Add missing member in Vec4's SetZero function

### PR DESCRIPTION
**Pull request by lioncash**
Previously Vec4's SetZero would only reset three of its four elements.

### CODE REVIEW

**Comment by archshift** [comment]
LGTM

**Comment by yuriks** [comment]
Was this function even used? I wonder if it causes any bugs.

**Comment by lioncash** [comment]
@yuriks Luckily, no

**Comment by JayFoxRox** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
