### PR TITLE
NWM_UDS: use sizeof(<var being used>) instead of hard-coded type

### LINKED ISSUE #4090: [UDS] Monster Hunter XX - multiplayer with 3 and 4 players is not working since Nightly-864
According to https://community.citra-emu.org/t/monster-hunter-xx-multiplayer-problems/40044 and https://www.reddit.com/r/Citra/comments/96ihlj/monster_hunter_xx_i_cant_connect_more_than_2/

Bisected to Nightly-864, PR being #3985 

image
image

@BreadFish64 fixup requested!

### PR DESCRIPTION
**Pull request by wwylele**
Intend to fix #4090. 

` node_map.node.second` type was changed to `u16` in #3985. However the type change wasn't reflected here. Should have used variable name instead to automatically do type change

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4093)

### CODE REVIEW

**Comment by wwylele** [comment]
@tywald could you test this?

**Comment by Subv** [comment]
Doesn't this make the network protocol incompatible with older versions?

**Comment by MojoJojoDojo** [comment]
There is also nsmb2 not working.

**Comment by tywald** [comment]
#4090 fixed with this PR.

image

**Pull request merged**
