### PR TITLE
core: De-globalize movie

### PR DESCRIPTION
**Pull request by GPUCode**
First step into untagling our global state mess

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6659)

### CODE REVIEW

**Comment by GPUCode** [comment]
The diff appears larger because I removed a bunch of includes in core/core.h and those need to be included explicitely in the cpp files they are used

**Review by Steveice10 — APPROVED** [review]

**Comment by Steveice10** [comment]
Conflicts in canary https://github.com/citra-emu/citra/actions/runs/5459309138/jobs/9935179489

**Comment by Steveice10** [comment]
Please rebase

**Comment by Steveice10** [comment]
Needs rebase and build was failing.

**Comment by GPUCode** [comment]
Rebased

**Pull request merged**
