### PR TITLE
AMD 22.7 workaround ... maybe

### PR DESCRIPTION
**Pull request by SachinVin**
cc @xperia64 @peacepenguin

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6079)

### CODE REVIEW

**Comment by GPUCode** [comment]
I don't understand why ALLOW_SHADOW is kept these days. Back when OpenGL ES 3.2 was bleeding edge it made sense to check for these features but nowadays almost every OpenGL driver supports image load/store operations. The mobile device requirements to run Citra are also pretty high already and I don't think any user would appreciate playing their games without shadow mapping. I propose to drop this and just throw a device unsupported error if GL_ARB_shader_image_load_store or GL_ARB_shader_image_size are not supported.

**Comment by xperia64** [comment]
GL_ARB_shader_image_size is not supported on AMD's drivers in a 3.3 context. According to the official Khronos spec, this technically requires a 4.2 context and never should have worked.

**Comment by Nezarn** [comment]
> I propose to drop this and just throw a device unsupported error if GL_ARB_shader_image_load_store or GL_ARB_shader_image_size are not supported.

Or just add an option as hack to bump shader version tag to 420 or 430 which fixes the issue with 0 change to the if statements.

**Comment by GPUCode** [comment]
> 

That would work but relies on driver behavior that is not explicitly defined by the specification. The proper fix would be the bump the context version to 4.2. I don't see any reason against this, as the emulator [uses](https://github.com/citra-emu/citra/blob/b3cab3c4507dc1b28e2f15b2e0c9f473f6e1959f/src/citra/emu_window/emu_window_sdl2.cpp#L198) different paths to initialize desktop OpenGL and ES.

**Comment by xperia64** [comment]
> > I propose to drop this and just throw a device unsupported error if GL_ARB_shader_image_load_store or GL_ARB_shader_image_size are not supported.
> 
> Or just add an option as hack to bump shader version tag to 420 or 430 which fixes the issue with 0 change to the if statements.

That appears to require a 4.2/4.3 context as well (which I'm not against, given the sorry state of macOS these days)

**Comment by GPUCode** [comment]
> > > I propose to drop this and just throw a device unsupported error if GL_ARB_shader_image_load_store or GL_ARB_shader_image_size are not supported.
> > 
> > 
> > Or just add an option as hack to bump shader version tag to 420 or 430 which fixes the issue with 0 change to the if statements.
> 
> That appears to require a 4.2/4.3 context as well (which I'm not against, given the sorry state of macOS these days)

Bumping the context could also allow for further improvements to the OpenGL backend, biggest of which is ARB_direct_state_access imo

**Comment by SachinVin** [comment]
@xperia64 I'm not seeing  `Shadow might not be able to render because of unsupported OpenGL extensions.` warning on logs with older drivers, so it definitely seems to be have been supported. There are other places we check for the extensions to populate the uniform, so shadow would've been lost before this change 
> According to the official Khronos spec, this technically requires a 4.2 context and never should have worked.

As far as I understand extensions can be used on old opengl contexts too, we use GL_ARB_get_program_binary introduced in 4.1-ish for shader cache.

**Comment by xperia64** [comment]
> As far as I understand extensions can be used on old opengl contexts too, we use GL_ARB_get_program_binary introduced in 4.1-ish for shader cache.
Extensions appear to have version requirements too, and get_program_binary as an extension calls out 3.0 as a requirement, while image_size calls out 4.2

**Comment by SachinVin** [comment]
I see, i wonder why they and other vendors support it then, just a quality of life feature? (i can understand nvidia because they like to make their own spec.)

**Comment by SachinVin** [comment]
I'll tag it to canary for now, while we contemplate dropping macos support.

**Comment by dante3732** [comment]
I test it in 10 games, it work fine, but the emulator periodically stops responding for 1-2 seconds.

**Comment by SachinVin** [comment]
Untagged, conflicts with #6103

**Pull request closed without merging**
