### PR TITLE
applets: stub mii selector to always return a standard mii

### LINKED ISSUE #3743: Super Mario 3D Land: Save File not recognized, but still loads correctly
I'm running Canary HEAD-4687EE7, and when I boot the game with a previous save file, it sees none in the load menu.

image

In this case, slot A is where the save data is located. When slot A is selected, it takes you through the process of creating a new save file in that slot.

However when the game is loaded, it's not a new game. It is indeed loads the game in its previously saved state.

image

I'm attaching the log to this issue.
[citra_log.txt](https://github.com/citra-emu/citra/files/1998714/citra_log.txt)

### PR DESCRIPTION
**Pull request by FearlessTobi**
Thanks to @valentinvanelslande for the initial implementation and helping me figure this out.

With this PR, a "standard mii" will always be returned when the (HLE) mii selector applet is used.
It is named Citra and has the standard settings for its look.

For instructions on how to reproduce the process of getting the data, take a look at the commit message.

This fixes #3743 and probably some other (unreported) issues.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4279)

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Build failure is not related to this PR.

**Comment by FearlessTobi** [comment]
It seems like its possible, but I need to investigate this further.

**Comment by FearlessTobi** [comment]
Cause I don't want any issues with too quick merges again, let me make it clear: Don't merge this PR until I've got wwyleles review comment addressed.

**Comment by bunnei** [comment]
What is the status of this PR?

**Comment by FearlessTobi** [comment]
@bunnei Converting the raw data to members of a struct is like 95% done. Just need to do some minor changes and test everything again, then I'll push it out.

**Comment by bunnei** [comment]
@FearlessTobi ping again on this PR

**Comment by bunnei** [comment]
@FearlessTobi ping again on this PR

**Comment by FearlessTobi** [comment]
I planned to finish it up this week, but something got in the way. @bunnei 
Same for the other PR you tagged me in.

**Pull request merged**
