### PR TITLE
Edit Citra URLs

### PR DESCRIPTION
**Pull request by atouchet**
The URL structure was changed so these led to 404 pages.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2728)

### CODE REVIEW

**Comment by wwylele** [comment]
The two in the source code is going to be covered by #2611 . You can just change the `.github/ISSUE_TEMPLATE.md` one

**Comment by atouchet** [comment]
@wwylele Do you expect that PR will be merged in the very near future? Having support links direct to a 404 page is something I think should be fixed quickly.

**Comment by TheKoopaKingdom** [comment]
I would say pretty soon, within the next week or two.

**Comment by TheKoopaKingdom** [comment]
#2611 has now been merged.

**Pull request merged**
