### PR TITLE
Test PR -- Please ignore.

### PR DESCRIPTION
**Pull request by chris062689**
Updated the README.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2890)

### CODE REVIEW

**Comment by mailwl** [comment]
dislike

**Comment by BreadFish64** [comment]
I think Citra: the Emulator would be better

**Comment by einstein95** [comment]
Citra The Emulator 3 & Knuckles

**Comment by BreadFish64** [comment]
Featuring Dante from the Devil May Cry series

**Comment by khang06** [comment]
New Citrastved The Emularor 3Mix and Knuckles Limited Complete Edition U

**Comment by B3n30** [comment]
Is this still needed, or can we close it?

**Comment by chris062689** [comment]
This PR was designed so we can quickly trigger a canary build without tagging / untagging a random PR.

**Comment by B3n30** [comment]
closed, since it is no needed atm.
Feel free to reopen, if needed

**Pull request closed without merging**
