### PR TITLE
Prevent non-Windows OS from sleeping when a game is running

### PR DESCRIPTION
**Pull request by dackst**
Implements #4914 for mac and other unix-like platforms

Admittedly, I don't have a mac available to test this on, but the implementations as of the first commit were copied almost directly from Dolphin's `EnableScreenSaver` function. Apologies if I messed something up there.

Dolphin's linux implementation uses xdg-screensaver, a part of xdg-utils, which I think can be expected to be already installed, as it is a dependency of qt. However, it only seems to work if the net-dbus and x11-protocol optional dependencies of xdg-utils are installed, which wasn't the already the case in my system. Otherwise, it fails and there's no effect (i.e. the system still tries to sleep when a game is running).  I switched to using qt's dbus module instead, which I don't think requires any extra dependencies?

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5507)

### CODE REVIEW

**Comment by gal20** [comment]
This wouldn't work in flatpak, because the application doesn't have permission to access the dbus. You'll need to add the permission `--talk-name=org.freedesktop.ScreenSaver` to the flatpak manifest (found [here](https://github.com/dackst/citra/blob/1e9cb1674a12ca41331a50dd4230ed43fc7c4ded/.travis/linux-flatpak/generate-data.sh#L70)).

**Comment by dackst** [comment]
> You'll need to add the permission `--talk-name=org.freedesktop.ScreenSaver` to the flatpak manifest (found [here](https://github.com/dackst/citra/blob/1e9cb1674a12ca41331a50dd4230ed43fc7c4ded/.travis/linux-flatpak/generate-data.sh#L70)).

Done.

**Review by zhaowenlan1779 — APPROVED** [review]

**Comment by zhaowenlan1779** [comment]
The macos check was failing and the log has expired. I'm wondering if that was caused by this PR?

**Comment by dackst** [comment]
I think I remember the macOS check failing on everything at the time. They seem to be passing on other things now, so I guess it might work here now too.

**Comment by vitor-k** [comment]
2 things:
We mostly prefer rebasing to merging, though it's not that big of a deal.
Since a few changes enacted by Github, now first-time contributors need maintainer approval for the CI to run, so someone needs to do that (it's a different approval from review approval).

**Comment by B3n30** [comment]
Approved fro CI

**Comment by dackst** [comment]
Removed the merge commits

The log talks of a conflict with `Debugger`, which apparently the new mac import tries to redefine somewhere down the line. It seems at least [build successfully](https://github.com/dackst/citra/actions/runs/963596177) now.

**Comment by zhaowenlan1779** [comment]
That looks okay. Please add a comment in the code though, so that future readers can see why this is necessary.

**Comment by dackst** [comment]
Comment added.

**Comment by FearlessTobi** [comment]
Superseded by https://github.com/citra-emu/citra/pull/6249.

**Pull request closed without merging**
