### PR TITLE
HLE/FS: Converted some functions to use IPCHelpers

### PR DESCRIPTION
**Pull request by Subv**
Namely:
* OpenFileDirectly
* DeleteFile
* RenameFile
* DeleteDirectory
* DeleteDirectoryRecursively
* CreateFile

There are still many left to convert, and then we'll have to convert the entire service to ServiceFramework, this is not included in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3252)

### CODE REVIEW

**Comment by valentinvanelslande** [comment]
is this needed for home menu?

**Comment by Subv** [comment]
This has nothing to do with the Home Menu

**Comment by valentinvanelslande** [comment]
This PR breaks everything.
With this, i get a lot of errors and fatal errors.
StreetPass Mii Plaza spams fatal errors and crashes Citra.
spam

**Comment by Subv** [comment]
I can't test that but every other game i've tried works fine. Do you have a log?

**Comment by valentinvanelslande** [comment]
Try 11.6 Mii Plaza
If works, format config savegame and retry

**Comment by Subv** [comment]
Do you have a log?

**Comment by valentinvanelslande** [comment]
added

**Comment by Subv** [comment]
Nice catch, please test now.
Thanks!

**Pull request merged**
