### PR TITLE
Add MinGW CMake option to disable DWARF debugging information

### PR DESCRIPTION
**Pull request by vvanelslande**
Also, I disabled it for the Linux MinGW build.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4885)

### CODE REVIEW

**Comment by jroweboy** [comment]
Thanks for the PR. :+1: 

Could we instead default the option to compiling without DWARF information and then have the build bots explicitly add the `COMPILE_WITH_DWARF` build option? That way it removes one more WTF for people building with mingw?

**Comment by zhaowenlan1779** [comment]
Eh.. I think this should be inverted.
When compiling in general we would usually want the debugging information to use with debuggers, but for CI builds (meant for releases) we would strip it out anyway and therefore, we do not need to generate it at all.
So IMO if we want to introduce this option it should be ON by default and turned OFF for CI builds. This also matches our previous behavior.

**Comment by zhaowenlan1779** [comment]
Maybe add this flag to Appveyor MinGW build as well?

**Comment by vvanelslande** [comment]
@zhaowenlan1779 no, it's enabled by default

**Comment by zhaowenlan1779** [comment]
Oh yeah, Appveyor needs the debug info. My bad.

**Pull request merged**
