### PR TITLE
fix compiling problem with vs2017

### PR DESCRIPTION
**Pull request by yhnmj6666**
VS 2017 will report something like " '__cpuid': identifier not found " if <intrin.h> isn't included.

### CODE REVIEW

**Comment by wwylele** [comment]
Is this the only error we get on VS 2017?

**Comment by jfmherokiller** [comment]
I dont believe so but rn i think visual studio 2017 is still in the release candidate stage

**Comment by legoj15** [comment]
As of March 9th, VS 2017 is released. 

Or that's what this says at least https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

**Comment by jfmherokiller** [comment]
well can somone test that you can select the visual studio 2015 toolset from the cmake gui if you install it via vs2017?

**Comment by bunnei** [comment]
This change was just merged with #2626, thanks anyway!

**Pull request closed without merging**
