### PR TITLE
Add THREADPROCESSORID_MAX on SVC::CreateThread

### PR DESCRIPTION
**Pull request by JamePeng**
#1449 
PTM::CheckNew3DS will return the machine type(u8 output: 0 = Old3DS, 1 = New3DS.) 
so, if you select the New3DS,it will cause a assert failed!

### CODE REVIEW

**Comment by Subv** [comment]
:-1: The ProcessorId enum should be changed to reflect the new CPUs in the n3DS

**Comment by JamePeng** [comment]
@

**Comment by JamePeng** [comment]
@Subv No,the crash rely on "CheckNew3DSApp"，if you select New3DS status. 
The crash still happen!

**Comment by Subv** [comment]
What? How is that related to what i said?

**Comment by bunnei** [comment]
@JamePeng I'm going to close this one... This is not the right way to fix this issue. THREADPROCESSORID_MAX is meant for doing bounds checking on valid processor IDs for O3DS, it itself was not meant to be used as a valid ID.

**Pull request closed without merging**
