### PR TITLE
Only redefine some 64-bit file operation for MSVC

### LINKED ISSUE #4332: Launching titles with seed crypto fails the first time
On the latest nightly (0962AB8), attempting to launch a title with seed crypto (with the correct seed in seeddb.bin) after starting Citra will result in a "your rom is encrypted" message and the error "<Error> core/file_sys/ncch_container.cpp:Load:174: Seed for program 00040000001A7100 not found". Attempting to launch the title (or another seed crypto title) a second time works normally. The same happens for both installed titles and loose ncch files.

Another smaller but possibly related issue: installing a CIA with seed crypto will remove the name/icon in the game list from all previously installed CIAs (including the one being installed) until the emulator is restarted.

### PR DESCRIPTION
**Pull request by wwylele**
@bakugo could you test to see if this fixes #4332 ?

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4336)

### CODE REVIEW

**Comment by bakugo** [comment]
It's fixed, thanks.

**Comment by wwylele** [comment]
Untagging as this cause some issue booting games

**Comment by wwylele** [comment]
@bakugo Do you have idea why this breaks some games (e.g. pokemon)?

**Comment by bakugo** [comment]
The new issue is related to fseeko not seeking to the right place. I think I know why but I still need to test more.

**Comment by bakugo** [comment]
Okay, I was right, the flag _FILE_OFFSET_BITS=64 just needs to be set for mingw as well (it's already set but for Linux only) in CMakeLists.txt to make off_t 64 bits, otherwise games with large file sizes like pokemon cause these functions to overflow.

**Comment by bakugo** [comment]
Everything seems to be working fine now.

**Pull request merged**
