### PR TITLE
Port yuzu-emu/yuzu#2451: "travis: Update to using Xcode 10.2"

### PR DESCRIPTION
**Pull request by FearlessTobi**
See yuzu-emu/yuzu#2451.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4769)

### CODE REVIEW

**Comment by B3n30** [comment]
Note that this might be a bigger change than you think. This will start building on osx 10.14 instead of 10.13, which could mean users can't use Citra on older systems.

**Comment by wwylele** [comment]
@B3n30 Isn't our Qt frontend broken for 10.13 anyway? :p

**Comment by B3n30** [comment]
Not for all users and not related to osx 10.13 but the qt version. So I won't bet on it getting fixed with osx 10.14

**Comment by B3n30** [comment]
BTW if we merge this (and I'm not a fan of it until it is really necessary), https://github.com/citra-emu/citra/blob/c1de8acfe5895f16713cd20cdc105d69036304a3/.travis/macos/build.sh#L5 needs to get changed too

**Comment by FearlessTobi** [comment]
I guess this can be closed then.

**Pull request closed without merging**
