### PR TITLE
ci: Do not fail macos-universal when deletion of intermediates fails.

### PR DESCRIPTION
**Pull request by Steveice10**
Sometimes the macos-universal workflow step to delete the intermediate artifacts fails due to unknown GitHub errors. Since this is not fatal for us, set ```failOnError``` to false so it doesn't fail the whole build.

If the step fails it will leave behind some extra artifacts for arch-specific builds, but this rarely happens and is not a big issue, and it's better than failing the build altogether. If absolutely necessary one can manually delete the artifacts from the build if this happens.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6631)

### CODE REVIEW

**Comment by SachinVin** [comment]
Wouldn't this upload the intermediate artifacts to the release?

**Comment by Steveice10** [comment]
> Wouldn't this upload the intermediate artifacts to the release?

If the delete fails, yes. Those artifacts being single-arch macOS builds. It’s a trade-off whether we want to fail the build if an error occurs deleting or tolerate the potential rare extra artifact.

**Review by vitor-k — APPROVED** [review]

**Comment by SachinVin** [comment]
Any idea which one the installer would pick? The universal ?

**Comment by Steveice10** [comment]
> Any idea which one the installer would pick? The universal ?

I'm not really sure, I think it would go for the first in the artifact list.

**Comment by Steveice10** [comment]
I found another way to do the universal build without creating intermediate artifacts, by saving the arch-specific job outputs to cache and pulling them in the universal job. It's a lot faster that way too. This has been incorporated into the CI reworks PR.

**Comment by vitor-k** [comment]
For future reference, the referred CI PR is #6556

**Pull request closed without merging**
