### PR TITLE
audio_core\hle\shared_memory.h: Update struct member names based on FE:Fates Symbols

### PR DESCRIPTION
**Pull request by SachinVin**
Rename and add some of the easy to find variables.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6995)

### CODE REVIEW

**Review by Steveice10 — APPROVED** [review]

**Review by FearlessTobi — APPROVED** [review]

**Comment by GPUCode** [comment]
Btw I'm curious, what does the added warning mean exactly?

**Comment by SachinVin** [comment]
>  // TODO(SachinV): This is probably not accurate, based on symbols from FE:Fates,
    // state.intermediate_mixer_volume[0] represents the master volume

If you mean this comment, then these volumes don't seem map to intermediate mixers volumes. I think it is supposed to use the gain[][] table. 
I haven't actually changed the code since it would require more RE work than I have done here

**Comment by GPUCode** [comment]
Hm can this information be found by REing the dsp firmware or the dsp service?

**Comment by SachinVin** [comment]
Dsp firmware. As far as I understand the dsp service only forwards stuff to the dsp. (And maybe some sanitization)

**Pull request merged**
