### PR TITLE
archive_ncch: add open source country list archive

### PR DESCRIPTION
**Pull request by wwylele**
See [here](https://github.com/B3n30/citra_system_archives/tree/master/country_list) for the source code for generating the data. (Un)fortunately the generated data is a 100% match with the original version dumped from 3DS. There shouldn't be copyright issue, however, as the source code shows that the data can be generated purely from public information.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4256)

### CODE REVIEW

**Comment by lioncash** [comment]
Just a suggestion, but for yuzu, I made a Python script that generates files like these from data, but generates them in .cpp and .h pairs, so the data doesn't get copied twice if ever used in more than one translation unit (was used for this [PR](https://github.com/yuzu-emu/yuzu/pull/1293)). It can be found [here](https://gist.github.com/lioncash/d0e1fd8f8390f2462ba4361ed0236f16) if it seems like a good idea for citra.

**Comment by wwylele** [comment]
@lioncash good idea actually. I'll look into it in the next pass where we are going to unify the open source archive generator into python scripts.

**Comment by wwylele** [comment]
Sorry that I lied a little. There is a small chunk of data that is not public information. The `tail` field that you can see in the [json file](https://github.com/B3n30/citra_system_archives/blob/master/country_list/country.json). They are there for every each country entry and are usually 4 - 12 bytes long. Most of them are zeros. A few of them are strangely non-zero and has some special values like `0xFFFFFFFF`, `0x00400000`. I have no idea what they means.

**Comment by wwylele** [comment]
It is identified that `tails` are bit flags, one bit for each country/division. Only a few entries has this bit set. If I don't find what it means soon, I'll just clear them all in the open source archive.

**Comment by wwylele** [comment]
The unknown `tail` problem is solved in https://github.com/B3n30/citra_system_archives/pull/9. The generated data is unchanged.

**Comment by wwylele** [comment]
going to merge if no more comments.

**Pull request merged**
