### PR TITLE
shader_interpreter: Fix control flow edge cases and implement break/breakc 

### PR DESCRIPTION
**Pull request by GPUCode**
Basically a rebase of https://github.com/wwylele/citra/pull/48
Fixes Steel Diver Sub Wars with the shader interpreter may fix other games that use breakc like Gunman Clive.
The code looks okay to me and matches the 3dbrew control flow [section](https://www.3dbrew.org/wiki/GPU/Shader_Instruction_Set). Additional reviews are appreciated though

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6844)

### CODE REVIEW

**Comment by GPUCode** [comment]
Depends on https://github.com/citra-emu/ext-boost/pull/32
Tested a variety of games and no regressions so far. All shader tests pass as well

**Review by Steveice10 — APPROVED** [review]

**Comment by wheremyfoodat** [comment]
Out of curiosity, can you get a disassembly of the code the use of boost::circular_buffer emits? The size of the ring buffer is not a template parameter so I expect it to emit kind of bad code for the wrapping (eg fetch the size from memory and use idiv to calculate modulo as if it didn't know the size)

This shouldn't be a blocker for the PR, just rather curious. Not like shader interpreter speed matters much anymore.

**Comment by SachinVin** [comment]
We alread y had an implementation for a circular buffer https://github.com/citra-emu/citra/blob/master/src/common/ring_buffer.h

**Comment by GPUCode** [comment]
Hm didn't know we that in common. Looking at the interface though it appears impractical compared to the boost one. Is it okay if I amend the existing one in this PR, or do it in another one?

**Comment by Steveice10** [comment]
> Hm didn't know we that in common. Looking at the interface though it appears impractical compared to the boost one. Is it okay if I amend the existing one in this PR, or do it in another one?

If we want to switch audio over to boost circular buffer, probably a separate PR. If we want to adapt the current RingBuffer for this use case, probably good to do here.

**Comment by FearlessTobi** [comment]
@GPUCode Whats your plan regarding the ringbuffer?

**Comment by Steveice10** [comment]
Opened a PR to move the DSP FIFO over to circular_buffer: https://github.com/citra-emu/citra/pull/6906

**Pull request merged**
