### PR TITLE
externals: point to upstream dynarmic

### PR DESCRIPTION
**Pull request by SachinVin**
Upstream dynamic now works well with the android app, so it's a great time to switch from our old fork.
Also, bumped xbyak and cleaned up the CMakelists.
and removed the no longer used `DYNARMIC_NO_BUNDLED_FMT` option.

This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6233)

### CODE REVIEW

**Comment by vitor-k** [comment]
It seems to be pointing to a commit from upstream dynarmic, but in the citra-emu fork.
Should the .gitmodules be updated to point to upstream as well?

**Comment by SachinVin** [comment]
fixed, thanks.

**Comment by SachinVin** [comment]
closed in favor of https://github.com/citra-emu/citra/pull/6240

**Comment by innovation2013** [comment]
After updating to the upstream, the game is now running very slowly, such as Monster Hunter 3G, the FPS dropped from 60 to 20, and it is very unstable

**Pull request closed without merging**
