### PR TITLE
service/nwm_uds: Various improvements/corrections

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
This is an attempt to fix @tywald's problem with MH, reported on Discord a while ago. Apparently it is fixed by the first two commits. The third commit addresses the issue of Citra sometimes crashing when host close the network.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5382)

### CODE REVIEW

**Comment by tywald** [comment]
During my initial testing suggests it partially fixes it, the crash associated with it seems to be gone though.

If all 4 players join and player 2 disconnects then player 2 would be unable to reconnect on latest Nightly/Canary however with this PR player 2 can reconnect.
If both player 2 & 3 disconnect then the first player that tries to reconnect will fail while the other will succeed, at this state the game will say the hub is full while there is a spot still open.

I will check later during next week what node_info looks like.

**Comment by zhaowenlan1779** [comment]
@tywald I pushed a new commit, can you please test it? I'm just randomly trying things now and I'm not sure if it will work at all though :p

**Comment by tywald** [comment]
Ow this didn't work at all unfortunately, nobody could join.
logs: [logs.zip](https://github.com/citra-emu/citra/files/4718952/logs.zip)

**Comment by tywald** [comment]
Same as the first test, if player 2 & 3 disconnects one of them will fail when they try reconnect but the other will succeed.
logs: [logs.zip](https://github.com/citra-emu/citra/files/4726020/logs.zip)

**Comment by BreadFish64** [comment]
Does this PR fix the initial issue now?

**Comment by tywald** [comment]
Yes, but I will test other games to check if they are fine.

**Comment by zhaowenlan1779** [comment]
This technically doesn't require a version bump, but since we've been making a lot of UDS changes recently, we may as well do one when we merge all of these

**Review by B3n30 — APPROVED** [review]

**Pull request merged**
