### PR TITLE
Kernel/SVC: Partially implemented svcReplyAndReceive

### PR DESCRIPTION
**Pull request by Subv**
This svc takes care of most IPC duties, more information can be found [here](https://www.3dbrew.org/wiki/IPC#svcReplyAndReceive)

It behaves mostly as WaitSynchronizationN with wait_all = false, except for IPC buffer translation.

The target thread of an IPC response will now wake up when responding.
IPC buffer translation is currently not implemented.
Error passing back to svcSendSyncRequest is currently not implemented.

cc @yuriks

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2793)

### CODE REVIEW

**Comment by yuriks** [comment]
I tested with a test homebrew I was writing and it seems to work ok, but it's hard to tell since there's no translation and, more importantly, SendSyncRequest doesn't block the caller yet or re-schedule properly yet, meaning that command buffers will always be garbage by the time the server thread gets to it.

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/hle/function_wrappers.h, line 83 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOPnpXIiPSEUsz-Zck:-KnOPnpXIiPSEUsz-Zcl:b-8k0jx3) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/function_wrappers.h#L83)):*
> ```objc
>         func(&param_1, (Kernel::Handle*)Memory::GetPointer(PARAM(1)), (s32)PARAM(2), PARAM(3)).raw;
> 
>     if (retval != RESULT_INVALID.raw) {
> ```

Am I missing something, or does `RESULT_INVALID` not seem to serve any purpose anymore? In that case you can probably get rid of this in WaitSynch1/N too.

---

*[src/core/hle/svc.cpp, line 405 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOLg4cHebxzTIl75rp:-KnOLg4cHebxzTIl75rq:b-5x7yox) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L405)):*
> ```cpp
>                                   Kernel::Handle reply_target) {
>     // Check if 'handles' is invalid
>     if (handles == nullptr)
> ```

Add a note here about this indeed having to be valid even if `handle_count` is 0.

---

*[src/core/hle/svc.cpp, line 412 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOLqHtoKNmrUO67VT5:-KnOLqHtoKNmrUO67VT6:b2efzwb) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L412)):*
> Kernel::SharedPtr

Drop the `Kernel::`, it's cleaner.

---

*[src/core/hle/svc.cpp, line 426 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOMz3oCDEB2wRbVhQX:-KnOMz3oCDEB2wRbVhQY:b-nzmogb) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L426)):*
> ```cpp
>     u32* cmd_buff = Kernel::GetCommandBuffer();
>     IPC::Header header{cmd_buff[0]};
>     if (reply_target && header.command_id != 0xFFFF) {
> ```

`reply_target != 0`

---

*[src/core/hle/svc.cpp, line 434 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnONljjpZDm7lyaJUCk:-KnONljjpZDm7lyaJUCl:b-kprn8y) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L434)):*
> ```cpp
> 
>         // Error out if there's no request thread or the session was closed.
>         if (!request_thread || session->parent->client == nullptr) {
> ```

`request_thread == nullptr`

---

*[src/core/hle/svc.cpp, line 434 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnONvevbccxBqBU7ru5:-KnONvewhmZ9KSBIXIaw:b-n23fpx) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L434)):*
> ```cpp
> 
>         // Error out if there's no request thread or the session was closed.
>         if (!request_thread || session->parent->client == nullptr) {
> ```

This seems like a good place to clean up the thread list if the session was closed.

---

*[src/core/hle/svc.cpp, line 442 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOO8KcQ5CgtuD5z0BE:-KnOO8KcQ5CgtuD5z0BF:b-2unqdf) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L442)):*
> ```cpp
> 
>         // Mark the request as "handled".
>         session->currently_handling = nullptr;
> ```

The move above happens to already set this to null, which will have different results if you fail due to `ERR_SESSION_CLOSED_BY_REMOTE` or during translation. Make sure to double-check your logic in that case.

---

*[src/core/hle/svc.cpp, line 451 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOOpItW-Nl3EbfKxKT:-KnOOpItW-Nl3EbfKxKU:b-2znip8) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L451)):*
> ```cpp
>         *index = 0;
>         // The kernel uses this value as a placeholder for the real error, and returns it when we
>         // pass no handles and we do not perform any reply.
> ```

"pass no handles and do not perform any reply."

---

*[src/core/hle/svc.cpp, line 452 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOOgRVhT8mKGIr_4Yw:-KnOOgRW3T6lkTl4s0zD:b-nk8fu7) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L452)):*
> ```cpp
>         // The kernel uses this value as a placeholder for the real error, and returns it when we
>         // pass no handles and we do not perform any reply.
>         if (!reply_target || header.command_id == 0xFFFF)
> ```

`reply_target == 0`

---

*[src/core/hle/kernel/server_session.cpp, line 43 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKPcmDuxKYPDGI-2D:-KnOKPcnM26BdtEtLV1q:b-chet23) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L43)):*
> ```cpp
>     // Closed sessions should never wait, an error will be returned from svcReplyAndReceive.
>     if (parent->client == nullptr)
>         return false;
> ```

Do we need to clean up `pending_threads` somewhere in this case? Otherwise `pending_threads` could hold references to dead threads, preventing their resources from being released.

---

*[src/core/hle/kernel/server_session.cpp, line 45 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOMv64hCQwtgEdDKCv:-KnOMv64hCQwtgEdDKCw:b96lu9i) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L45)):*
> ```cpp
>         return false;
>     // Wait if we have no pending requests, or if we're currently handling a request.
>     return pending_threads.empty() || currently_handling;
> ```

`currently_handling != nullptr`

---

*[src/core/hle/kernel/server_session.cpp, line 51 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKCiweoM-s04XrDV_:-KnOKCiweoM-s04XrDVa:b-u2e30o) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L51)):*
> ```cpp
>     ASSERT_MSG(!ShouldWait(thread), "object unavailable!");
>     // We are now handling a request, pop it from the stack.
>     currently_handling = pending_threads.back();
> ```

What happens if two threads try to Acquire on a server session? Seems like one of the pending replies will be permanently lost and hang the requesting thread.

---

*[src/core/hle/kernel/server_session.cpp, line 71 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJygJy1S6jPUjN9AT:-KnOJygJy1S6jPUjN9AU:bjtnfeq) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L71)):*
> GetCurrentThread()

Pass the thread in as a parameter instead.

---

*[src/core/hle/kernel/server_session.h, line 84 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJjEo2IJmEMGphnHl:-KnOJjEo2IJmEMGphnHm:befzeii) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L84)):*
> ```objc
> 
>     /// List of threads that are pending a response after a sync request.
>     /// This list is processed in a LIFO manner, thus, the last request will be dispatched first.
> ```

Word wrap paragraph properly.

---

*[src/core/hle/kernel/server_session.h, line 86 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJHbyTlEejV_FzP-p:-KnOJHbyTlEejV_FzP-q:bthi1su) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L86)):*
> ```objc
>     /// This list is processed in a LIFO manner, thus, the last request will be dispatched first.
>     /// TODO(Subv): Verify if this is indeed processed in LIFO using a hardware test.
>     std::vector<SharedPtr<Thread>> pending_threads;
> ```

I think `pending_requesting_threads` is a more descriptive name.

---

*[src/core/hle/kernel/server_session.h, line 89 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJguc4miwMU2qLOnW:-KnOJguc4miwMU2qLOnX:befzeii) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L89)):*
> ```objc
> 
>     /// Thread whose request is currently being handled.
>     /// A request is considered "handled" when a response is sent via svcReplyAndReceive.
> ```

Word wrap paragraph properly.

---

*[src/core/hle/kernel/server_session.h, line 91 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJMmlX_rji28Dhz8s:-KnOJMmlX_rji28Dhz8t:b7w2h5u) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L91)):*
> ```objc
>     /// A request is considered "handled" when a response is sent via svcReplyAndReceive.
>     /// TODO(Subv): Find a better name for this.
>     SharedPtr<Thread> currently_handling;
> ```

`thread_being_handled`, maybe? Not sure either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2793#-:-KnOS2rcliysG3_iUCRa:bpghyxt)*

**Comment by Subv** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/hle/function_wrappers.h, line 83 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOPnpXIiPSEUsz-Zck:-KnPO6FvFa8eEbu_2TYI:b-p5p3i0) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/function_wrappers.h#L83)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Am I missing something, or does `RESULT_INVALID` not seem to serve any purpose anymore? In that case you can probably get rid of this in WaitSynch1/N too.
</blockquote></details>

You're right, it's a leftover from old code, i'll remove it

---

*[src/core/hle/svc.cpp, line 434 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnONvevbccxBqBU7ru5:-KnPOGqiY6HLPH3vRZep:bj1kxhp) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L434)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

This seems like a good place to clean up the thread list if the session was closed.
</blockquote></details>

At this time it's already been popped from the pending_threads list (because Acquire was called)

---

*[src/core/hle/svc.cpp, line 442 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOO8KcQ5CgtuD5z0BE:-KnPOTCDnzvQYnIlfpAx:b8fy446) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L442)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

The move above happens to already set this to null, which will have different results if you fail due to `ERR_SESSION_CLOSED_BY_REMOTE` or during translation. Make sure to double-check your logic in that case.
</blockquote></details>

This line should be moved above the if check, I think explicitly setting it to nullptr shows intent better than hiding it behind move

---

*[src/core/hle/kernel/server_session.cpp, line 43 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKPcmDuxKYPDGI-2D:-KnPOfKfkBTqJpYGt140:b1npr42) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L43)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Do we need to clean up `pending_threads` somewhere in this case? Otherwise `pending_threads` could hold references to dead threads, preventing their resources from being released.
</blockquote></details>

ReplyAndReceive should still be signaled on dead threads, we can't clean up that list here, it'll be progressively cleaned up as the server thread goes through the ReplyAndReceive calls (where Acquire is called).

---

*[src/core/hle/kernel/server_session.cpp, line 51 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKCiweoM-s04XrDV_:-KnPP1XGwMok9ZKPRj7T:b-7ordg0) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L51)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

What happens if two threads try to Acquire on a server session? Seems like one of the pending replies will be permanently lost and hang the requesting thread.
</blockquote></details>

Currently if two threads do that, the !ShouldWait assert will fail and citra will crash :dancer: 

In reality this can not happen, because once a thread Acquires the session, "currently_handling" will be set to some thread and ShouldWait will become true, making any other threads wait before calling Acquire.

On the other hand, this sequence of events could hang one of the server threads:
Server: Thread A, Thread B, ServerSession X

Thread A calls ReplyAndReceive to receive request from X
Thread B calls ReplyAndReceive to receive request from X <- This waits because X->currently_handling is not nullptr.
Thread A calls ReplyAndReceive to reply to X <- This doesn't signal the ServerSession in the kernel.
Thread B never wakes up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2793)*

**Comment by Subv** [comment]
Review status: 0 of 5 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/hle/function_wrappers.h, line 83 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOPnpXIiPSEUsz-Zck:-KnQIQWYkn8lAZ-ZIza-:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/function_wrappers.h#L83)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

You're right, it's a leftover from old code, i'll remove it
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 405 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOLg4cHebxzTIl75rp:-KnQIZYjzucy2SDn8k7h:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L405)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Add a note here about this indeed having to be valid even if `handle_count` is 0.
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 412 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOLqHtoKNmrUO67VT5:-KnQIgHSDpb1Hruw3ojQ:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L412)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

> Kernel::SharedPtr

Drop the `Kernel::`, it's cleaner.

</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 426 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOMz3oCDEB2wRbVhQX:-KnQIib5X8ZPCPwNoIHZ:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L426)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

`reply_target != 0`
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 434 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnONljjpZDm7lyaJUCk:-KnQIo8QjphaLAywyz6p:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L434)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

`request_thread == nullptr`
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 442 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOO8KcQ5CgtuD5z0BE:-KnQIsKFS8swbqVtCTK8:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L442)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

This line should be moved above the if check, I think explicitly setting it to nullptr shows intent better than hiding it behind move
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 451 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOOpItW-Nl3EbfKxKT:-KnQIvCoIU7y2OyMaFCm:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L451)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

"pass no handles and do not perform any reply."
</blockquote></details>

Done.

---

*[src/core/hle/svc.cpp, line 452 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOOgRVhT8mKGIr_4Yw:-KnQIxYjLdlymKT3QOPX:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L452)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

`reply_target == 0`
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.cpp, line 45 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOMv64hCQwtgEdDKCv:-KnQJ24MWCalkfW1NrVe:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L45)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

`currently_handling != nullptr`
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.cpp, line 71 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJygJy1S6jPUjN9AT:-KnQJiPJm_DK6E9X5Zp4:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L71)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

> GetCurrentThread()

Pass the thread in as a parameter instead.
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.h, line 84 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJjEo2IJmEMGphnHl:-KnQK2vVBtGgezit3CuX:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L84)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Word wrap paragraph properly.
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.h, line 86 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJHbyTlEejV_FzP-p:-KnQJrhI1QYsNrYBeuIM:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L86)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

I think `pending_requesting_threads` is a more descriptive name.
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.h, line 89 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOJguc4miwMU2qLOnW:-KnQK3Yr71UNXeqeegMD:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.h#L89)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Word wrap paragraph properly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2793)*

**Comment by yuriks** [comment]
Reviewed 3 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/core/hle/svc.cpp, line 434 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnONvevbccxBqBU7ru5:-KnWmn7BWyMWd0gC130m:b-o3d79n) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/svc.cpp#L434)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

At this time it's already been popped from the pending_threads list (because Acquire was called)
</blockquote></details>

(Responding on the other related comment.)

---

*[src/core/hle/svc.cpp, line 403 at r7](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnWo_18bHyUuUtlY2UB:-KnWo_18bHyUuUtlY2UC:b-h4d3fo) ([raw file](https://github.com/citra-emu/citra/blob/34de8481424e8e895f08ededbb78177691c84454/src/core/hle/svc.cpp#L403)):*
> ```cpp
> /// In a single operation, sends a IPC reply and waits for a new request.
> static ResultCode ReplyAndReceive(s32* index, Kernel::Handle* handles, s32 handle_count,
>                                   Kernel::Handle reply_target) {
> ```

Do you plan on incorporating the fixed error codes you mentioned on IRC to this PR?

---

*[src/core/hle/kernel/client_session.cpp, line 42 at r7](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnRiBmN1EscPN-6YpDh:-KnRiBmN1EscPN-6YpDi:b-iruwo5) ([raw file](https://github.com/citra-emu/citra/blob/34de8481424e8e895f08ededbb78177691c84454/src/core/hle/kernel/client_session.cpp#L42)):*
> ```cpp
> 
>     // Signal the server session that new data is available
>     return server->HandleSyncRequest(GetCurrentThread());
> ```

If possible, also pass is in as a param here. SVC should be the only one calling GetCurrentThread() (keep proliferation of global state low when possible).

---

*[src/core/hle/kernel/server_session.cpp, line 43 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKPcmDuxKYPDGI-2D:-KnWn3BtqHk_WcyuCrvf:bhf7vrq) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L43)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

ReplyAndReceive should still be signaled on dead threads, we can't clean up that list here, it'll be progressively cleaned up as the server thread goes through the ReplyAndReceive calls (where Acquire is called).
</blockquote></details>

Acquire isn't currently called for threads you're not replying to. If this is something that needs to be implemented in the future then leave a comment stating so in the svc implementation above. Currently threads are only cleaned up if you try to reply to them.

---

*[src/core/hle/kernel/server_session.cpp, line 51 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKCiweoM-s04XrDV_:-KnWoIu-BzAlJSA7v0Qk:bn0z81v) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L51)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

Currently if two threads do that, the !ShouldWait assert will fail and citra will crash :dancer: 

In reality this can not happen, because once a thread Acquires the session, "currently_handling" will be set to some thread and ShouldWait will become true, making any other threads wait before calling Acquire.

On the other hand, this sequence of events could hang one of the server threads:
Server: Thread A, Thread B, ServerSession X

Thread A calls ReplyAndReceive to receive request from X
Thread B calls ReplyAndReceive to receive request from X <- This waits because X->currently_handling is not nullptr.
Thread A calls ReplyAndReceive to reply to X <- This doesn't signal the ServerSession in the kernel.
Thread B never wakes up
</blockquote></details>

To clarify, is this hanging you describe what would actually happen in the real kernel if you try to share a session? If so, then SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2793)*

**Comment by yuriks** [comment]
:lgtm: Apply fixups and stuff.

---

Reviewed 1 of 3 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/hle/svc.cpp, line 403 at r7](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnWo_18bHyUuUtlY2UB:-KnX61Bj7PJG6q7a2zFX:b6czevz) ([raw file](https://github.com/citra-emu/citra/blob/34de8481424e8e895f08ededbb78177691c84454/src/core/hle/svc.cpp#L403)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Do you plan on incorporating the fixed error codes you mentioned on IRC to this PR?
</blockquote></details>

Already done.

---

*[src/core/hle/kernel/server_session.cpp, line 43 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKPcmDuxKYPDGI-2D:-KnX6HwS9WMbZqfKRriU:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L43)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

Acquire isn't currently called for threads you're not replying to. If this is something that needs to be implemented in the future then leave a comment stating so in the svc implementation above. Currently threads are only cleaned up if you try to reply to them.
</blockquote></details>

Done.

---

*[src/core/hle/kernel/server_session.cpp, line 51 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2793#-KnOKCiweoM-s04XrDV_:-KnX6Jvx-Zao1d5bbxDk:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/c811e0ca433369e5b06d0786115105e83a093976/src/core/hle/kernel/server_session.cpp#L51)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

To clarify, is this hanging you describe what would actually happen in the real kernel if you try to share a session? If so, then SGTM.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2793#-:-KnX6LeoKZU0Xk_yCqfX:b-uwmdkx)*

**Pull request merged**
