### PR TITLE
HWRenderer/TextureCache: Flush the texture cache when bit 16 of register 0x80 is set to 1

### PR DESCRIPTION
**Pull request by Subv**
Taken from 3dbrew, this fixes a very old texture cache issue with Castle Conqueror (and probably more)

### CODE REVIEW

**Comment by neobrain** [comment]
What does our texture cache have to do with the PICA200's texture cache?

**Comment by yuriks** [comment]
Yeah, this seems like a misfix. Our texture cache doesn't mean the same thing as the PICA one. (We don't implement or need to worry about the PICA one. It has to be flushed every time you change textures after rendering.)

**Comment by Subv** [comment]
Castle Conqueror isn't issuing flush commands after changing the textures used for rendering, however it is writing to this register multiple times before triggering a draw again

**Comment by yuriks** [comment]
*Every* game will issue a write to this register after *every* texture pointer change. Flushing our texture cache here makes it essentially pointless.

**Pull request closed without merging**
