### PR TITLE
Renamed all .hxx headers to .h

### PR DESCRIPTION
**Pull request by chrisvj**

### CODE REVIEW

**Comment by neobrain** [comment]
Yay!

(Just a small hint for the future: If applicable, we usually try to prefix commit summaries with the respective module that the patch affects, so in this case the commit message should read "citra-qt: Renamed all .hxx headers to .h". It's not too important for this particular PR though)

LGTM.

**Comment by chrisvj** [comment]
Ah, alright. I'll make sure to do that in the future.

**Comment by bunnei** [comment]
Conflicts with your other PR, #406. Please fix, then I'll merge :)

**Comment by chrisvj** [comment]
Took some fumbling, new to using git w/ a team, pull requests, etc. Should be good now though.

**Comment by bunnei** [comment]
Thanks. Can you squash these to a single commit?

**Comment by chrisvj** [comment]
Done.

**Comment by bunnei** [comment]
LGTM. Thanks!

**Pull request merged**
