### PR TITLE
DSP/Interrupts: Keep track of the registered interrupts

### PR DESCRIPTION
**Pull request by Subv**
This is still a hack, but it's a bit better than just ignoring the previous interrupt events. It should allow some games to not freeze randomly.

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2015-12-27T17:54:49Z: https://github.com/citra-emu/citra/compare/031443199bf5df2fc1f840793b36b975a61a5596...Subv:36a0d5c66c86a2c8dc55dfcb9b34b62d960ffd0e

**Comment by Normmatt** [comment]
LGTM

**Comment by yuriks** [comment]
Ah, so this is where that map comes from. @MerryMage, is this PR completely deprecated by #1386? If not, can you include any relevant changes in it?

**Comment by MerryMage** [comment]
Updated #1386 to incorporate all changes.

**Comment by Subv** [comment]
As of #1386 being merged, this is no longer valid

**Pull request closed without merging**
