### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bladeoner**
Small change to the README.md

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5855)

### CODE REVIEW

**Review by bladeoner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/citra-emu/citra/5855#-:-MkBSk1_97NyCFf47b-U:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by bladeoner** [comment]
@SachinVin can you review my change please?

**Comment by SachinVin** [comment]
Hi @bladeoner, I assume this is for consistency... it would be helpful to mention _why_ the change is needed in the PR body.

**Comment by bladeoner** [comment]
Hi @SachinVin, exactly this small change is to make the README.md more consistent.

**Comment by SachinVin** [comment]
Thanks

**Pull request merged**
