### PR TITLE
dist/languages: Update current translations

### PR DESCRIPTION
**Pull request by Hexagon12**
Also adds two new languages: Danish and Polish.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3830)

### CODE REVIEW

**Comment by Hexagon12** [comment]
Updated the translations again. There's now 2 more languages available: Portuguese and Taiwanese.

**Comment by jroweboy** [comment]
@zhaowenlan1779 could you please check that the translations for chinese are good again?

**Comment by zhaowenlan1779** [comment]
Tested with canary-592.
It looks fine.
----- 原始邮件 -----
发件人：James Rowe <notifications@github.com>
收件人：citra-emu/citra <citra@noreply.github.com>
抄送人：朱鹏飞 <zhupengfei321@sina.cn>,  Mention <mention@noreply.github.com>
主题：Re: [citra-emu/citra] dist/languages: Update current translations (#3830)
日期：2018年06月27日 10点36分

@zhaowenlan1779 could you please check that the translations for chinese are good again?

&mdash;

**Comment by zhaowenlan1779** [comment]
@jroweboy 
Tested with Canary 592 and works fine.

**Pull request merged**
