### PR TITLE
Config: disable audio stretching by default

### PR DESCRIPTION
**Pull request by Adamillo**
The reason I propose this change is that time stretching has quite a few cons. For one, the latency is quite large and it's very noticeable. Second of all, the audio quality with time stretching is not very great when it's in full speed. Third of all the performance gets a small downgrade for the Android version according to the description of time stretch there

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6076)

### CODE REVIEW

**Comment by xperia64** [comment]
I support this for desktop, it's a little non-obvious why the audio quality is wonky when you're running a game at full speed.

Doesn't look like you changed the Android version [here](https://github.com/citra-emu/citra/blob/84d5d62cf59da7e001bad6b7298e45faac37fbeb/src/android/app/src/main/jni/config.cpp#L187) but Android devices are also more likely to chug so I think it's best to leave it enabled by default for Android.

**Comment by Adamillo** [comment]
Ah right. I wasn't sure where the config was stored for the Android version but I guess I could let it stay on there since as you said, the performance can chug on Android quite a lot

**Comment by vitor-k** [comment]
There's a few other places that need changing, like [here](https://github.com/citra-emu/citra/blob/357025dfdf2b08204b0a3ae38330dc5fe3f05103/src/citra/default_ini.h#L237) (Though it's just explanatory text) and [here](https://github.com/citra-emu/citra/blob/357025dfdf2b08204b0a3ae38330dc5fe3f05103/src/citra_qt/configuration/config.cpp#L114).
I don't really have an opinion on what should be the default though.

**Comment by SachinVin** [comment]
It shouldn't matter on android, we are disabling audio stretching [here](https://github.com/citra-emu/citra/blob/master/src/android/app/src/main/jni/native.cpp#L213-L226) if speed is over 95%.

**Comment by B3n30** [comment]
> It shouldn't matter on android, we are disabling audio stretching [here](https://github.com/citra-emu/citra/blob/master/src/android/app/src/main/jni/native.cpp#L213-L226) if speed is over 95%.

Wouldn't this be the better approach on desktop, too?

**Comment by SleepingSnakezzz** [comment]
So long as there's a definitive way to turn it off all together in the GUI settings, I agree with B3n30 there. Something like Dynamic, Off, and On options.

**Comment by Adamillo** [comment]
I agree, this should be also in the desktop version. I would like to implement this feature to the desktop version, but I sadly do not have the programming knowledge to implement this...

**Comment by Adamillo** [comment]
Are there any things left for me to do in order to get this PR into Nightly?

**Comment by GPUCode** [comment]
Untagging this for now due to conflicts, will readd shortly

**Comment by Steveice10** [comment]
Superceded by: https://github.com/citra-emu/citra/pull/7201

**Comment by Adamillo** [comment]
Thanks! This is a much better approach!

**Pull request closed without merging**
