### PR TITLE
Services/UDS: Handle beacon frames and the basic AP connection sequence frames.

### PR DESCRIPTION
**Pull request by Subv**
There is currently no connection stage tracking, a client is considered "Connected" when it receives the EAPoL Logoff packet from the server, this is not yet implemented.

The received beacon frames are stored in a circular buffer of 15 elements, where new elements displace the older ones.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2831)

### CODE REVIEW

**Comment by B3n30** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 747 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGIeZot0RbUboXGNdl:-KpGIeZot0RbUboXGNdm:bfn2rs2) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/nwm_uds.cpp#L747)):*
> ```cpp
>         return;
> 
>     // TODO(Subv): Actually send the beacon.
> ```

This TODO isn't needed anymore

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 39 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGJMmgr1tk-u5sEtyt:-KpGJMmgr1tk-u5sEtyu:b7i24tc) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/uds_connection.cpp#L39)):*
> ```cpp
>  */
> static std::vector<u8> GenerateSSIDTag(u32 network_id) {
>     constexpr u8 SSIDSize = 8;
> ```

SSID_size

---

*[src/core/hle/service/nwm/uds_connection.h, line 16 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGJqY08QXvvwiMYldG:-KpGJqY08QXvvwiMYldH:bhtv2r9) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/uds_connection.h#L16)):*
> ```objc
> 
> /// Sequence number of the 802.11 authentication frames.
> enum class AuthenticationSeq : u8 { SEQ1 = 1, SEQ2 = 2 };
> ```

Why u8 when you cast it to u16 in GenerateAuthenticationFrame

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831)*

**Comment by Subv** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 747 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGIeZot0RbUboXGNdl:-KpGN_hMl-e4E0Cw1WaB:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/nwm_uds.cpp#L747)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

This TODO isn't needed anymore
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/uds_connection.h, line 16 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGJqY08QXvvwiMYldG:-KpGNbFI69lwoDbWvUBb:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/uds_connection.h#L16)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

Why u8 when you cast it to u16 in GenerateAuthenticationFrame
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831)*

**Comment by B3n30** [comment]
Reviewed 4 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 39 at r4](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpGJMmgr1tk-u5sEtyt:-KpGOQt7xG2IR-G0SmWu:b32w0x) ([raw file](https://github.com/citra-emu/citra/blob/1ca3cd5fa99813fcf5e71fd56c353cc4a5219274/src/core/hle/service/nwm/uds_connection.cpp#L39)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

SSID_size
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831)*

**Comment by wwylele** [comment]
Reviewed 3 of 5 files at r1, 1 of 4 files at r5, 1 of 3 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 59 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpPyKJeAqtfvcOc81ai:-KpPyKJfTA_yYytZsaEL:b-52r70q) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/nwm_uds.cpp#L59)):*
> ```cpp
> // Mutex to synchronize access to the list of received beacons between the emulation thread and the
> // network thread.
> static std::mutex beacon_mutex;
> ```

[`SynchronizedWrapper`](https://github.com/citra-emu/citra/blob/master/src/common/synchronized_wrapper.h) can probably be used for this?

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 20 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6aIp-CYwAlru63ci:-KpQ6aIp-CYwAlru63cj:b-i97apr) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L20)):*
> ```cpp
> 
>     std::vector<u8> data(sizeof(frame));
>     memcpy(data.data(), &frame, sizeof(frame));
> ```

`std::memcpy`

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 27 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6_sEQ-7VFg9SNM-t:-KpQ6_sFoDpzuLG3SjlE:b-i97apr) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L27)):*
> ```cpp
> AuthenticationSeq GetAuthenticationSeqNumber(const std::vector<u8>& body) {
>     AuthenticationFrame frame;
>     memcpy(&frame, body.data(), sizeof(frame));
> ```

`std::memcpy`

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 51 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ8G8HdTcFIqyk2BR-:-KpQ8G8HdTcFIqyk2BR0:b-p4b5hb) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L51)):*
> ```cpp
> 
>     char network_name[SSIDSize + 1];
>     snprintf(network_name, SSIDSize + 1, "%08X", network_id);
> ```

use `Common::StringFromFormat` or the `fmt` library

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 53 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6WpAJh9iZJsQQt6T:-KpQ6WpBWAcxZ488dYAo:b-i97apr) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L53)):*
> ```cpp
>     snprintf(network_name, SSIDSize + 1, "%08X", network_id);
> 
>     memcpy(buffer.data() + sizeof(tag_header), network_name, SSIDSize);
> ```

`std::memcpy`

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 67 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6ZLkpplpI0xSnnXm:-KpQ6ZLkpplpI0xSnnXn:b-i97apr) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L67)):*
> ```cpp
> 
>     std::vector<u8> data(sizeof(frame));
>     memcpy(data.data(), &frame, sizeof(frame));
> ```

`std::memcpy`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831)*

**Comment by Subv** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 59 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpPyKJeAqtfvcOc81ai:-KsZMrFiEN0aZ39CuleU:b-f6xr2l) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/nwm_uds.cpp#L59)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

[`SynchronizedWrapper`](https://github.com/citra-emu/citra/blob/master/src/common/synchronized_wrapper.h) can probably be used for this?
</blockquote></details>

Given the amount of assignments we do from a single thread, that'd be a bit overkill.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 20 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6aIp-CYwAlru63ci:-KsZKTTWrlfvnvfwL-5L:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L20)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

`std::memcpy`
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 27 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6_sEQ-7VFg9SNM-t:-KsZKU7hgv5ChQs-P_n3:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L27)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

`std::memcpy`
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 51 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ8G8HdTcFIqyk2BR-:-KsZMSqfw5GbVeL4qxja:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L51)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

use `Common::StringFromFormat` or the `fmt` library
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 53 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6WpAJh9iZJsQQt6T:-KsZMTK2hCgRppidbxrC:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L53)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

`std::memcpy`
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/uds_connection.cpp, line 67 at r10](https://reviewable.io:443/reviews/citra-emu/citra/2831#-KpQ6ZLkpplpI0xSnnXm:-KsZMTmt_gAPdWqed0mQ:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/ac915ccd961db3fa9fcf579b33f23b6cbc4416ba/src/core/hle/service/nwm/uds_connection.cpp#L67)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

`std::memcpy`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831)*

**Comment by B3n30** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2831#-:-KsZPChJEz5d1HJ_PM5z:bnfp4nl)*

**Comment by wwylele** [comment]
From Discord:
> 
> wwylele / 白疾風 - Today at 2:27 PM
> B3N30 / Subv what to do with #2831 ?
> B3N30 - Today at 2:45 PM
> If you like merge it without the todo-comments. I'll fix it anyway
> Or wait till the Subv added the comments
> wwylele / 白疾風 - Today at 2:46 PM
> Yeah that's what I am asking... Can I expect Subv to fix it soon or you will take over most of the work
> B3N30 - Today at 2:59 PM
> It seems like he has no interest/time to fix that PR
> Any other PR will be submitted by me
> wwylele / 白疾風 - Today at 3:01 PM
> I'll take your word and merge it then
>

**Pull request merged**
