### PR TITLE
Remove dead platform #ifdefs to make the code more readable.

### PR DESCRIPTION
**Pull request by linkmauve**
Symbian, Xbox, Blackberry and iOS got removed; FreeBSD and Android kept due to them potentially being able to run Citra in the future.

### CODE REVIEW

**Comment by kevinhartman** [comment]
What makes iOS a dead platform?

**Comment by linkmauve** [comment]
Its inability to execute runtime-generated code makes it a dead platform for emulation, so it will always need a pure interpreter for everything.

**Comment by kevinhartman** [comment]
PPSSPP apparently uses JIT on jail-broken iOS (which you'd need anyway as a user to get an emulator). Check out the Porting PPSSPP section here: http://www.ppsspp.org/development.html

**Comment by linkmauve** [comment]
Do we really want to support a platform which every user would need to jailbreak?

**Comment by kevinhartman** [comment]
In either case, looks like in PPSSPP's mem arena the iOS stuff was removed (https://github.com/hrydgard/ppsspp/commit/a42c970a25a4c0a93459f73b7f7d264df68ba8a9).

**Comment by bunnei** [comment]
Hey, I have an iPhone! It's possible it could happen if PPSSPP does it :) Perhaps unlikely any time this year or next, though (I probably won't have the same phone anymore...)

**Comment by linkmauve** [comment]
Alright, I un-removed the iOS support, now only Symbian, Xbox and Blackberry are removed, which already cleans up a fair share of dead code.

**Comment by yuriks** [comment]
Wasn't the only iOS thing the memory map thing, which was removed by PPSSPP anyway?

**Comment by linkmauve** [comment]
Oh, indeed, it might make more sense to remove it as well then.  They apparently removed it to actually fix its support.

**Comment by linkmauve** [comment]
I removed the iOS part again, since its removal fixed an iOS issue in PPSSPP.

**Comment by yuriks** [comment]
Yay! LGTM

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
