### PR TITLE
Fix missing Mac builds by reverting #5317 and target 10.14

### LINKED ISSUE #5481: Updated Mac builds missing from Citra nightly and canary
When installing or updating Citra, I only have the options to download an outdated build of nightly and canary is entirely missing in the maintenance tool. The most recent available Mac build is nightly 1588.

### PR DESCRIPTION
**Pull request by GMaxera**
Fixes #5481

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5490)

### CODE REVIEW

**Comment by GMaxera** [comment]
@MerryMage My reasoning was that from one side your PR fixed crashed for Mac OS 10.13 but on the other hand it hits the timeout limits imposed by Travis. So, I thought that it's safer to increase the requirements to Mac OS 10.14 to avoid hitting Travis timeouts and running Citra on OS 10.13 ... at least till there is another alternative.

**Comment by GMaxera** [comment]
:-( It didn't work. It still needs more than 50 minutes to build :-(

**Comment by BreadFish64** [comment]
It's timing out because the build cache is broken and it can't regenerate because an uncached build will time out. So we're kinda stuck unless we can mess with Travis's cache.

**Comment by GMaxera** [comment]
:-( I'll close considering that I misunderstood the reason of failure :-(

**Pull request closed without merging**
