### PR TITLE
ncch_container: Assume override exheaders are decrypted

### PR DESCRIPTION
**Pull request by leoetlino**
Require and assume that override exheaders are decrypted for consistency with Luma's loader and to ensure consistent behaviour regardless of whether the NCCH is marked as encrypted or not.

Currently, exheader overriding with an encrypted NCCH would cause the title ID checking heuristic to mistakenly disable encryption, which would then make exefs loading fail.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4862)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
On a second thought, it would be great to add a check there as well to ensure decrypted exheader replacement.

**Comment by leoetlino** [comment]
Hmm, what check do you think should be added? Some sanity check like checking that the program ID and jump ID in the exheader match?

**Comment by zhaowenlan1779** [comment]
Yes, exactly what I meant.

**Comment by leoetlino** [comment]
Done, added a warning if the IDs don't match

**Comment by leoetlino** [comment]
Fixed the lint issue; thought there'd be an IRC notification for failing builds so I missed the lint failure

**Comment by leoetlino** [comment]
Build failure appears to be unrelated.

**Comment by zhaowenlan1779** [comment]
I'll merge this soon if no more comments.

**Pull request merged**
