### PR TITLE
Service/CECD: Stub OpenAndRead & Migrate logging macros

### LINKED ISSUE #2238: Kid Icarus Uprising - Hangs after saving
Tested on https://github.com/citra-emu/citra/commit/cf5b8483fc53ca3b4919d231045348625a507d05 .

First boot [LOG](http://pastebin.com/9ZJ67fTv)

bottom screen is clickable:
kid 1

Second boot [LOG](http://pastebin.com/MqP7ji78)

screen:
kid 2

After saving spams with:
```
[ 138.420488] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:74: unknown / unimplemented function 'ReadSavedData': port=cecd:u, cmd_buff[1]=0x60, cmd_buff[2]=0x30000, cmd_buff[3]=0x2, cmd_buff[4]=0x12, cmd_buff[5]=0x20, cmd_buff[6]=0x0, cmd_buff[7]=0x60C, cmd_buff[8]=0xE014D28
[ 138.420979] Service.NDM <Warning> core\hle\service\ndm\ndm.cpp:Service::NDM::ResumeDaemons:102: (STUBBED) daemon_bit_mask=0x0000000F
```

### LINKED ISSUE #2475: Tomodachi Life hangs after creating savedata
Tested on 
https://github.com/citra-emu/citra/commit/f8523699864b6000572affaa0e36d9a4d89ffce6

Log:
http://pastebin.com/a5un6HsB

### PR DESCRIPTION
**Pull request by valentinvanelslande**
Fixes #2238
Fixes #2475

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3583)

### CODE REVIEW

**Comment by Dragios** [comment]
It has been rejected in PR #3344 and you still continue to create the same PR? Did you bother to read through PR history?

**Comment by mailwl** [comment]
@wwylele has a pretty nice inmplementation of cec: https://github.com/wwylele/citra/tree/cec
i think, porting it to fresh citra enough to close issues about cecd

**Comment by FearlessTobi** [comment]
@mailwl His implementation isn't finished nor working 100% correctly. My PR actually used code from his branch and still got rejected. The consensus was: "If you didn't do any RE work, expect your PR to be closed".

**Comment by jroweboy** [comment]
I'm just going off past precedent when I say this: "Stubbing CEC is not acceptable" Thank you for your contribution, and I'd really love to see a full implementation of CEC someday 👍

**Pull request closed without merging**
