### PR TITLE
Updated some module's FunctionTable from 3dbrez,no function changed!

### PR DESCRIPTION
**Pull request by JamePeng**

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-02-08T19:26:19Z: https://github.com/citra-emu/citra/compare/f1d1049c4fdf51fd382f9afb6b5cd5f104e71b0e...JamePeng:1d86878be4e5a156656a10535678d20d5e6f329c

**Comment by Subv** [comment]
Huh, why is the diff so big?

**Comment by Dazzozo** [comment]
Looks like someone changed all the line endings and indentation. :P

**Comment by MerryMage** [comment]
Regarding the use of tabs: [Whitespace is prefered](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md#indentationwhitespace-style).

**Comment by JamePeng** [comment]
Maybe I broke some line endings and indentation !

**Comment by JamePeng** [comment]
Please close it! I will do it again!

**Comment by JamePeng** [comment]
I try to do it well

**Comment by JamePeng** [comment]
Please close this request! thank admin! @Subv @neobrain

**Pull request closed without merging**
