### PR TITLE
CFG: move language override to the boot process

### PR DESCRIPTION
**Pull request by wwylele**
Previously in #2240 I added a language overriding in `GetConfigInfoBlock`, which happens when the region setting is auto. This causes a small problem because `GetConfigInfoBlock` is also used by the Qt frontend to checkout the current settings. The symptom is that the configuration dialog will always shows "Japanese" as language if the region is auto, in spite of the actual language settings. ~~Now I moved this overriding into the service functions, so that it only happens when the game reads it.~~ Now I moved this overriding to the boot process, so that it won't happens when users edit the system settings. It will still affect if users open the configuration window while a game is running, but it doesn't matter and actually tells users that the language is changed.

### CODE REVIEW

**Comment by yuriks** [comment]
Hm, rather than keep doing this, I think it'd be cleaner to have the boot process set the language if automatic region detection is enabled. That way the functions don't need to be modified at all. Are there any problems with that approach?

**Comment by wwylele** [comment]
Did what @yuriks suggested.

**Comment by yuriks** [comment]
Doesn't the current version always override the language, even if auto-region isn't enabled? I think that we should probably warn about this in the UI, but should let the user do it anyway, in case someone wants to experiment or find unused content in games, etc.

**Comment by wwylele** [comment]
>Doesn't the current version always override the language, even if auto-region isn't enabled?

My fault. I forgot to wrap it with the condition. Fixed

**Pull request merged**
