### PR TITLE
Services/AM: Add errors and adjust naming for accuracy

### PR DESCRIPTION
**Pull request by shinyquagsire23**
This PR can be reviewed commit-by-commit.

This PR renames three functions which require DLC TIDs and adds appropriate errors for when non-DLC TIDs are passed to them. Mapped buffers are passed back as appropriate. Some previous warnings have also been fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3087)

### CODE REVIEW

**Comment by Subv** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/core/hle/service/am/am.cpp, line 688 at r1](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ1SykZ-N_kA_0y5lv:-KyJ1SylMc4lIRoj6XGP:bf3qcnr) ([raw file](https://github.com/citra-emu/citra/blob/f5cb66d34ac9113871faf4214397c5fa556c71c7/src/core/hle/service/am/am.cpp#L688)):*
> ```cpp
>         rb.Push<u32>(1); // Number of content infos plus one
>         LOG_WARNING(Service_AM, "(STUBBED) called media_type=%u, title_id=0x%016" PRIx64,
>                     static_cast<u8>(media_type), title_id);
> ```

shouldn't you be casting these to u32?

---

*[src/core/hle/service/am/am.cpp, line 423 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ2iCOnUrROtEJvkXk:-KyJ2iCOnUrROtEJvkXl:bekdtwo) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L423)):*
> ```cpp
>                             ErrorSummary::InvalidArgument, ErrorLevel::Usage);
>         IPC::RequestBuilder rb = rp.MakeBuilder(1, 4);
>         rb.Push(result);
> ```

you can just build the ResultCode inside the Push call

---

*[src/core/hle/service/am/am.cpp, line 460 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ2kTXVIcp5IBGFjOu:-KyJ2kTXVIcp5IBGFjOv:b9ewvq) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L460)):*
> ```cpp
> 
>     IPC::RequestBuilder rb = rp.MakeBuilder(1, 4);
>     rb.Push(result);
> ```

you can use RESULT_SUCCESS here directly

---

*[src/core/hle/service/am/am.cpp, line 468 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ2ug9DqKvtzJf_T8F:-KyJ2ug9DqKvtzJf_T8G:bgwt9gv) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L468)):*
> ```cpp
>     IPC::RequestParser rp(Kernel::GetCommandBuffer(), 0x1003, 5, 2); // 0x10030142
> 
>     ResultCode result = RESULT_SUCCESS;
> ```

same. Why are you using this variable anyways?

---

*[src/core/hle/service/am/am.cpp, line 719 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ3-P1auyo3e6jqkQJ:-KyJ3-P2KFf5ZqQ88SzC:b-mszor9) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L719)):*
> ```cpp
>                                  ErrorSummary::InvalidArgument, ErrorLevel::Usage);
>         IPC::RequestBuilder rb = rp.MakeBuilder(2, 2);
>         rb.Push(result);
> ```

construct the ResultCode directly in the Push call

---

*[src/core/hle/service/am/am.cpp, line 843 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ32SKKrD0NWWWNTFZ:-KyJ32SKKrD0NWWWNTF_:bb7od0r) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L843)):*
> ```cpp
>             .Unwrap());
> 
>     LOG_WARNING(Service_AM, "(STUBBED) media_type=%u", static_cast<u8>(media_type));
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/3087)*

**Comment by Dragios** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/hle/service/am/am_sys.cpp, line 57 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ8Om0HTqHdggk5TDA:-KyJ8Om1A9bC0678Ztr8:b-kldelo) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am_sys.cpp#L57)):*
> ```cpp
>     {0x002C0084, nullptr, "GetProgramInfosIgnorePlatform"},
>     {0x002D00C0, CheckContentRightsIgnorePlatform, "CheckContentRightsIgnorePlatform"},
>     {0x100100C0, GetDLCContentInfoCount, "GetNumContentInfos"},
> ```

Did you forget to rename this text string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/3087)*

**Comment by shinyquagsire23** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/hle/service/am/am.cpp, line 468 at r2](https://reviewable.io:443/reviews/citra-emu/citra/3087#-KyJ2ug9DqKvtzJf_T8F:-KyJiquumAPTQ_NaHvcZ:b-mwy0kf) ([raw file](https://github.com/citra-emu/citra/blob/5193bc5a99d1437d784bac2ff8884ba6d63be16c/src/core/hle/service/am/am.cpp#L468)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

same. Why are you using this variable anyways?
</blockquote></details>

Was more for any additional errors, but apparently I've hit all errors up to pxi:am9, so I'll have to dig deeper into Process9 later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/3087)*

**Comment by Subv** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/3087#-:-KyJmn0QbMqDd7dh0hgE:bnfp4nl)*

**Pull request merged**
