### PR TITLE
Android: Target Latest SDK Version

### PR DESCRIPTION
**Pull request by greggameplayer**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4590)

### CODE REVIEW

**Comment by wwylele** [comment]
Why

**Comment by greggameplayer** [comment]
@wwylele Because it's better to support the latest versions in order to avoid bugs and problems

**Comment by FearlessTobi** [comment]
We will maybe consider this if you show us just one place where this will improve the app for the end user. I'm not sure you understand how android development works, but the sdk ver isn't necessarily related to bug or security fixes. All this does is leading to potential situations where we accidentally use a feature from a newer sdk version and lock out a substantial part of our userbase.

**Comment by greggameplayer** [comment]
@FearlessTobi so i close it for now

**Pull request closed without merging**
