### PR TITLE
Changed FAQ link

### PR DESCRIPTION
**Pull request by 3dsemu**
I changed the FAQ link so it leads to the FAQ on the Citra website, instead of the FAQ hosted
on GitHub. I'm not really sure if this is necessary, but I did it just in case.

### CODE REVIEW

**Comment by 3dsemu** [comment]
If you don't believe this is necessary, tell me and I will close this PR.,

**Comment by freiro** [comment]
I suppose that uniforming everything under citra's domain is better.
LGTM

**Comment by chris062689** [comment]
LGTM

**Comment by 3dsemu** [comment]
I'm still waiting for someone to merge this. If you think this change is necessary, please merge this.

**Pull request merged**
