### PR TITLE
Implement Mii Selector & Minor swkbd changes

### LINKED ISSUE #3743: Super Mario 3D Land: Save File not recognized, but still loads correctly
I'm running Canary HEAD-4687EE7, and when I boot the game with a previous save file, it sees none in the load menu.

image

In this case, slot A is where the save data is located. When slot A is selected, it takes you through the process of creating a new save file in that slot.

However when the game is loaded, it's not a new game. It is indeed loads the game in its previously saved state.

image

I'm attaching the log to this issue.
[citra_log.txt](https://github.com/citra-emu/citra/files/1998714/citra_log.txt)

### PR DESCRIPTION
**Pull request by valentinvanelslande**
Changes:
- Move buttons text to a separate file
- Move ptm_shared_extdata_id to header
- Minor swkbd changes
- Implement Mii Selector

Default Implementation: Mii from #4279 is always returned.

Qt Implementation: Reads Mii database. Shows message if no Miis were found

[Video](https://streamable.com/14lmm)
Screenshot:
miiselector

Guest Miis are not supported because they are copyrighted.

Fixes #3743

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4345)

### CODE REVIEW

**Comment by wwylele** [comment]
Please split your commits according to your bullet points in the description.

**Comment by chris062689** [comment]
How does this change effect SDL? Is there an SDL parameter to specify their Mii?

**Comment by FearlessTobi** [comment]
if the user doesn't have a mii yet, can't we just return "the standard mii" that's also returned for SDL?

**Comment by valentinvanelslande** [comment]
@chris062689 for SDL, Mii from #4279 is always returned, there's no parameter.
@FearlessTobi a 3DS shows this message if the user doesn't have a Mii:
nomii

**Comment by FearlessTobi** [comment]
I don't think this preferable for Citra though? Does anyone else have an opinion on this?

**Comment by chris062689** [comment]
If the user doesn't have a Mii, I think providing them a basic one by default is preferred.

**Comment by valentinvanelslande** [comment]
i messed up with my branch. someone can open a new PR with the comments addressed.

**Pull request closed without merging**
