### PR TITLE
Frontends, HID: Add New 3DS specific pad buttons, and stub the touch one.

### PR DESCRIPTION
**Pull request by linkmauve**
I used ctrulib’s input example to make sure it was correct.

### CODE REVIEW

**Comment by purpasmart96** [comment]
Nice!

**Comment by archshift** [comment]
Didn't add it to `[default_ini.h](https://github.com/citra-emu/citra/blob/master/src/citra/default_ini.h)`?

**Comment by linkmauve** [comment]
Oops, I forgot this place, I hope it was the only one.  I did grep for a few keys though…

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
