### PR TITLE
Dyncom: Don't exit on user mode

### PR DESCRIPTION
**Pull request by SeannyM**
I noticed armemu was removed, so I decided to submit this. The only thing I found that worked with armemu but not dyncom was Pokemon Mystery Dungeon Gates To Infinity. It may not work well, but it gets somewhat into the loading screen, and I'm sure it can get farther once more functions are implemented. Simply not exiting for user mode allows the game to run on dyncom just as it did on armemu. Obviously this exit was put there for a reason, however if removing it increases compatability, I think it makes sense. There isn't much here to review, but I won't be able to respond to any comments for about a week. I'm about to leave on vacation, and I doubt I'll find wifi. I just decided to submit this before I left as I planned on doing so once armemu was removed anyways.

### CODE REVIEW

**Comment by Subv** [comment]
That log is very misleading, what this code path does is exit if some application tried to load 0 as the CPU mode, this is a current bug with Pokemon Mystery Dungeon Gates To Infinity.

This patch is not the way to fix it.

**Comment by lioncash** [comment]
Agreeing with @Subv here.

**Comment by SeannyM** [comment]
This is why I wish I knew more about this stuff than I do :P We could at least change the log, or maybe implement some kind of workaround? It still runs fine, at least as far as it does run, by simply removing the exit.

**Comment by lioncash** [comment]
Definitely not a workaround. This is something that gets fixed the correct way.

**Comment by SeannyM** [comment]
Completely understandable. I'll take my programming course next semester and maybe get back to you ;)

**Pull request closed without merging**
