### PR TITLE
Implement function APT::ReplySleepQuery() and Correct APT::AppletUtility

### PR DESCRIPTION
**Pull request by JamePeng**
Implement function ReplySleepQuery
Update the APT FunctionTable
Correct APT::AppletUtility Parameter and comment

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-02-10T21:03:21Z: https://github.com/citra-emu/citra/compare/f1d1049c4fdf51fd382f9afb6b5cd5f104e71b0e...JamePeng:db3b2226dfddd08e36b74b443a6d7d678212e283

**Comment by lioncash** [comment]
This should only have the commit for ReplySleepQuery in it.

**Comment by JamePeng** [comment]
But this request Only for the APT file!  I need the header file，so …………

**Comment by JamePeng** [comment]
@lioncash But this request Only for the APT file! 
Otherwise I need the header file，so …………

**Comment by lioncash** [comment]
Right, so you should only have the prototype for ReplySleepQuery in the header file and the implementation of ReplySleepQuery in the cpp file.

You already have a PR open for ListDataTitleTicketInfos(), Including those commits for it is unnecessary.

**Comment by JamePeng** [comment]
@lioncash
As a newbie student，please forgive my mistake tonight :p :p
（But we have a same dream：Make the citra perfect day by day！Right？）

**Comment by lioncash** [comment]
I never held it against you anyways, things happen.

Please fix the unnecessary commits however. This can be fixed with a `git rebase`

**Comment by JamePeng** [comment]
@lioncash
like this？？？？？？？
git checkout main
git rebase <branch name>

**Comment by MerryMage** [comment]
@JamePeng

In order to have a tidy log, you can squash(合併) several commits together. One way to do this is with `git rebase`.

Links to guides:
en: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
zh: http://zerodie.github.io/blog/2012/01/19/git-rebase-i/

**Comment by JamePeng** [comment]
@MerryMage  Thanks for your advice, I think it was very helpful！

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-02-11T07:52:14Z: https://github.com/citra-emu/citra/compare/f1d1049c4fdf51fd382f9afb6b5cd5f104e71b0e...JamePeng:69ca50645eb30c9fb6152f7542cddd4d9fccef2b

**Pull request closed without merging**
