### PR TITLE
Service/CFG: Add block 0x000A0000 (username) to default config file

### PR DESCRIPTION
**Pull request by yuriks**
Fixes missing block issue in #1129.

### CODE REVIEW

**Comment by yuriks** [comment]
@Romsstar: Check if this PR fixes that specific issue with Digimon. Make sure to delete the existing config savefile so that Citra re-creates it.

**Comment by Romsstar** [comment]
This PR fixes the config savefile issue in #1129 completely. 
The other problems still persist.

**Comment by Subv** [comment]
:shipit: LGTM

**Comment by JamePeng** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM

**Comment by wwylele** [comment]
I get confused... apparently there is already a name block, what's the point to create another one?

**Pull request merged**
