### PR TITLE
arm_dyncom_thumb: Implement missing instructions.

### PR DESCRIPTION
**Pull request by lioncash**
The pretty cool thing about these not being implemented is that you'd get junk loads and stores whenever they were used in thumb mode :^)

### CODE REVIEW

**Comment by bunnei** [comment]
Looks fine to me. Out of curiosity, how complete is our thumb emulation?

**Comment by lioncash** [comment]
That's all the unimplemented instructions as far as ARMv6K compatibility is concerned.

**Comment by Subv** [comment]
LGTM

**Comment by lioncash** [comment]
Just minor changes to comments (removing "T1" since it's confusing to refer to A1 bases with that relative to what's being decoded). Will merge once build is green.

**Pull request merged**
