### PR TITLE
Services/UDS: Set the proper bit in the ConnectionStatus structure when creating a network.

### PR DESCRIPTION
**Pull request by Subv**
This lets the application know that the host was successfully added to the session.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2738)

### CODE REVIEW

**Comment by B3n30** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/nwm_uds.h, line 54 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2738#-KlKrkwM5taOfntP33ch:-KlKrkwM5taOfntP33ci:b-bci2h5) ([raw file](https://github.com/citra-emu/citra/blob/4a9d3abee2480b72df03573fe57e4420bed56724/src/core/hle/service/nwm/nwm_uds.h#L54)):*
> ```objc
>     u16_le network_node_id;
>     u16_le changed_nodes;
>     u16_le nodes[UDSMaxNodes];
> ```

Shouldn't those get initialized/cleared at some point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2738)*

**Comment by Subv** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/nwm_uds.h, line 54 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2738#-KlKrkwM5taOfntP33ch:-Klo50iG6LZkUXn5OIQU:bm2srkt) ([raw file](https://github.com/citra-emu/citra/blob/4a9d3abee2480b72df03573fe57e4420bed56724/src/core/hle/service/nwm/nwm_uds.h#L54)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

Shouldn't those get initialized/cleared at some point?
</blockquote></details>

They are zero-initialized every time ConnectionStatus is set to {}, do you have a specific place in mind?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2738)*

**Comment by B3n30** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/hle/service/nwm/nwm_uds.h, line 54 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2738#-KlKrkwM5taOfntP33ch:-KloIQibA4uZj2tPJ2uh:b-b0mpuj) ([raw file](https://github.com/citra-emu/citra/blob/4a9d3abee2480b72df03573fe57e4420bed56724/src/core/hle/service/nwm/nwm_uds.h#L54)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

They are zero-initialized every time ConnectionStatus is set to {}, do you have a specific place in mind?
</blockquote></details>

At least the one from nodes[] should be removed at DestroyNetwork(). Otherwise any old data can remain in the array and could cause errors/confusion if at a later stage we add ConnectToNetwork(), which won't initialize it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2738)*

**Comment by B3n30** [comment]
It's fine for me: LGTM

**Pull request merged**
