### PR TITLE
Minor Menu Fixes

### PR DESCRIPTION
**Pull request by Pringo**
Fix capitalization and spacing in menu.

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-09-17T19:08:24Z: https://github.com/citra-emu/citra/compare/8bf09b5302dc7717477f6c3b5c1f0ea8f2c80717...Pringo:ff98bd30b4cc175ed3952a11c106f60566fe6775

**Comment by Subv** [comment]
LGTM

**Comment by yuriks** [comment]
LGTM. Blocking on #2086

**Comment by wwylele** [comment]
@Pringo Sorry for the format change in #2086. Could you please rebase it to solve the conflict?

**Comment by Pringo** [comment]
Sorry, I did this with the web interface and I don't think I can rebase. I will close this PR and re-submit a fixed version.

**Pull request closed without merging**
