### PR TITLE
Proper naming

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by jroweboy** [comment]
Need to update the CMakeFile as well I believe. https://github.com/citra-emu/citra/blob/master/CMakeLists.txt#L261

**Comment by AlmariJosh** [comment]
@wwylele don't limit me and locked me on replying ok?? Just tell me if you don't want to answer that question!!

**Comment by Lord-Haji** [comment]
Chexked the whole repo therr r no other places needed to change

**Comment by bunnei** [comment]
Sorry, why does this need to be changed? Please add descriptions to your PRs.

**Comment by Lord-Haji** [comment]
Ehh?? For proper and convenient naming

**Comment by wwylele** [comment]
@Lord-Haji It is neither proper nor convenient IMO. Although I don't know what the file is exactly (not so familiar with Linux), but this renaming gives me an even worse picture of the file.

It is not convenient, because as I see, the file contains several mime types information that citra uses, instead of encoding of citra or something. The word "encoding" tends to mislead developers and users.

It is not proper, for other similar files I found in my PC are not named as `xxx-encoding.xml` format, but most of them are bare application name or type name. I don't know if there is a rule or convention for these, but this renaming doesn't seem to fit in other files I've seen.

**Comment by JayFoxRox** [comment]
If there is a convention we should follow please add it to this discussion.
I'll close this now. There is no point having 6 participants discussing a +1 -1 line change.

**Pull request closed without merging**
