### PR TITLE
Dyncom/VFP: Convert denormal outputs into 0 when the FTZ flag is enabled.

### LINKED ISSUE #1990: VFP: Incorrect FTZ behaviour
Skyeye does not seem to perform FTZ on outputs at all. DAZ on inputs however does occur.

Assembly Code:

```
@ This test program adds two numbers that produces a denormal
.text
.arm
.align 4

.global test1
.type test1, %function
test1:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x81784441
    vmov.f32 s1, r0
    ldr r0, =0x0142e1d7
    vmov.f32 s18, r0
    vadd.f32 s14, s1, s18
    vmov.f32 r0, s14
    bx lr

.global test2
.type test2, %function
test2:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x81784441
    vmov.f32 s1, r0
    ldr r0, =0x0142e1d7
    vmov.f32 s18, r0
    vadd.f32 s14, s1, s18
    vmrs r0, fpscr
    bx lr

.global test3
.type test3, %function
test3:
    ldr r0, =0x01000000
    vmsr fpscr, r0
    ldr r0, =0x806ac4d4
    vmov.f32 s2, r0
    ldr r0, =0x00000000
    vmov.f32 s3, r0
    vadd.f32 s0, s2, s3
    vmov.f32 r0, s0
    bx lr
```

Citra output:

```
test1: 0x806ac4d4 *
test2: 0x01000000 *
test3: 0x00000000
```

Hardware output:

```
test1: 0x00000000 *
test2: 0x01000008 *
test3: 0x00000000
```

### PR DESCRIPTION
**Pull request by Subv**
closes #1990

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2692)

### CODE REVIEW

**Comment by yuriks** [comment]
-pr:needs-review +pr:needs-work 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/arm/skyeye_common/vfp/vfpdouble.cpp, line 143 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-KjkZrG2DkZNcI83-uIy:-KjkZrG2DkZNcI83-uIz:b5lcorn) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L143)):*
> ```cpp
>         if ((type & VFP_DENORMAL) && (fpscr & FPSCR_FLUSH_TO_ZERO)) {
>             // Flush denormal to positive 0
>             exponent = 0;
> ```

`exponent` is always set to 0 above already

---

*[src/core/arm/skyeye_common/vfp/vfpdouble.cpp, line 148 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-KjkZfSAkkVxnv-_bHYQ:-KjkZfSAkkVxnv-_bHYR:bbwi8ue) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L148)):*
> ```cpp
>             vd->sign = 0;
>             vd->exponent = exponent;
>             vd->significand = significand;
> ```

It looks like you could move the block above (that's wrapped in `#if 1`) below this if to avoid these redundant assignments.

---

*[src/core/arm/skyeye_common/vfp/vfpsingle.cpp, line 146 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-Kjk_31YD7SGAKfvx_d7:-Kjk_31ZxslnGkXv3pJr:brfn46l) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpsingle.cpp#L146)):*
> ```cpp
>         if ((type & VFP_DENORMAL) && (fpscr & FPSCR_FLUSH_TO_ZERO)) {
>             // Flush denormal to positive 0
>             exponent = 0;
> ```

Same deal.

---

*[src/core/arm/skyeye_common/vfp/vfpsingle.cpp, line 151 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-Kjk_46XYED_1qwz1lB5:-Kjk_46XYED_1qwz1lB6:brfn46l) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpsingle.cpp#L151)):*
> ```cpp
>             vs->sign = 0;
>             vs->exponent = exponent;
>             vs->significand = significand;
> ```

Same deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2692#-:-Kjk_6MuK-X2lj3GeAZA:bgixoqy)*

**Comment by Subv** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/arm/skyeye_common/vfp/vfpdouble.cpp, line 148 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-KjkZfSAkkVxnv-_bHYQ:-KkhRG0kCTuReAf-fIyy:btyk9gt) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L148)):*
<details><summary><i>Previously, yuriks (Yuri Kunde Schlesner) wrote…</i></summary><blockquote>

It looks like you could move the block above (that's wrapped in `#if 1`) below this if to avoid these redundant assignments.
</blockquote></details>

I need vd to have the newly calculated significand so vfp_double_type can correctly determine if it's denormal or not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2692)*

**Comment by yuriks** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/arm/skyeye_common/vfp/vfpdouble.cpp, line 148 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2692#-KjkZfSAkkVxnv-_bHYQ:-KkibxsrlHROeAUzwPCV:bbtn5u6) ([raw file](https://github.com/citra-emu/citra/blob/b1a29371c9955a79bb9353043532316516512334/src/core/arm/skyeye_common/vfp/vfpdouble.cpp#L148)):*
<details><summary><i>Previously, Subv (Sebastian Valle) wrote…</i></summary><blockquote>

I need vd to have the newly calculated significand so vfp_double_type can correctly determine if it's denormal or not
</blockquote></details>

Ok, I missed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2692#-:-KkicFo-cM4RET9tffAB:bnfp4nl)*

**Comment by MerryMage** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2692#-:-KkjmxBuqHdcxxa8amh7:bnfp4nl)*

**Pull request merged**
