### PR TITLE
shader: Fix address register offset behavior in x64 Jit

### PR DESCRIPTION
**Pull request by GPUCode**
Same fix as https://github.com/citra-emu/citra/pull/6910 and https://github.com/citra-emu/citra/pull/6920 but the shader JIT.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6942)

### CODE REVIEW

**Comment by SachinVin** [comment]
Please add unit tests

**Comment by Steveice10** [comment]
Tested with the same hardware tests as before and looks correct.

**Comment by SachinVin** [comment]
Unit tests are also useful to weed out future regressions.

Also side note, the is some (future) optimisation potential if you move unlikely branches to "far code", so the hot code isn't flushed from the pipeline.

**Comment by Steveice10** [comment]
> Unit tests are also useful to weed out future regressions.

I agree, this wasn't a reply to you just a general acknowledgement that I've made sure this works correctly.

**Comment by SachinVin** [comment]
Sorry, my bad

**Comment by GPUCode** [comment]
Note to self: Don't merge this until unit tests are written. Can add both c0 and c40 bases as the original hwtests

**Comment by Wunkolo** [comment]
Bumping this as having unit tests would be super useful for verifying an arm64 implementation over in https://github.com/citra-emu/citra/pull/7002

**Comment by GPUCode** [comment]
Thanks for the reminder, I should be able to complete this in the next few days

**Comment by GPUCode** [comment]
Added test case based on the c40 hwtest. Should cover for all/most cases

**Comment by Wunkolo** [comment]
You might need a Catch-stringifier somewhere too so that the asserts have actual info in them.

```
-------------------------------------------------------------------------------
Address Register Offset
-------------------------------------------------------------------------------
...
...............................................................................

...FAILED:
  REQUIRE( shader.Run(13.f) == f_uniforms[53] )
with expansion:
  {?} == {?}
```

Something like:
```
namespace Catch {
template <>
struct StringMaker<Common::Vec4f> {
    static std::string convert(Common::Vec4f value) {
        return fmt::format("{}, {}, {}, {}", value.r(), value.g(), value.b(), value.a());
    }
};
} // namespace Catch
```
```
-------------------------------------------------------------------------------
Address Register Offset
-------------------------------------------------------------------------------
...
...............................................................................

...
FAILED:
  REQUIRE( shader.Run(13.f) == f_uniforms[53] )
with expansion:
  (0.4392157, 0.4392157, 0.4392157, 1)
  ==
  (0.3372549, 0.3372549, 0.3372549, 1)
```

**Comment by Wunkolo** [comment]
I think you don't have to do these shifts anymore now either.

https://github.com/citra-emu/citra/blob/c36679ecf0b831631b39d74d0101f458ef35304b/src/video_core/shader/shader_jit_x64_compiler.cpp#L676-L677

**Comment by GPUCode** [comment]
Added the stringifier for the vector types and fixed up some additional premultiplications by 16 for the LOOPCOUNT register (thanks @Wunkolo!)

**Review by FearlessTobi — APPROVED** [review]

**Pull request merged**
