### PR TITLE
Service/NFC: stub some functions

### PR DESCRIPTION
**Pull request by mailwl**
Initial stubbing NFC functions.
This is minimal set to start **Mini-Mario & Friends - amiibo Challenge** with first character (Mini Mario).

no actual amiibo parsing is done yet

### CODE REVIEW

**Comment by lioncash** [comment]
Your commit should include what games the stubbing was done for.

**Comment by mailwl** [comment]
Done. I also tryed for Skylanders, but this game works right with IR module, so, no success

**Comment by FernandoS27** [comment]
Fixes the regression in Hyrule Warriors caused by e8a960f6a1c86d15de03a26c22b868771a49929c

**Comment by mailwl** [comment]
@FernandoS27, fully playable Hyrule Warriors(low speed through), hack, based on this PR, if you want: https://github.com/mailwl/citra/tree/hyrule

**Comment by FernandoS27** [comment]
@mailwl you should make a PR for that branch. It does not look very hacky but I don't know much about the kernel. I normaly work on video_core.

**Comment by mailwl** [comment]
nooo, i dislike PRs, which hide errors. It's good as workaround for one or two games, but it may lead to errors in other games

**Comment by FernandoS27** [comment]
oh thought it was just some stubbing, in that case I must agree.

**Pull request merged**
