### PR TITLE
cleardnscache function in httpc implemented

### PR DESCRIPTION
**Pull request by jfmherokiller**
I stubbed the cleardnscache function in HTTP:C
I also added the http service enumeration value to the log.h file

### CODE REVIEW

**Comment by mailwl** [comment]
+1, this stub absolutely equal for unrealized functions (except red string in log)

**Comment by Subv** [comment]
And what would be the point of stubbing this? I see no benefit to it, and it just clutters the codebase.

**Comment by jfmherokiller** [comment]
well i wasnt sure if i should implement it or not since clearing the dns cache could be bad

**Comment by jfmherokiller** [comment]
I now provided clear dns cache code for all platforms

**Comment by mailwl** [comment]
wow, wow! Please don't include this in Citra code! Emulator not allowed to change host

**Comment by wwylele** [comment]
...nope, you probably missed the point of emulation. It is most likely that this function will be implemented in a container that does not interfere the host system. And what's more important, how this is going to be implemented should be decided by who implement the http service (or at least the main part of it). Just picking this single function and implement it with any method doesn't make sense to me.

**Comment by jfmherokiller** [comment]
ok ill remove the changes i was just trying to provide an implementation

**Comment by mailwl** [comment]
@jfmherokiller why do you create whis PR? some game disturbing with log errors?

**Comment by jfmherokiller** [comment]
@mailwl no i just wanted to provide a possible implementation

**Comment by mailwl** [comment]
well, good reason, but why exactly this function? Initialize goes first?

**Comment by mailwl** [comment]
httpc need to be realized, but it tons of work(for all 3 OSes)

**Pull request closed without merging**
