### PR TITLE
Correct output paths for executable binaries in CMakeLists.txt

### PR DESCRIPTION
**Pull request by Dragios**
I believe this was an oversight to miss out `$<CONFIG>` parameter at [CMakeLists.txt](https://github.com/citra-emu/citra/blob/master/CMakeLists.txt) as `$<CONFIG>` was defined in CMakeModules for both [CopyCitraQt5Deps.cmake](https://github.com/citra-emu/citra/blob/master/CMakeModules/CopyCitraQt5Deps.cmake#L3) & [CopyCitraSDLDeps.cmake](https://github.com/citra-emu/citra/blob/master/CMakeModules/CopyCitraSDLDeps.cmake#L3) files.

This fixes the issue for executables binaries copied to the `bin` folder instead of its subfolder after local compile finish with *Microsoft Visual Studio Community 2019 Preview* (Version 16.6.0 Preview 5.0) and thus causing the executable fail to launch within debugging environment due to failing to locate the dlls.

Supersedes PR #5323

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5332)

### CODE REVIEW

**Comment by vvanelslande** [comment]
fix Travis CI

**Comment by Dragios** [comment]
Really? You did not let me know prior to this. Lets wait CI to build first and see how.

**Comment by vitor-k** [comment]
May be similar to what happened on [(https://github.com/citra-emu/citra/pull/4908#discussion_r406900295)]
I'll test later if this doesn't introduce the same errors on VS non-preview (Mine is currently Community 2019 Version 16.4.5)

**Comment by Dragios** [comment]
**Linux (Debug, Frozen version)** exe files are created in *Debug* folder rather than *Release*, I wonder if this breaks anything?
I wanted to put a variable rather than a fix folder name *Release* in `upload.sh` but not sure how.
If any of you guys have idea, let me know else, I might need time to research this.

**Comment by vvanelslande** [comment]
> I wonder if this breaks anything?

it doesn't

**Comment by BreadFish64** [comment]
I believe the frozen version is intentionally a debug build.

**Pull request merged**
