### PR TITLE
qt_themes: replace game_list icons

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
The original icons were drawn by @BreadFish64 and they do not look that good. So I got some icons (slightly revised) in similar styles (black and white) from https://icons8.com to replace the old icons. I'm pretty sure I was licensed to use them for Citra (I even asked them), by the way.
In default theme:
image

In dark theme:
image

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4002)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Revised the SD card icon a bit
New look:
image

**Comment by Dragios** [comment]
Why not make it dark grey instead of black. It will definitely looks better.

**Comment by zhaowenlan1779** [comment]
@Dragios I do not think so, and I'd like to keep the same style for now.

**Comment by B3n30** [comment]
this still lacks documentation of the licenses of the used icons

**Pull request merged**
