### PR TITLE
Windows arm trial

### PR DESCRIPTION
**Pull request by luc-git**
Add windows arm build in github workflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6505)

### CODE REVIEW

**Comment by Steveice10** [comment]
As is I don't think this is actually building for ARM, I see a lot of x86_64 stuff in the CMake logs.

**Comment by luc-git** [comment]
> As is I don't think this is actually building for ARM, I see a lot of x86_64 stuff in the CMake logs.

Maybe but cmake_system_processor is correctly set to arm64. There is another thing there is only one artefact build for msvc and not two

**Comment by luc-git** [comment]
But maybe it’s useless to provide a build for windows arm because as I can see on internet windows arm does not seem to support vulkan

**Comment by luc-git** [comment]
Officially we can only compile a qt-6 project form arm64 by cross compiling from a x64 pc https://doc.qt.io/qt-6/windows.html
`Note: Windows on ARM is only supported as a deployment target. Applications have to be cross-compiled from an x86-64 Windows machine and deployed to target.`

**Comment by SachinVin** [comment]
this is wrong, you need to set the cross-compile options with `-A`
https://cmake.org/cmake/help/v3.26/generator/Visual%20Studio%2017%202022.html#platform-selection

That said, do we want to care about Windows on ARM when Microsoft does not?

**Comment by Steveice10** [comment]
> That said, do we want to care about Windows on ARM when Microsoft does not?

Yeah, it’s already been mentioned that none of the current Windows on ARM platforms support Vulkan, but apparently Microsoft’s own OpenGL compatibility pack also doesn’t support OpenGL above 3.3, so at best you’d get the software renderer. This doesn’t really seem feasible yet.

**Comment by SachinVin** [comment]
Well... that's unfortunate

**Comment by luc-git** [comment]
> this is wrong, you need to set the cross-compile options with `-A` https://cmake.org/cmake/help/v3.26/generator/Visual%20Studio%2017%202022.html#platform-selection
> 
> That said, do we want to care about Windows on ARM when Microsoft does not?

I tried and it does not work 
https://github.com/citra-emu/citra/blob/2b8610fcc4a34aec7c13cbe413076d9de74a9c03/CMakeModules/DownloadExternals.cmake#L45

**Comment by Steveice10** [comment]
> I tried to set the architecture with cmakegui and it does not work
> 
> https://github.com/citra-emu/citra/blob/2b8610fcc4a34aec7c13cbe413076d9de74a9c03/CMakeModules/DownloadExternals.cmake#L45
> 
> I will retry

You can try changing that condition to just ```elseif (MSVC)```, I think it's a typo on my part that the condition wasn't narrowed as there's an ARM64 path inside.

**Comment by FearlessTobi** [comment]
I agree with what was said above. Does Citra even run on Arm64 devices?
If this is only for seeing if Citra compiles on arm architectures, we already have the Android CI target.

**Comment by luc-git** [comment]
> I agree with what was said above. Does Citra even run on Arm64 Windows devices?
> If this is only for seeing if Citra compiles on arm architectures, we already have the Android CI target.

It could run but without graphics acceleration

**Comment by luc-git** [comment]
And you don’t plan to add directx api

**Comment by FearlessTobi** [comment]
Thanks for your contribution, however arm64 is still very niche and we do not plan to offer prebuilt binaries for it at the moment.
Most people who are currently running such devices have the skills to build Citra themselves.

Also as you said yourself, it currently doesn't even work with hw-acceleration on Windows.

**Pull request closed without merging**
