### PR TITLE
Remove unused hash and mem_arena from common

### PR DESCRIPTION
**Pull request by yuriks**
Notably, this gets rid of mem_arena, which should fix 32-bit builds crashing on bootup. (Haven't tested though.)

### CODE REVIEW

**Comment by bunnei** [comment]
LGTM

**Comment by purpasmart96** [comment]
Thank you, mem_arena needed to go, badly...

**Comment by yuriks** [comment]
Just tested, and this *does* fix 32-bit builds. Wee!

**Comment by linkmauve** [comment]
Also tested on Linux, the i686 build even seem to work better than the amd64!

**Comment by lioncash** [comment]
Looks fine to me.

**Pull request merged**
