### PR TITLE
appveyor: change mkdir to md

### PR DESCRIPTION
**Pull request by valentinvanelslande**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3342)

### CODE REVIEW

**Comment by wwylele** [comment]
What is the purpose to change the command to its alias (or the other way around)?

**Comment by MerryMage** [comment]
It would be nice to have a reason/justification for the change in the PR description. This PR seems unnecessary.

**Comment by BreadFish64** [comment]
Since no one is actually typing these, I don't think it's necessary to abbreviate them.

**Comment by chris062689** [comment]
Closed due to original PR description not having a reason / justification. Please be more detailed when opening future PRs as to what function and reason for the change.

**Pull request closed without merging**
