### PR TITLE
Port yuzu-emu/yuzu#11946: "Enable (Feral Interactive) Gamemode on Linux"

### PR DESCRIPTION
**Pull request by FearlessTobi**
Ported from https://github.com/yuzu-emu/yuzu/pull/11946.
Would be great if someone who is on Linux could test this.

**Original description**:
Rebase of #10599 by @xcfrg on master, using new settings.
Gamemode needs to be installed on the computer to be used, otherwise it runs without it and a warning is logged.

I set the setting has being disabled when a game is running, as I do not know if it is possible to enable/disable gamemode while running. But `SetGamemodeDisabled()` is called if the settings is changed, so we would only need to change from `false` to `true` in the Setting definition in settings.h

> This pull request adds [Feral Gamemode](https://github.com/FeralInteractive/gamemode) support to yuzu on linux, allowing for optimizations to the cpu governor, i/o and process priority, and if using a -ck or -pf kernel, the kernel scheduler.
> 
> Closes https://github.com/yuzu-emu/yuzu/issues/10078

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7245)

### CODE REVIEW

**Review by Steveice10 — APPROVED** [review]
Not able to test but the code looks fine to me.

**Comment by Steveice10** [comment]
TGP reported that the setting doesn't persist if Citra is restarted, I think the code for saving/loading the setting is missing on second look.

**Comment by FearlessTobi** [comment]
Fixed.

**Comment by Steveice10** [comment]
Confirmed, thanks

**Pull request merged**
