### PR TITLE
Fix issue #2238 Kid Icarus

### PR DESCRIPTION
**Pull request by SigmaVirus**
According to @mailwl ReadSavedData needs to be stubbed in order to pass the loop in Kid Icarus

### CODE REVIEW

**Comment by SigmaVirus** [comment]
Sorry for the PR clutter but I didn't know how to change and include multiple files in a PR, but #2535, #2536 and #2537 is connected to each other.

**Comment by wwylele** [comment]
@SigmaVirus Please integrate these three PR into one. You can commit multiple files by forking citra, pulling it to your local, committing multiple files via git and pushing back to github.

**Comment by mailwl** [comment]
@wwylele i prefer view your CEC implemetnation in Cirta code instead ot returning error, Du you plan to fll your code to Citra? it confimed as working by Tomodachi Life

**Comment by SigmaVirus** [comment]
Made a proper pull request.

**Pull request closed without merging**
