### PR TITLE
Service/NDM: convert to ServiceFramework

### PR DESCRIPTION
**Pull request by wwylele**
a.k.a rewrite NDM module

~~This is a single-service module, so there is no point to have two `ndm.cpp` and `ndm_u.cpp` files. As our convention it should be put in top level service folder.~~

Only log the input parameters according to conventions as well.

Changed LOG to NGLOG

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3746)

### CODE REVIEW

**Comment by Subv** [comment]
Is it really our convention to put single-service modules in the top level? I kinda prefer them to be organized in their own subfolders

**Comment by wwylele** [comment]
@Subv I am fine either way. If you prefer that I will move the files.

**Comment by purpasmart96** [comment]
When I refactored a whole bunch of services a while ago I found that having them in their own folder felt much more organized then having them all over place in one directory, So I would personally prefer them to be kept in  in their own subfolders.

**Comment by wwylele** [comment]
moved to the ndm folder

**Pull request merged**
