### PR TITLE
added http service enum to the log.h file

### PR DESCRIPTION
**Pull request by jfmherokiller**
I added the http svc enum to the correct spot in the log.h file

### CODE REVIEW

**Comment by jfmherokiller** [comment]
sorry for the last pull request i just wanted to try to help and didnt know the full picture

**Comment by mailwl** [comment]
may you also add 2 changes to PR?
https://github.com/citra-emu/citra/blob/master/src/core/hle/service/nim/nim.cpp#L22 - NWM to NIM
https://github.com/citra-emu/citra/blob/master/src/core/hle/service/ir/ir_u.cpp#L30 - clang format ON

**Comment by jfmherokiller** [comment]
@mailwl yes i can one moment

**Comment by jfmherokiller** [comment]
@mailwl the changes have been made

**Comment by mailwl** [comment]
thanks a lot!

**Comment by wwylele** [comment]
You need also add the log entry here: https://github.com/citra-emu/citra/blob/master/src/common/logging/backend.cpp

**Comment by mailwl** [comment]
@wwylele good point, i am an idiot not see such mistake, when i already adds so many services to log

**Comment by jfmherokiller** [comment]
oh fuck

**Comment by jfmherokiller** [comment]
fixed lol

**Pull request merged**
