### PR TITLE
motion_emu: Use 0.00125 as default sensitivity instead of 0.01

### PR DESCRIPTION
**Pull request by adityaruplaha**
Self-explanatory.

---
Thanks to Bargington#5947 on Discord for helping me pin down the value.
Turns out 0.01 makes tilt way too fast. Tested on Mario & Luigi Dream Team.

---
(Also I've made a few other misc changes to `tilt_clamp` to make it compliant to coding style.)

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3626)

### CODE REVIEW

**Comment by lioncash** [comment]
The commit message should include the rationale for changing the default sensitivity

**Comment by adityaruplaha** [comment]
It's already in the PR description. You want me to add it in the commit message too? Np, will do.

**Comment by lioncash** [comment]
Yes, that's the point of a commit message. To explain and provide context.

People shouldn't have to look up the pull request to find out why you did something (part of the point of git, or any distributed version control is that it's not centralized, you can access information/revisions without needing the internet, provided the repository is cloned).

If we ever migrate off GitHub (for whatever reason) in the future, that contextual information is effectively lost.

**Comment by adityaruplaha** [comment]
@lioncash Done.

**Comment by wwylele** [comment]
Inb4 next week another one open a PR changing it to 0.02, saying 0.00125 is too slow for game XXX.

----

My concern is that you only said this is suitable for Mario & Luigi Dream Team, not mentioning/testing other games. Different games might require different proper value, so I don't think messing with the default value is a good idea before we have a concrete argument about what is the proper default one considering all games. Instead, it is probably better to expose it as user settings and let users control it when needed.

**Comment by adityaruplaha** [comment]
In that case, closing.

**Pull request closed without merging**
