### PR TITLE
android: Turn GameInfo into a class

### PR DESCRIPTION
**Pull request by JosJuice**
By only loading data from disk when creating an instance of this new class instead of on every method call, we save a lot of file open operations, which due to SAF are very expensive. This should noticeably speed up game list scanning.

No intended change in what metadata is shown.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6494)

### CODE REVIEW

**Comment by SachinVin** [comment]
Please rebase

**Comment by SachinVin** [comment]
Seems submodules were accidentally reverted

**Comment by JosJuice** [comment]
Thanks for the catch! Should be fixed now.

**Comment by SachinVin** [comment]
Thanks!

**Pull request merged**
