### PR TITLE
Fix Missing libpcre2-16-0.dll from both latest Nightly and Canary builds #3036

### PR DESCRIPTION
**Pull request by acnleditor2**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3037)

### CODE REVIEW

**Comment by wwylele** [comment]
Question: out of all "pcre" dlls
```
"libpcre-*.dll",
"libpcre16-*.dll",
"libpcre2-16-*.dll", (new added)
"libpng16-*.dll"
```
are these still all relevant? Or some of them can be removed due to the update?

**Comment by Hexagon12** [comment]
@wwylele Those DLLs are still relevant.

**Comment by Jhon591** [comment]
try using it on me
https://gbatemp.net/threads/citra-unofficial-chinese-builds-discussion.431974/page-306#post-7649940

**Comment by jroweboy** [comment]
@wwylele yes, they are all dependcies for qt5 in case you are wondering where they came from.

@MerryMage a proper fix would be much appreciated, but in the meantime, lets just merge this one so at least its not completely non functional

Also re sound issues: someone will have to investigate them separately.

**Comment by acnleditor2** [comment]
@jroweboy I can create a folder called dlls in the root, add SDL2.0.5 there and make AppVeyor download it instead of copying it from the mingw folder.

**Comment by Jhon591** [comment]
I replaced the New SDL2.dll with the Old one and it worked fine, so is new SDL2.dll causing No Audio in Citra.

**Pull request merged**
