### PR TITLE
OpenGL: Implement DOT3 texture combiner

### PR DESCRIPTION
**Pull request by yuriks**
This was only implemented in the software rasterizer.

cc @JohnGodgames

### CODE REVIEW

**Comment by JamePeng** [comment]
@yuriks 
maybe also implement AppendAlphaCombiner::DOT3_RGBA

**Comment by mailwl** [comment]
DOT3_RGB/DOT3_RGBA does not apply to AlphaCombiner, only ColorCombiner

**Comment by JamePeng** [comment]
@mailwl yes,my fault,it should apply to colorcombiner!

**Comment by yuriks** [comment]
Uh, as pointed out by @JamePeng this is actually completely wrong.

**Comment by JamePeng** [comment]
video_core\rasterizer.cpp:Pica::Rasterizer::ProcessTriangleInternal 
there are some missing case and process for Dot3RGB in ColorCombine!

**Comment by bunnei** [comment]
Is there a reason not to also implement this in the HW renderer with this PR (as it's also quite trivial)

**Comment by yuriks** [comment]
@bunnei This *is* in the hwrenderer. The rasterizer already had this for a while. Anyway, don't merge this yet cause I haven't tested it properly.

**Comment by JamePeng** [comment]
@yuriks @mailwl

**Comment by bunnei** [comment]
@yuriks Oops indeed... I had misinterpreted the description "This was only implemented in the software rasterizer." without actually looking at the diff, sorry!

**Comment by Subv** [comment]
Didn't we find that this formula wasn't actually correct for the 3DS?

**Comment by JamePeng** [comment]
I try this expression:
`  out += "vec3(dot(" + variable_name + "[0] - vec3(0.5), " + variable_name + "[1] - vec3(0.5)) * 4.0)";`

**Comment by yuriks** [comment]
Hi, my name is yuriks and I created a PR in 10 minutes without verifying the code or even testing that it worked. Unsurprisingly it didn't at all. So that PR is now closed.

**Comment by yuriks** [comment]
Again: I closed this PR because it was untested, broken, and I didn't plan on working or spending any more time on this. @JamePeng's code seemingly works fine for this specific case, so someone else can probably use it for another PR implementing this. I wonder if one of the versions shouldn't exclude or include alpha, which that currently doesn't seem to differentiate between.

**Pull request closed without merging**
