### PR TITLE
citra, citra_qt: add quick volume control using mouse wheel

### PR DESCRIPTION
**Pull request by vvanelslande**
For `citra`, the volume is logged (using `Debug` level).
For `citra_qt`, a message saying `Volume changed to %` is shown in the status bar when you change the volume using the mouse's wheel.
A setting (disabled by default) is added.

Video (`citra_qt` starts at 0:25):
[Video](https://streamable.com/j5ta0)

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4947)

### CODE REVIEW

**Comment by chris062689** [comment]
This isn't self explanatory at all. 

What is this doing? Did you change the UX? Please include a screenshot. 

Does this allow users to mouse scroll anywhere on the screen to control volume?

**Comment by vvanelslande** [comment]
nothing in the UI is changed. 

> Does this allow users to mouse scroll anywhere on the screen to control volume?

yes

**Comment by wwylele** [comment]
I wonder if this would cause more accidental volume changing than intended. Like users just wants to scroll the browser but accidentally does it on citra and mute the sound, then comes to complain about it. In my experience volume controlled by mouse wheel isn't a common practice that people can easily find.

**Comment by chris062689** [comment]
This does not seem to be a very well thought out UX improvement. 
This will absolutely cause users to accidental change volume while playing.

Requesting to close.

**Comment by vvanelslande** [comment]
I will add a setting to enable this.

**Comment by vvanelslande** [comment]
Rebased and changed the SDL log class from `Frontend` to `Audio`.

**Comment by chris062689** [comment]
Putting it behind a setting does not mean it is a good UX decision.

**Comment by adityaruplaha** [comment]
> Like users just wants to scroll the browser but accidentally does it on citra and mute the sound, then comes to complain about it. In my experience volume controlled by mouse wheel isn't a common practice that people can easily find.

I'm personally prone to that mistake. Besides, is this really needed? Most people don't even use `citra`.

**Pull request closed without merging**
