### PR TITLE
build: Enable link time optimization in CI.

### PR DESCRIPTION
**Pull request by Steveice10**
Replacement for https://github.com/citra-emu/citra/pull/6609

Enables link-time optimizations in release builds. I've moved this to set for the entire src directory instead of having to set the flag on every target individually.

In my testing this did not require any of the other compiler changes that the previous PR did. All I had to do was increase the Windows page file size in CI for the build to succeed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6887)

### CODE REVIEW

**Comment by GPUCode** [comment]
The original intent behind configuring this per-target was to make sure LTO is applied only for citra targets and not for external libraries, to prevent any issues arising from that. Was there any performance benefit observed by setting it globally?

**Comment by Steveice10** [comment]
> The original intent behind configuring this per-target was to make sure LTO is applied only for citra targets and not for external libraries, to prevent any issues arising from that. Was there any performance benefit observed by setting it globally?

I haven't thoroughly performance tested anything yet but I haven't seen any issues come out of it. It simplifies the logic to have it in one place because of the additional checks that we should be doing that weren't there before, but I can change it back if you'd prefer that.

**Comment by Steveice10** [comment]
Thinking about it again, I might be able to just apply it to the src folder CMakeLists and still keep it consolidated into one piece of logic. I'll do that in a bit.

**Comment by GPUCode** [comment]
That would be best option I think

**Comment by Steveice10** [comment]
Two updates:
* Moved flag setting to src directory only to keep logic simple but exclude externals.
* Set ENABLE_LTO by default for all release builds, to help prevent weird CI build only issues that aren't caught in local release builds. Debug builds will still leave it disabled.

**Comment by Steveice10** [comment]
Some really basic, unscientific performance tests on my Windows machine:
* Super Mario 3D Land demo level (when you wait on the title screen): 570 FPS -> 590 FPS
* Pokemon Alpha Sapphire title screen: 360 FPS -> 380 FPS
* Luigi's Mansion Dark Moon title screen: 60 FPS -> 64 FPS

**Pull request merged**
