### PR TITLE
Switch compiler to clang on Linux

### PR DESCRIPTION
**Pull request by TGP17**
This gives me a Performance increase from 5 to 10% in games on Citra on Linux. I tested this on a Laptop with an iGPU. 
This needs https://github.com/citra-emu/build-environments/pull/57

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7077)

### CODE REVIEW

**Comment by Steveice10** [comment]
Looks fine to me although wanted to check, have you tried what happens if you install clang and don't install GCC in the Docker image? Would be simpler if we could just swap the compiler in the image and it automatically picks it up in Citra with no changes needed here.

**Comment by TGP17** [comment]
I haven't tested this yet, but I can quickly test this in my build script rest repo.

**Comment by TGP17** [comment]
I get these errors: `CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!`

**Comment by Steveice10** [comment]
I think if you just install the ‘ninja’ package it might resolve that

**Comment by TGP17** [comment]
Yeah, pretty weird. And you're welcome.

**Comment by Steveice10** [comment]
Only other comment I'd have on this is, assuming only Clang 15 is installed in the AppImage, if we could refer to them by just 'clang' and 'clang++' here instead of the specific version, that would help for updating the build image in the future.

**Comment by TGP17** [comment]
Alright done. I needed to set clang 15 as the default version in the dockercontainer, otherwise it didn't find any clang version.

**Comment by amayra** [comment]
compiled citra and other emulators with "march=native" and some other optimizations flag can make a big different in my intel ivy bridge CPU and I don't think newer CPU users see or need this tho

**Comment by Steveice10** [comment]
> compiled citra and other emulators with "march=native" and some other optimizations flag can make a big different in my intel ivy bridge CPU and I don't think newer CPU users see or need this tho

That won't really work as well for our broadly distributed release builds here, as the benefit of using march=native is that it can better target your specific CPU.

**Pull request merged**
