### PR TITLE
core_timing: Allow configuring a fixed or random initial system tick value.

### PR DESCRIPTION
**Pull request by Steveice10**
Adds a random base ticks value to the counter on startup, to account for games that query the system tick and use it for randomness. Based on an idea from comments in https://github.com/citra-emu/citra/pull/7199 (note: the PR is not fully superceded by this as LLE module initialization is still an issue).

~~This should not impact TASing or other use cases that rely on consistency since this only happens on first initialization; when a save state is loaded the tick counter will be restored as well.~~

TAS movies will now generate an override value for recording and playback, saved in the movie file header.

This also adds a setting to configure whether to use the random base tick value or provide your own fixed value.

Preview:
Screenshot 2024-01-03 at 11 37 37 AM
Screenshot 2024-01-03 at 11 37 45 AM

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7309)

### CODE REVIEW

**Comment by B3n30** [comment]
I agree with @JosJuice . Solution might be to seed the rng with the system time. So if TAS or movies are used and settings are set to fixed time you get the same seed every time and a normal user who uses system time will always get a random seed and thus a random clock ticks offset

**Review by B3n30 — CHANGES_REQUESTED** [review]
base_ticks should always be the same number if fixed time/movies/TAS is used, not only if save-sates is used

**Comment by Steveice10** [comment]
I admittedly am not super familiar with how the TAS movie system works, I thought that they used states to control for the initial state of the recording but I was mistaken.

I've added saving/loading the base ticks value to the movie header to account for this. For any existing movies, the value at that offset in the header should be 0 so it will work out to initializing the tick count to 0, same as the previous behavior they were recorded under.

Please check and let me know if I'm missing anything.

**Comment by B3n30** [comment]
I'm still not happy with this change since it now only provides consistency with movies but e.g. not with external tas tools. Like I said the offset should just be based on our init_time so we only have one source of RNG and every other RNG Is derived from that

**Comment by Steveice10** [comment]
> I'm still not happy with this change since it now only provides consistency with movies but e.g. not with external tas tools. Like I said the offset should just be based on our init_time so we only have one source of RNG and every other RNG Is derived from that

It doesn't make sense for it to be based on time though, for example if the user wants to set the time to X time on Y day for reasons other than RNG control they shouldn't also be forced to have the same ticks value. Would a separate setting alongside init_time suffice?

**Comment by B3n30** [comment]
But the init_time was only introduced for that RNG purpose.

**Comment by Steveice10** [comment]
> But the init_time was only introduced for that RNG purpose.

No? `init_time` can be used simply to influence in-game time-of-day and time-based events as well.

**Comment by B3n30** [comment]
yes it can but fot that one can also simply change the system time.
And in that case we would have the same issue: the game isn't really random anymore for games that only use the time as RNG-seed. But for casual play this isn't noticeable due to the randomness of inputs. Thus I think just having the init_time as RNG seed should be enough

**Comment by Steveice10** [comment]
> yes it can but fot that one can also simply change the system time. And in that case we would have the same issue: the game isn't really random anymore for games that only use the time as RNG-seed. But for casual play this isn't noticeable due to the randomness of inputs. Thus I think just having the init_time as RNG seed should be enough

It's more convenient to change the time in the Citra settings than to change the time of your whole system. I don't see why this needs to be tied together and why we can't just have separate wall-time and tick-time settings.

**Comment by B3n30** [comment]
We can do that. I just think it's not necessary, overkill and might be to complex for users to understand. But maybe lets check how other emus handle this?

**Comment by Steveice10** [comment]
> We can do that. I just think it's not necessary, overkill and might be to complex for users to understand. But maybe lets check how other emus handle this?

If we're catering toward use cases like TAS I'd rather have maximum flexibility for the value to be manipulated.

**Comment by Steveice10** [comment]
> We can do that. I just think it's not necessary, overkill and might be to complex for users to understand. But maybe lets check how other emus handle this?

FWIW I couldn't find examples of other emulators that handle games random seeding from the tick count, I checked Yuzu, Dolphin, and PPSSPP and didn't see anything.

**Review by B3n30 — APPROVED** [review]

**Comment by CasualPokePlayer** [comment]
Dolphin sort of has an example, [setting the "timebase" value to the emulated RTC](https://github.com/dolphin-emu/dolphin/blob/8a9d1687754e25a42d5da2d369093e653e6fd798/Source/Core/Core/HW/SystemTimers.cpp#L279-L281)... but that's not so much of a good example since that's just what the IPL does too (and games always just treat the timebase value as the RTC's value).

**Comment by PabloMK7** [comment]
> > We can do that. I just think it's not necessary, overkill and might be to complex for users to understand. But maybe lets check how other emus handle this?
> 
> FWIW I couldn't find examples of other emulators that handle games random seeding from the tick count, I checked Yuzu, Dolphin, and PPSSPP and didn't see anything.

Other emus just don't care about this, either because is very minor or because they have real multithreading which introduces the needed "randomness" so that the system tick varies.

**Comment by JosJuice** [comment]
Most other emulators don't provide any randomness of this kind to the emulated system. The games have to make do with button inputs and the RTC (if there is one) to seed their RNGs. (There is also the fascinating topic of uninitialized RAM on older systems, which some games do use for RNG seeding, but I'm not aware of any emulators that randomize that by default.)

**Comment by CasualPokePlayer** [comment]
> I'm not aware of any emulators that randomize that by default

It's not entirely unheard of. The Game Boy has bgb, SameBoy, and Mesen (and probably others) doing that by default. For the SNES, bsnes (/higan/ares) and Mesen also do that. And Mesen also does it by default for PC Engine and SMS (although it does interesting not do that for NES, instead defaulting to all 0s).

**Pull request merged**
