### PR TITLE
Clang fix

### PR DESCRIPTION
**Pull request by adityaruplaha**
I dont think there's anything to explain.

This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3423)

### CODE REVIEW

**Comment by adityaruplaha** [comment]
Hey why absolute silence?

**Comment by BreadFish64** [comment]
Well, IIRC jroweboy is planning to fix clang stuff to work automatically and change the version, so we're debating whether it's necessary in the meantime

**Comment by jroweboy** [comment]
@adityaruplaha https://github.com/citra-emu/citra/pull/3410 clang format version is getting updated (and the whole program is getting reformatted) so it doesn't matter whether this gets merged or not really. if you want, we can merge it, but it doesn't change anything. 3410 is held up until we merge tex cache and multiplayer.

**Comment by adityaruplaha** [comment]
Ohhhkkk....
Since doesn't help anyways, I'll just close it.
I think the devs have got enough on their plate already 😃

**Pull request closed without merging**
