### PR TITLE
ci: Support Android x86_64 and optimize build caching.

### PR DESCRIPTION
**Pull request by Steveice10**
* Add support for x86_64 to the Android builds.
  * This is pretty low hanging fruit since we already support x86_64 on desktops, it just needed a few guards for ARM64-specific adrenotools code and the x86_64 Vulkan Validation Layer.
  * Can be useful for x86_64-based Chromebooks, Android TV boxes, 2-in-1s, etc.
  * Replace Android JNI libs in source tree with build-time download of Vulkan Validation Layer from the upstream releases. This way we don't need the ~40MB .so files in our source tree.
  * Remove libc++_shared.so. According to Android docs we don't actually need this since it should be handled for us by Gradle, and from my testing I haven't seen any adverse effects from removing it.
  * Added compression to Android build artifacts to keep download size down.
* Optimizations to the CI build caching to keep compile times under control with this change.
  * Changed all ccache compiler checks to 'content'. The modified time of the compiler can vary from run to run, which causes caches to invalidate too often.
  * ~~Disabled pre-compiled headers by default. While typically these may provide a compile time speed boost, in practice it didn't do much, and in fact it drastically increases our build times because it causes issues with ccache matching.~~ Re-enabled pre-compiled headers since it helps cold build times and worked around cache issue with some flags.
    * Added build flag to match dynarmic pre-compiled header setting to Citra's.
  * Enable verbose ccache statistic reporting for build time debugging purposes.
  * Remove recursive clone from macos-universal job as we don't need any of the submodules for this step.

With these changes the build times look roughly like this best-case: ~~https://github.com/Steveice10/citra/actions/runs/6430069770~~ https://github.com/Steveice10/citra/actions/runs/6438419187

MSVC still needs work (and I think there was an issue with the GitHub worker that caused it to take that long in that particular run) but you can see that the other runs took only about ~8-11 minutes, even with Android building for two architectures.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/7045)

### CODE REVIEW

**Comment by SachinVin** [comment]
Do we really want to tho... the artifact is now almost 300mb...

**Comment by Steveice10** [comment]
> Do we really want to tho... the artifact is now almost 300mb...

That’s two artifacts combined. It’s split in the releases.

**Comment by SachinVin** [comment]
That's still >150mb for the apk

**Comment by Steveice10** [comment]
> That's still ~>150mb~(184mb actually) for the apk
> 
> Majority of it seems to be the Vulkan validation layers ~50mb for each architecture

Should we remove those then? It is possible to load them externally, and no other platform includes them bundled in.

**Comment by SachinVin** [comment]
> Should we remove those then? 

(@GPUCode )

>It is possible to load them externally, and no other platform includes them bundled in.

Seems like it is possible only on android 11 for non debug builds
https://developer.android.com/ndk/guides/graphics/validation-layer#enable-debugging

**Comment by GPUCode** [comment]
Loading validation layers externally requires root access, which is not feasable for the average user. Also limits our ability to get vulkan bug reports (well debug renderer checkbox is not a bit broken but the option is still accessible from the config file)

**Comment by Steveice10** [comment]
> Loading validation layers externally requires root access, which is not feasable for the average user. Also limits our ability to get vulkan bug reports (well debug renderer checkbox is not a bit broken but the option is still accessible from the config file)

The docs say root access is one out of three possible ways, not required to load it.

**Comment by Steveice10** [comment]
Is this even really an issue at all? When the APK is installed the parts not for the current device are discarded, so the installed size doesn’t change.

**Comment by SachinVin** [comment]
Mostly thinking about download size, and if it is really worth the extra build time for maybe 1% of Android users

**Comment by Steveice10** [comment]
> Mostly thinking about download size, and if it is really worth the extra build time for maybe 1% of Android users

* Download size I'm looking into adding compression similar to our other downloads.
* The build time is not an issue, the optimizations cut down the Android build time to same or less than it was before, even with x86_64 included. You may not see that in the PR build though because the cache is fully cold.

**Comment by Steveice10** [comment]
Made a few changes to hopefully help satisfy concerns:
* Android artifacts are now compressed the same as the others, which cut the artifact size down by half.
* Re-enabled pre-compiled headers as it was driving up the cold cache build times more than expected, now we just use a couple of compiler and ccache options to make sure that we still get good cache hit rates in CI.

**Review by SachinVin — APPROVED** [review]
Still not convinced that we need to ship x64 for android, but it is fine since my concerns are addressed

**Pull request merged**
