### PR TITLE
Qt: RoundPreferFloor scaling mode for win HiDPI

### PR DESCRIPTION
**Pull request by stuken**
The HiDPI code is identical to Yuzu where it also caused 4k displays at 150% displays to scale way too high. RoundPreferFloor will stop Qt from scaling too high for 150% scaling modes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6441)

### CODE REVIEW

**Comment by GPUCode** [comment]
Could you share some screenshots of the before and after?

**Comment by stuken** [comment]
image
You can see the latest nightly and the pr build here along with the visual studio and firefox. The PR build has consistent scaling with the rest of the OS while the nightly is doubled in size.
image
You can see the bitmap resources getting pixelated due to the scaling, this carries over to game icon and other library items.

**Comment by Daisouji** [comment]
I was just something similar to this on QT6 PR, but w/ a non-4K resolution w/ the same dpi
Capture

**Comment by stuken** [comment]
Closing as the Qt6 migration has fixed the scaling.

**Pull request closed without merging**
