### PR TITLE
Https/GitHub.com/jhon591/citra/commit/683948e1735fe62651f1833db2c7d38142d8d1e1

### PR DESCRIPTION
**Pull request by Jhon591**
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3019)

### CODE REVIEW

**Comment by j-selby** [comment]
Can you please stop creating these PRs if you are just going to take others work? They don't contribute anything to the discussion and only promote your hacked up builds, which do nothing to further Citra.

**Comment by B3n30** [comment]
This really gets annoying, and also spams all the log

Can you please stop creating those PRs, if you don't know how to use github ask for help on irc or discord.

I personally don't think that changing just that one label, is worth a PR...

**Comment by Jhon591** [comment]
I'll not do any more, keeps pulling more files then just the one file intended to be..

**Comment by B3n30** [comment]
Yeah you are clearly doing a lot wrong.

Ask for help here: https://discordapp.com/invite/9jgD2y4
But follow the rules!!!

If you are continuing creating such PRs you risk getting banned from github.

**Comment by Jhon591** [comment]
Ok, B3n30, try give this a go, not good.
https://gbatemp.net/threads/citra-unofficial-chinese-builds-discussion.431974/page-304#post-7644367

**Comment by Jhon591** [comment]
Maybe adding the one fix to a clean master citra.

**Comment by Jhon591** [comment]
looks like did not listen to some think in that guild, will retry soon.

**Comment by Jhon591** [comment]
How can this be a hack ?
https://github.com/Jhon591/citra/commit/24fa5863d1d7d68ab0f8a1b256378c3797eac632

Is what the game was asking for in cmd, once added game booted, but other issue is with it saving game.

**Comment by Jhon591** [comment]
This one boost the full motion video speed to 100% found by mistake, seems to have 0 regression as far i know are tested games by
https://github.com/Jhon591/citra/commit/9866a49d54643c40db14b96ee0b2e2d00d4b8daa

Maybe you guys could find out why, Maybe come up with a much better Source Coding out of it ?, stuff like this could be useful..

**Comment by Dragios** [comment]
Clearly you did not test it thorougly if you can't find any regression. I already found a few flaws with your so call video speed hack.

**Comment by Jhon591** [comment]
@Dragios 
Don't have every game in the world to try, what have you found, i did not hack just found while messing about, yes videos have 100% speed +, but yes frame limit enabled is advised.

**Pull request closed without merging**
