### PR TITLE
Services/FS: Stubbed CardSlotIsInserted to always return false

### PR DESCRIPTION
**Pull request by Subv**
We won't be emulating this for the foreseeable future and it is needed for Home Menu to boot further

### CODE REVIEW

**Comment by yuriks** [comment]
Won't this produce interesting results, like if some game expects to be running from the card and calls this?

**Comment by yuriks** [comment]
LGTM

**Comment by archshift** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM

**Pull request merged**
