### PR TITLE
Replace standard uint*_t and int*_t with CommonTypes’ u* and s* types

### PR DESCRIPTION
**Pull request by linkmauve**
The ARM core was ridden with those, but there was also an occurence in the CitraQt debugger.

This commit is purely stylistic, there is no change in behaviour.

### CODE REVIEW

**Comment by zawata** [comment]
i came across this several times during my warning fixes and was unsure of why it was that way
i just left it because i figured there was a reason

**Comment by Subv** [comment]
Is there any reason for this? the way I see it, it's just adding more includes and making the dyncom harder for other projects to use for no gain

**Comment by linkmauve** [comment]
I was thinking about unification of the codebase.

My personal opinion would be to drop those ugly u32, s16, etc. and use the proper uint32_t, int16_t types instead, everywhere, and drop common_types.

**Comment by neobrain** [comment]
I'm not opposed to this change. I'd also prefer dropping u32 & pals, though.

**Comment by mailwl** [comment]
please dont do it!
i like u32 s32 and friends

**Comment by lioncash** [comment]
likewise

**Comment by bunnei** [comment]
LGTM. I don't really have a strong opinion in keeping them or changing all to uint*... but for now I think this change makes sense.

**Comment by yuriks** [comment]
I like the u* overloads, but I think we should keep dyncom as is. It's not a significant cleanup to change it, generates diff churn and also makes it harder to use it in other projects.

**Comment by purpasmart96** [comment]
I agree with yurkis, I like the u* typedefs too myself.

**Comment by bunnei** [comment]
So can this be merged...?

**Comment by neobrain** [comment]
@linkmauve Please decide whether you want this merged or not.

**Comment by linkmauve** [comment]
I rebased it as is, as I think uniformity is better in the case of Citra (and dyncom was already ridden with our own integer types anyway).

**Comment by bunnei** [comment]
@linkmauve I'm not sure why this wasn't merged after you rebased.... I guess no one noticed it was good to go. Can you rebase again to address the current conflicts? Sorry :-/

**Comment by linkmauve** [comment]
Here, rebased and included the newer files that also added some standard int types. :)

**Pull request merged**
