### PR TITLE
Disable web services by default

### PR DESCRIPTION
**Pull request by j-selby**
Telemetry reporting should not be enabled by default. Branches in development or unofficial builds should not be submitting telemetry data by default unless it is explicitly required, as this data could potentially be mixed with data from valid, prebuilt nightly distributions.

This also enables web services for Travis and AppVeyor builds by default.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2832)

### CODE REVIEW

**Comment by B3n30** [comment]
After that PR gets merged, we should change the wiki pages for building thus users building citra will enable web_services.

**Comment by chris062689** [comment]
We probably need separate flags for telemetry vs netplay.

**Comment by yuriks** [comment]
:lgtm:, but maybe should be reviewed by someone more familiar with this subsystem.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2832#-:-KqQwJlBMg2z-RQC-7Eb:bpngtip)*

**Comment by yuriks** [comment]
Also, needs a rebase.

**Comment by j-selby** [comment]
Rebased.

**Comment by yuriks** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2832)*

**Comment by chris062689** [comment]
@B3n30 isn't the point that anyone building Citra shouldn't build with web_services, as we don't want them submitting telemetry? 

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by B3n30** [comment]
I'm still not sure if disabling web_services is the right way to disable telemetry. Currently it's only telemetry using web_service, but we will add other stuff that needs web_services. I think it's better to have a flag that gets checked when sending telemetry, thus this can be disabled by default and travis/appveyor will enable it by default. The same flag is probably used for settings

**Comment by chris062689** [comment]
@bunnei What is your opinion on this related to telemetry? 

Should we enable it by default (anyone that builds Citra will have it enabled) or only on our official builds? 

We already have it setup where you can easily filter out custom builds from the rest of the data.

**Comment by j-selby** [comment]
Closing. Not willing to maintain this.

**Pull request closed without merging**
