### PR TITLE
Common: Remove Common::make_unique, use std::make_unique

### PR DESCRIPTION
**Pull request by MerryMage**
\C++14/

### CODE REVIEW

**Comment by lioncash** [comment]
LGTM

**Comment by bunnei** [comment]
... a little bit late, but LGTM as well

**Comment by neobrain** [comment]
Reactions don't work without javascript, so here goes ascii art:
```
░░░░░░░░░░░░░░░░░▒█████████▓░░░░░░░░░░░░░░░░░ ░░░░░░░░░░░░░░░▓██████████████▒░░░░░░░░░░░░░░ ░░░░░░░░░░░░░▒████▓▒░░░░░░▒▓████▒░░░░░░░░░░░░ ░░░░░░░░░░░░████▒░░░░░░░░░░░░▒████░░░░░░░░░░░ ░░░░░░░░░░░███▒░░░░░░░░░░░░░░░░▒███░░░░░░░░░░ ░░░░░░░░░░███░░░░░░░░░░░░░░░░░░░░███░░░░░░░░░ ░░░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░███░░░░░░░░ ░░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░░░▓██░░░░░░░ ░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░░░░░███░░░░░░ ░░░░░░███░░░░░▒░▒░▒░░░░░░░▒░▒░▒░▒░░░░██▓░░░░░ ░░░░░▒██░▒░▒▒▒▒▒░▒░▒░▒░▒░▒░▒░▒▒▒▒▒░░░░██░░░░░ ░░░░░██░░░▒▒▒▒▒▒▒▒▒░▒░▒░▒░▒░▒▒▒▒▒▒▒▒▒░▒██░░░░ ░░░░██▓░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒░██▒░░░ ░░░░██░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░██░░░ ░░░██▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▓█▓░░ ░░░██░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒███░░██░░ ░░▓█▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░▒██████▓░▓█▒░ ░░██░▒▒░░░▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░▓█████████▓░██░ ░░██░░▒▓▒▒░░░░░░░▒▒▒▒▒▒▒░░░░███████████▓▒░██░ ░▓█▒░░████████▓▒░░░░░░▒░░░████████▓██▒░░▒░▓█░ ░██░░█████████████▓▒░░░░████████░░░░█▓▒▒▒▒▒█▓ ░██░▓████████████████▓▒█████████▒░░░█▓▒▒▒▒░██ ▒█▓░▒▓▓██░░▒██████████▒█████████▒░░░█▓▒▒▒▒░██ ▓█▒░▒░▒██░░░███████▓█▓░█▒▓█░▓███▒░░░█▓▒▒▒▒▒▓█ ██▒▒▒▒▒██░░░██░████░▓▓░▓▓░█████▓░░░▒█▒▒▒▒▒▒▒█ ██░▒▒▒▒██░░░▓█████▓░█▒░▓█░▒███▓░░░░▓█▒▒▒▒▒▒▒█ ██░▒▒▒░██░░░░▓███▓░░█▒▒▒█▒░░░░░░░░▒█▓▒▒▒▒▒▒▒█ ██░▒▒▒▒▓█▒░░░░▒▒▒░░▓█░▒▒▓█▒░░░░░░░██░▒▒▒▒▒▒▒█ ██░▒▒▒▒▒██░░░░░░░░▒█▒▒▒▒░▓█▓░░░░▒██▒▒▒▒▒▒▒▒▒█ ██▒▒▒▒▒░▒██░░░░░░▒█▓▒▒▒▒▒░▒██▓▓██▓░▒▒▒▒▒▒▒▒▒█ ██▒▒▒▒▒▒░▓██▒▒▒▒▓█▓░▒▒▒▒▒▒░▒▒▓▓▒░░▒▒▒▒▒▒▒▒▒▓█ ▓█▓▒▒▒▒▒▒░▒▓████▓▒░▒▒▒▒▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒██ ░██▒▒▒▒▒▒▒░░▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░██ ░██░▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▓ ░▓█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓█░ ░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██░ ░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▓█████▓▒░▒▒▒▒▒▒▒▒▒▒▒▒▒██░ ░░▒██▒▒▒▒▒▒▒▒▒▒▒▒▒███████████▒▒▒▒▒▒▒▒▒▒▒▒██░░ ░░░██▒▒▒▒▒▒▒▒▒▒░▓███▒░░░░░▒▓███▒▒▒▒▒▒▒▒▒▓██░░ ░░░░██▒▒▒▒▒▒▒▒▒██▓░░▒▒▒▒▒▒▒░░▒██▒▒▒▒▒▒▒▒██░░░ ░░░░▓██▒▒▒▒▒▒▒██░▒▒▒▒▒▒▒▒▒▒▒▒▒░▓▓▒▒▒▒▒▒██▒░░░ ░░░░░███▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▓░░░░ ░░░░░░███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███░░░░░ ░░░░░░░███▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓███░░░░░░ ░░░░░░░░████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓███▓░░░░░░░ ░░░░░░░░░▒████▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓████░░░░░░░░░ ░░░░░░░░░░░▓█████▓▒▒▒▒▒▒▒▒▒▒▓█████▓░░░░░░░░░░ ░░░░░░░░░░░░░▓██████████████████▒░░░░░░░░░░░░ ░░░░░░░░░░░░░░░░▒███████████▓▒░░░░░░░░░░░░░░░
```

**Comment by neobrain** [comment]
Reactions don't work without javascript, so here goes ascii art:
```
░░░░░░░░░░░░░░░░░▒█████████▓░░░░░░░░░░░░░░░░░ 
░░░░░░░░░░░░░░░▓██████████████▒░░░░░░░░░░░░░░ 
░░░░░░░░░░░░░▒████▓▒░░░░░░▒▓████▒░░░░░░░░░░░░ 
░░░░░░░░░░░░████▒░░░░░░░░░░░░▒████░░░░░░░░░░░ 
░░░░░░░░░░░███▒░░░░░░░░░░░░░░░░▒███░░░░░░░░░░ 
░░░░░░░░░░███░░░░░░░░░░░░░░░░░░░░███░░░░░░░░░ 
░░░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░███░░░░░░░░ 
░░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░░░▓██░░░░░░░ 
░░░░░░░██▓░░░░░░░░░░░░░░░░░░░░░░░░░░███░░░░░░ 
░░░░░░███░░░░░▒░▒░▒░░░░░░░▒░▒░▒░▒░░░░██▓░░░░░ 
░░░░░▒██░▒░▒▒▒▒▒░▒░▒░▒░▒░▒░▒░▒▒▒▒▒░░░░██░░░░░ 
░░░░░██░░░▒▒▒▒▒▒▒▒▒░▒░▒░▒░▒░▒▒▒▒▒▒▒▒▒░▒██░░░░ 
░░░░██▓░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒░██▒░░░ 
░░░░██░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░██░░░ 
░░░██▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▓█▓░░ 
░░░██░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒███░░██░░ 
░░▓█▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░▒██████▓░▓█▒░ 
░░██░▒▒░░░▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░▓█████████▓░██░ 
░░██░░▒▓▒▒░░░░░░░▒▒▒▒▒▒▒░░░░███████████▓▒░██░ 
░▓█▒░░████████▓▒░░░░░░▒░░░████████▓██▒░░▒░▓█░ 
░██░░█████████████▓▒░░░░████████░░░░█▓▒▒▒▒▒█▓ 
░██░▓████████████████▓▒█████████▒░░░█▓▒▒▒▒░██ 
▒█▓░▒▓▓██░░▒██████████▒█████████▒░░░█▓▒▒▒▒░██ 
▓█▒░▒░▒██░░░███████▓█▓░█▒▓█░▓███▒░░░█▓▒▒▒▒▒▓█ 
██▒▒▒▒▒██░░░██░████░▓▓░▓▓░█████▓░░░▒█▒▒▒▒▒▒▒█ 
██░▒▒▒▒██░░░▓█████▓░█▒░▓█░▒███▓░░░░▓█▒▒▒▒▒▒▒█ 
██░▒▒▒░██░░░░▓███▓░░█▒▒▒█▒░░░░░░░░▒█▓▒▒▒▒▒▒▒█ 
██░▒▒▒▒▓█▒░░░░▒▒▒░░▓█░▒▒▓█▒░░░░░░░██░▒▒▒▒▒▒▒█ 
██░▒▒▒▒▒██░░░░░░░░▒█▒▒▒▒░▓█▓░░░░▒██▒▒▒▒▒▒▒▒▒█ 
██▒▒▒▒▒░▒██░░░░░░▒█▓▒▒▒▒▒░▒██▓▓██▓░▒▒▒▒▒▒▒▒▒█ 
██▒▒▒▒▒▒░▓██▒▒▒▒▓█▓░▒▒▒▒▒▒░▒▒▓▓▒░░▒▒▒▒▒▒▒▒▒▓█ 
▓█▓▒▒▒▒▒▒░▒▓████▓▒░▒▒▒▒▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒██ 
░██▒▒▒▒▒▒▒░░▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░██ 
░██░▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▓ 
░▓█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓█░ 
░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██░ 
░░██▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▓█████▓▒░▒▒▒▒▒▒▒▒▒▒▒▒▒██░ 
░░▒██▒▒▒▒▒▒▒▒▒▒▒▒▒███████████▒▒▒▒▒▒▒▒▒▒▒▒██░░ 
░░░██▒▒▒▒▒▒▒▒▒▒░▓███▒░░░░░▒▓███▒▒▒▒▒▒▒▒▒▓██░░ 
░░░░██▒▒▒▒▒▒▒▒▒██▓░░▒▒▒▒▒▒▒░░▒██▒▒▒▒▒▒▒▒██░░░ 
░░░░▓██▒▒▒▒▒▒▒██░▒▒▒▒▒▒▒▒▒▒▒▒▒░▓▓▒▒▒▒▒▒██▒░░░ 
░░░░░███▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▓░░░░ 
░░░░░░███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███░░░░░ 
░░░░░░░███▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓███░░░░░░ 
░░░░░░░░████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓███▓░░░░░░░ 
░░░░░░░░░▒████▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓████░░░░░░░░░ 
░░░░░░░░░░░▓█████▓▒▒▒▒▒▒▒▒▒▒▓█████▓░░░░░░░░░░ 
░░░░░░░░░░░░░▓██████████████████▒░░░░░░░░░░░░ 
░░░░░░░░░░░░░░░░▒███████████▓▒░░░░░░░░░░░░░░░
```

**Pull request merged**
