### PR TITLE
citra_qt/multiplayer: member pings support

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
**DO NOT PUT THIS ON CANARY. THIS REQUIRES A VERSION BUMP.**
The mega PR is #4468.

---

Adds member pings.

The user would be notified if the message contains "@" followed by the user's nickname or forum username. An alert would be shown, and the icon and message in the status bar would be changed. All notification is only shown if the chat window currently does not have focus.

Screenshot (just an example):
image

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4477)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
any review?

**Comment by jroweboy** [comment]
my primary concern is we are starting to cross over from "simple chat system built on existing infrastructure" to rebuilding IRC from scratch. I haven't had a chance to look at the code yet, but i'm a little leery of adding so many features to the chat when really we should be looking to migrate to self hosted IRC servers IMO

**Comment by jroweboy** [comment]
code looks pretty decent. quick read over but does this handle the case where you get a notification while the chat window is already focused? I only see the notification going away when the focus changes *to* the chat window, so if the user is already in the chat window, they'd need to click off to lose focus and then click back on to get the notification to go away.

As for the comment before about IRC, even if we went with an IRC client built in, we'd still probably want some sort of notification support, so i don't see this as terrible. But also ... i'm not really sure we'd want to make our own IRC client either... I guess we'll cross this bridge later.

**Comment by zhaowenlan1779** [comment]
@jroweboy I still believe we should get a convenient chat place for rooms.
And I think I've handled the case here:
https://github.com/zhaowenlan1779/citra/tree/302e12f0d2913250082dbcb71f2845f03cb1c82f/src/citra_qt/multiplayer/state.cpp#L213

**Pull request merged**
