### PR TITLE
Services/UDS: Implement DecryptBeaconData.

### PR DESCRIPTION
**Pull request by Subv**
This function decrypts the encrypted data tags contained in the 802.11 beacon frames.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2737)

### CODE REVIEW

**Comment by wwylele** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 476 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKoFMwKC585CBDCLFj:-KlKoFMwKC585CBDCLFk:bdv7dhj) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L476)):*
> ```cpp
> 
>     BeaconData data;
>     std::memcpy(&data, beacon_data.data(), sizeof(data));
> ```

where is `data` used? It is purely for verification?

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 501 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKn95H3_SewDFQHN3q:-KlKn95H3_SewDFQHN3r:bt0q249) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L501)):*
> ```cpp
>     Memory::WriteBlock(output_buffer_addr, nodes.data(), sizeof(NodeInfo) * nodes.size());
> 
>     IPC::RequestBuilder rb = rp.MakeBuilder(1, 0);
> ```

Given there is an output buffer returned, this should be likely `rp.MakeBuilder(1, 2)`, with a static buffer descriptor pushed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737)*

**Comment by B3n30** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 467 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKqKMrtyHPpLyHlZ1r:-KlKqKMrtyHPpLyHlZ1s:b-npq14r) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L467)):*
> ```cpp
> 
>     // Read the encrypted data.
>     // The first 4 bytes are the OUI and the OUI Type of the tags, we can ignore those.
> ```

I'm not sure, but shouldn't the tags be checked? Just to verify that they are the correct ones. They should probably always be the same, but just in case they are not, it could be really hard to find the error why the code fails, if they won't get checked here.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 476 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKpSBGfUNR8FmxqIyA:-KlKpSBGfUNR8FmxqIyB:b-hywlfx) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L476)):*
> ```cpp
> 
>     BeaconData data;
>     std::memcpy(&data, beacon_data.data(), sizeof(data));
> ```

nit: I think data is a very generic name and since the word 'data' is used very often in this section maybe you should go with a different name, e.g. beacon_header?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737)*

**Comment by Subv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 467 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKqKMrtyHPpLyHlZ1r:-KloBdGbN7mhQYcuQhVo:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L467)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

I'm not sure, but shouldn't the tags be checked? Just to verify that they are the correct ones. They should probably always be the same, but just in case they are not, it could be really hard to find the error why the code fails, if they won't get checked here.
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 476 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKoFMwKC585CBDCLFj:-Klo7QMJ1VT-dnjNdhao:b2nign6) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L476)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

where is `data` used? It is purely for verification?
</blockquote></details>

yes

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 476 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKpSBGfUNR8FmxqIyA:-KloBbsbibucWNA__1Yx:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L476)):*
<details><summary><i>Previously, B3n30 wrote…</i></summary><blockquote>

nit: I think data is a very generic name and since the word 'data' is used very often in this section maybe you should go with a different name, e.g. beacon_header?
</blockquote></details>

Done.

---

*[src/core/hle/service/nwm/nwm_uds.cpp, line 501 at r1](https://reviewable.io:443/reviews/citra-emu/citra/2737#-KlKn95H3_SewDFQHN3q:-KloBcZOU5EPk1ltfNSA:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/0f26b600db2c2ca49e7280db43adc7f64b4617ea/src/core/hle/service/nwm/nwm_uds.cpp#L501)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

Given there is an output buffer returned, this should be likely `rp.MakeBuilder(1, 2)`, with a static buffer descriptor pushed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737)*

**Comment by B3n30** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737#-:-KloJXARAuX3wgmjjrXO:bnfp4nl)*

**Comment by wwylele** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737#-:-KloZ_Qmm1Jr-C7x_NEf:bnfp4nl)*

**Comment by wwylele** [comment]
Please do clang-format

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2737#-:-KloZjN7H60DmEBsJxDg:bfb0ffb)*

**Pull request merged**
