### PR TITLE
shader_jit/tests: Add additional shader-jit tests

### PR DESCRIPTION
**Pull request by Wunkolo**
Add some more expansive tests for each of the shader-instructions for
regression-testing. `MAD`/`MADI` is not added due to an upstream bug in
nihstro:

https://github.com/neobrain/nihstro/issues/68

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6648)

### CODE REVIEW

**Comment by GPUCode** [comment]
How were the expected results verified? Aside from that LGTM, thanks for the extra tests!

**Comment by GPUCode** [comment]
What are those cases where the JIT differs from PICA?

**Comment by Wunkolo** [comment]
https://github.com/citra-emu/citra/pull/6648/files#diff-566073892a6d0498bdfd91d52101a9f7942a861faac247406ad2cdf9ac2e64f2R346

https://github.com/citra-emu/citra/pull/6648/files#diff-566073892a6d0498bdfd91d52101a9f7942a861faac247406ad2cdf9ac2e64f2R371

**Comment by GPUCode** [comment]
I think that above all we should strive to match the PICA behaviour, if it doesn't make sense. So maybe it would be better to adjust these tests to expect the pica result.

**Comment by SachinVin** [comment]
Agreed, we can't just comply with IEEE behavior just because it is better, e.g., many games rely on PICA's non-compliant multiplication to properly render. 

I am fine with testcases that don't agree with hardware as long as it is properly documented.

**Comment by Wunkolo** [comment]
> So maybe it would be better to adjust these tests to expect the hw accurate result.

The commented out tests are based on PICA hardware-results. The two I mentioned are commented out because the JIT currently fails them, unless we want to uncomment them now and let those tests fail until another PR addresses the issue.

**Comment by GPUCode** [comment]
I misunderstood your comment, appologies. Yeah lets keep them commented to keep the tests passing, cause I think failures might affect the CI

**Review by GPUCode — APPROVED** [review]

**Pull request merged**
