### PR TITLE
ci: Generate universal macOS build.

### PR DESCRIPTION
**Pull request by Steveice10**
Updates the CI to generate a universal macOS build for both x86_64 and arm64.

This PR updates some of the citra build system to better support multiarch builds. Architecture-specific code guards have been moved out from the CMake files into source files using architecture defines so that the correct code can be chosen for each arch, and the remaining architecture checks have been updated to allow for multiple specified architectures.

There are still some issues with how the CryptoPP and LibreSSL builds do platform detection that can cause the ARM64 parts of the build to fail, so I disabled ASM on those for now. Will likely need to be revisited later but I couldn't figure out a straightforward fix. Open to any suggestions.

Depends on https://github.com/citra-emu/citra/pull/6233 for switching to upstream dynarmic. Advances to a newer commit with support for macOS multiarch builds.

Working universal Vulkan branch builds: https://github.com/Steveice10/citra/actions/runs/3861375075

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6240)

### CODE REVIEW

**Comment by SachinVin** [comment]
Have you tested this? From what I remember using dynamic doesn't get built when using `CMAKE_OSX_ARCHITECTURES="x86_64;arm64"`

**Comment by Steveice10** [comment]
You are correct, I'm still getting a Vulkan build made for full testing as the mainline branch with OpenGL can't load a game on Mac, so I haven't been able to fully test yet. I do see what you mean from the build output though. Let me mark this as draft for now and will mark as ready when I've got a working Vulkan build to share.

**Comment by merryhime** [comment]
Support for universal builds pushed to dynarmic <https://github.com/merryhime/dynarmic/commit/6b41b5be07d51d8b1e2103782bb28d4873a3ebfa>.

**Comment by Steveice10** [comment]
Thanks, have updated to take care of that as well as making some changes to Citra itself for multi-arch build support. Have updated the PR description with the details.

Also have working builds with the Vulkan branch included that I've tested for both x86_64 (via Rosetta) and arm64: https://github.com/Steveice10/citra/actions/runs/3856451363

**Comment by SachinVin** [comment]
I personally dislike using `#ifdef` while relying on it being defined inside a header, as it is very much prone to "oops I forgot to include the header, and now the macro is not defined" and the build could silently pass. I like how [PPSSPP does it](https://github.com/hrydgard/ppsspp/blob/master/ppsspp_config.h#L6), but if you think there is a simpler or better way to do it, feel free to implement it that instead.

**Comment by Steveice10** [comment]
Updated:
* Shaved ~7 minutes off the build setup time by streamlining Homebrew installs. Some of the Python stuff was no longer necessary on the current GitHub Actions instances, and in general the set of packages that need to be installed is a lot smaller now.
* Changed architecture checks to use a function macro. Thanks for the tip on that, was worried a bit about forgotten includes myself but didn't know about the trick of using a function macro for that.

**Pull request merged**
