### PR TITLE
Decentralize ResultCode

### PR DESCRIPTION
**Pull request by yuriks**
At some point we noticed that keeping all possible descriptions in a central enum doesn't make much sense. This PR makes the description a mostly free-form integer, and does a general pass of defining result codes in a central location for a few modules.

(God, the kernel is super inconsistent in what error codes they return. It's ridiculous.)

Probably easier to review each commit.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2716)

### CODE REVIEW

**Comment by Subv** [comment]
Ref #2101

**Comment by Subv** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 10 of 10 files at r3, 2 of 2 files at r4, 21 of 21 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2716)*

**Comment by yuriks** [comment]
Rebased on top of #2718 and #2406

**Comment by wwylele** [comment]
Mostly LGTM. just some nit

---

Reviewed 31 of 31 files at r6, 3 of 3 files at r7, 10 of 10 files at r8, 2 of 2 files at r9, 23 of 23 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/common/bit_field.h, line 155 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktJM5BqEjY5Iy6CSi9:-KktJM5BqEjY5Iy6CSiA:bx2ldm2) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/common/bit_field.h#L155)):*
> ```objc
>             return (T)(((StorageType)value << (shift - position)) >> shift);
>         } else {
>             return (T)(((StorageType)value & mask) >> position);
> ```

`(StorageType)` is not neeeded

---

*[src/core/hle/kernel/address_arbiter.cpp, line 78 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktM3dc9cc-qaHUiFb8:-KktM3dc9cc-qaHUiFb9:b-uc378m) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/address_arbiter.cpp#L78)):*
> ```cpp
>     default:
>         LOG_ERROR(Kernel, "unknown type=%d", type);
>         return ERR_INVALID_ENUM_VALUE_FND;
> ```

I assume this error code change is intentional and is tested/RE-d ?

---

*[src/core/hle/kernel/errors.h, line 27 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktN3RBtOcqweIEF1Jn:-KktN3RBtOcqweIEF1Jo:b1kix4e) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L27)):*
> ```objc
> constexpr ResultCode ERR_OUT_OF_HANDLES(ErrCodes::OutOfHandles, ErrorModule::Kernel,
>                                         ErrorSummary::OutOfResource,
>                                         ErrorLevel::Permanent); // 0xD8600413
> ```

I assume the level change is verified?

---

*[src/core/hle/kernel/errors.h, line 80 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktNSB-JZi1shldjE3d:-KktNSB-JZi1shldjE3e:b-ef5hj3) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L80)):*
> ```objc
>                                          ErrorSummary::InvalidArgument,
>                                          ErrorLevel::Permanent); // 0xD8E007F6
> constexpr ResultCode ERR_INVALID_HANDLE(ErrorDescription::InvalidHandle, ErrorModule::Kernel,
> ```

The original code has a TODO with it: `// TOOD: Verify code`. Is this already verified?

---

*[src/core/hle/kernel/errors.h, line 95 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktMHC-BaUm9JPv599r:-KktMHC-BaUm9JPv599s:bmm6czn) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L95)):*
> ```objc
>                                              ErrorSummary::InvalidArgument,
>                                              ErrorLevel::Permanent); // 0xD8E007FD
> constexpr ResultCode ERR_TIMEOUT(ErrorDescription::Timeout, ErrorModule::OS,
> ```

Should this prefixed with `ERR_`? This is at `Info` level and has the highest bit cleared (which is considered as "no error")

---

*[src/core/hle/kernel/errors.h, line 98 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktMjk_4f7N9S7wdsAn:-KktMjk_4f7N9S7wdsAo:b-dsa7ve) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L98)):*
> ```objc
>                                  ErrorSummary::StatusChanged, ErrorLevel::Info);
> 
> } // namespace Kernel
> ```

New line at the end

---

*[src/core/hle/service/fs/archive.cpp, line 56 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktP9YI6HjQOsCckxMo:-KktP9YI6HjQOsCckxMp:bme5c01) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/service/fs/archive.cpp#L56)):*
> ```cpp
> // TODO: Verify code
> /// Returned when a function is passed an invalid handle.
> const ResultCode ERR_INVALID_HANDLE(ErrorDescription::InvalidHandle, ErrorModule::FS,
> ```

So this is not used anywhere and can be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2716#-:-KktQIfjM82hu5O3k6mo:b9dnfdc)*

**Comment by yuriks** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/common/bit_field.h, line 155 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktJM5BqEjY5Iy6CSi9:-KkxgknDZuEdgLq92RGL:bvty8h9) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/common/bit_field.h#L155)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

`(StorageType)` is not neeeded
</blockquote></details>

Done. Not even sure why I added that...

---

*[src/core/hle/kernel/address_arbiter.cpp, line 78 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktM3dc9cc-qaHUiFb8:-KktSGHVuJrWgy5wKezg:b-gcoxwd) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/address_arbiter.cpp#L78)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

I assume this error code change is intentional and is tested/RE-d ?
</blockquote></details>

Yep, RE'd

---

*[src/core/hle/kernel/errors.h, line 27 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktN3RBtOcqweIEF1Jn:-KkxfQ38GGWshOpecCNA:b2nhswv) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L27)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

I assume the level change is verified?
</blockquote></details>

Yep

---

*[src/core/hle/kernel/errors.h, line 80 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktNSB-JZi1shldjE3d:-Kkxfa1EZ6xBaVJW0JYJ:bxfapqt) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L80)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

The original code has a TODO with it: `// TOOD: Verify code`. Is this already verified?
</blockquote></details>

Sort of. I looked and it turns out that this and ERR_INVALID_HANDLE_OS are used at random in places where handles are checked. I didn't go through and audit every usage of the code to check if it was correct. I don't think it's that important.

---

*[src/core/hle/kernel/errors.h, line 95 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktMHC-BaUm9JPv599r:-Kkxi41HzIVis8o4PxWK:b-wyksuv) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L95)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

Should this prefixed with `ERR_`? This is at `Info` level and has the highest bit cleared (which is considered as "no error")
</blockquote></details>

Good catch. I changed it to "RESULT_TIMEOUT", you think that seems ok?

---

*[src/core/hle/kernel/errors.h, line 98 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktMjk_4f7N9S7wdsAn:-KkxiBEdWWFs6dRU0ncD:b-896fix) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/kernel/errors.h#L98)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

New line at the end
</blockquote></details>

Done.

---

*[src/core/hle/service/fs/archive.cpp, line 56 at r11](https://reviewable.io:443/reviews/citra-emu/citra/2716#-KktP9YI6HjQOsCckxMo:-KkxlWv811r40gTZF7Zs:bxd39xz) ([raw file](https://github.com/citra-emu/citra/blob/d27041ae3c032c77efa641ee74fc7c5ea5cf4948/src/core/hle/service/fs/archive.cpp#L56)):*
<details><summary><i>Previously, wwylele (Weiyi Wang) wrote…</i></summary><blockquote>

So this is not used anywhere and can be removed?
</blockquote></details>

Looks like it. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2716)*

**Comment by wwylele** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r14, 1 of 2 files at r15, 23 of 23 files at r16, 1 of 1 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2716#-:-Kky9upNhUrj_qJnZoDr:bnfp4nl)*

**Pull request merged**
