### PR TITLE
shader_jit: Add optimizations up to `x86-64-v4`

### PR DESCRIPTION
**Pull request by Wunkolo**
Adds architecture-specific accelerations to some shader_jit functions up to the `x86-64-v4` ISA, including AVX, AVX512{F,VL,DQ}, SSE41, FMA.

Passes unit tests on my i9-7900x.

Verification can also be done using Intel's [Software Development Emulator](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html) to simulate ISA features not available on the host.

- - -
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/6668)

### CODE REVIEW

**Comment by Steveice10** [comment]
Out of curiosity, do you any numbers for what kind of performance uplift this brings under the instruction set supported by your system?

**Comment by Wunkolo** [comment]
I used Catch2's benchmarking framework and had each run do a simple run to purely measure execution-time, like so:
```cpp
    BENCHMARK("RSQ") {
        shader.Run(0.6f);
    };
```

Set my processor(`i9-7900x`) to a stable-state with `sudo cpupower frequency-set -g performance` and ran the benchmarks with 10,000 samples(`./tests --benchmark-samples=10000`):

`master`:
```
-------------------------------------------------------------------------------
DP3
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:139
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DP3                                          10000           564     146.64 ms 
                                        25.9626 ns    25.9364 ns    25.9945 ns 
                                        1.47057 ns      1.267 ns    1.72184 ns 
                                                                               

-------------------------------------------------------------------------------
DP4
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:159
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DP4                                          10000           574      143.5 ms 
                                        25.8088 ns     25.785 ns    25.8401 ns 
                                        1.38474 ns    1.15235 ns    1.80069 ns 
                                                                               

-------------------------------------------------------------------------------
DPH
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:179
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DPH                                          10000           226      146.9 ms 
                                         65.746 ns    65.6523 ns     65.856 ns 
                                        5.17566 ns      4.633 ns    5.79623 ns 
                                                                               

-------------------------------------------------------------------------------
LG2
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:200
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
LG2                                          10000           469     145.39 ms 
                                        31.2487 ns    31.2116 ns     31.293 ns 
                                        2.06502 ns    1.80316 ns    2.36613 ns 
                                                                               

-------------------------------------------------------------------------------
EX2
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:221
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
EX2                                          10000           422      147.7 ms 
                                        35.6337 ns    35.5771 ns    35.6983 ns 
                                        3.07511 ns    2.77924 ns    3.40582 ns 
                                                                               

-------------------------------------------------------------------------------
MUL
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:243
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
MUL                                          10000           575     143.75 ms 
                                        25.7316 ns    25.7059 ns    25.7629 ns 
                                        1.44432 ns      1.239 ns    1.69245 ns 
                                                                               

-------------------------------------------------------------------------------
RCP
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:363
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
RCP                                          10000           589     147.25 ms 
                                        24.7569 ns    24.7244 ns    24.7953 ns 
                                        1.80506 ns    1.60043 ns    2.07945 ns 
                                                                               

-------------------------------------------------------------------------------
RSQ
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:392
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
RSQ                                          10000           597     143.28 ms 
                                        24.9053 ns    24.8675 ns    24.9485 ns 
                                        2.04919 ns    1.85451 ns    2.27167 ns 
                                                                               

===============================================================================
```

`shader-jit-x86-64-v4`:
```
-------------------------------------------------------------------------------
DP3
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:139
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DP3                                          10000           573     148.98 ms 
                                        25.6082 ns    25.5901 ns    25.6323 ns 
                                        1.05593 ns   0.855651 ns    1.31413 ns 
                                                                               

-------------------------------------------------------------------------------
DP4
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:159
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DP4                                          10000           566     147.16 ms 
                                        25.9052 ns    25.8823 ns    25.9342 ns 
                                        1.30524 ns    1.10088 ns    1.55826 ns 
                                                                               

-------------------------------------------------------------------------------
DPH
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:179
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
DPH                                          10000           228      148.2 ms 
                                        65.5046 ns    65.4232 ns    65.6001 ns 
                                        4.49131 ns     3.9473 ns    5.11577 ns 
                                                                               

-------------------------------------------------------------------------------
LG2
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:200
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
LG2                                          10000           565      146.9 ms 
                                        26.5334 ns    26.5015 ns    26.5737 ns 
                                        1.82866 ns     1.5504 ns    2.18556 ns 
                                                                               

-------------------------------------------------------------------------------
EX2
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:221
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
EX2                                          10000           523     146.44 ms 
                                        28.7991 ns    28.7647 ns    28.8405 ns 
                                        1.91881 ns    1.68575 ns     2.1867 ns 
                                                                               

-------------------------------------------------------------------------------
MUL
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:243
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
MUL                                          10000           607     145.68 ms 
                                        25.2094 ns    25.1826 ns    25.2413 ns 
                                        1.49667 ns    1.30919 ns    1.72056 ns 
                                                                               

-------------------------------------------------------------------------------
RCP
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:363
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
RCP                                          10000           594      148.5 ms 
                                        24.8444 ns    24.8139 ns    24.8808 ns 
                                        1.70099 ns    1.50065 ns    1.93432 ns 
                                                                               

-------------------------------------------------------------------------------
RSQ
-------------------------------------------------------------------------------
.../shader_jit_x64_compiler.cpp:392
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
RSQ                                          10000           604     144.96 ms 
                                         24.783 ns    24.7613 ns    24.8082 ns 
                                        1.19223 ns    1.04072 ns    1.39591 ns 
                                                                               

===============================================================================
```

**Review by Steveice10 — APPROVED** [review]

**Comment by Adamillo** [comment]
What's the behaviour in this PR when for example my CPU supports AVX2, FMA amd SSE4.2, but doesn't support AVX512?

**Comment by SachinVin** [comment]
It falls back to the old implementation

**Comment by vitor-k** [comment]
On a whim I plotted the means from the benchmark data you provided for easier visualization:
image

**Pull request merged**
