### PR TITLE
externals: update cubeb to 9a7a55153e7f9b9e0036ab023909c7bc4a41688b

### PR DESCRIPTION
**Pull request by valentinvanelslande**
Update cubeb to https://github.com/kinetiknz/cubeb/commit/9a7a55153e7f9b9e0036ab023909c7bc4a41688b
Commits list:
```
9a7a551 osx: check null reference before using the string (BMO 1502165).
04d58b6 osx: close the stream before calling setup (BMO 1500109)
262aea3 doc: update docs for register collection changed callback. Fixes 42
a68892d pulse: separate input output callbacks for collection changes (BMO 1498242).
ef8f8cb audiounit: separate input output callbacks for collection changes (BMO 1498242) (#465)
5066cfc tests: check correctly the audio buffer values range (BMO 1484541).  (#461)
d4b8c31 Build and link pulse rust backend if available.
4559815 audiounit: report removed devices correctly (BMO 1491152) (#463)
c6692b1 audiounit: avoid access to input buffer on playback case (#460)
b832dae (master) audiounit: Make io_side an enum class.
5c60bc0 Merge branch 'jyavenard-1489052_2'
f48857a s/OUTPUT/DEV_OUTPUT/
78ae261 Update CMake sanitizer submodule to current master.
7f3726d Only re-initialise stream on kAudioUnitErr_CannotDoInCurrentContext when an output is present. Otherwise just feed silence.
9e9f4d0 Remove unnecessary variable.
b5070a7 Don't propagate kAudioUnitErr_CannotDoInCurrentContext error, feed silence instead.
cc6c828 Don't run reinit task when one is already pending
2379583 Calculate the amount of input frames missing over the entire capture session
c381d1b Pad with silence according to the input device sampling rate.
f4968d9 Cancel reinit task when a audiounit_stream_destroy call is pending
78359c0 Attempt to reuse previous input device before falling back to the default one.
df71106 Do not attempt to destroy an aggregate device we failed to create
1b4547f Properly reset the number of frames present in the input buffer after re-creating it
c3b5045 Properly adjust the number of frames left to be processed by the resampler.
ad0d1c1 Remove unecessary locks.
0ba48ec Clear listeners once removed
44298ec Add .gitignore
d6a294c Reinit the stream if AudioUnitRender returns kAudioUnitErr_CannotDoInCurrentContext.
710df0b Ensure input is properly padded with enough silence.
12b78c0 cmake: Support GNUInstallDirs.
39b8703 audiounit: Simplify audiounit_add/remove_listener() by introducing property_listener (#451)
4b7442e audiounit: Reduce duplicate code in audiounit_stream_get_current_device (#453)
6c47043 Remove c-style cast in cubeb_resampler.cpp (#454)
8de5aae Always upmix mono to the first two channels if enough output channels are available #2
dbd6192 Always upmix mono to the first two channels if enough output channels are available
59f5cb4 Correctly retrieve the output layout on macOS < 10.12.
2968cba wasapi: Reduce timeout threshold (#447)
27be938 audiounit: new method on failed stream init to avoid deadlock (BMO 1470113). (#445)
bf2c281 cubeb_winmm.c: Don't define __MSVCRT_VERSION__.
0677b30 Fix volume handling in sndio backend
abf6ae2 osx: always access active stream count under context lock, BMO 1462210. (#442)
```

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4410)

### CODE REVIEW

**Comment by wwylele** [comment]
Could you make an update summary because it is hard to view it on github.

**Comment by valentinvanelslande** [comment]
Added commits list.

**Comment by B3n30** [comment]
Is there any of those changes relevant for Citra. Does that fix any audio issues?

**Comment by valentinvanelslande** [comment]
i opened this and #4411 to just to update externals. it's unknown if this fixes audio issues.

**Comment by zhaowenlan1779** [comment]
What's the status of this?

**Comment by valentinvanelslande** [comment]
@zhaowenlan1779 the status is ready for merge

**Pull request closed without merging**
