### PR TITLE
Memory/RasterizerCache: Ignore unmapped memory regions when caching physical regions

### PR DESCRIPTION
**Pull request by Subv**
Not all physical regions need to be mapped into the address space of every process, for example, system modules do not have a VRAM mapping.

This fixes a crash when loading applets and system modules.

In the future we'll have to figure out a way to update the page tables of other processes when caching / uncaching a region.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/2954)

### CODE REVIEW

**Comment by B3n30** [comment]
How does a 3ds behave if a app tries to access some unmapped VRAM?
Shouldn't it normally fail and only ignore it for system modules?

Maybe at least add some log, to make a search for errors possible?

**Comment by Subv** [comment]
Trying to access an unmapped memory region from the CPU will trigger an exception in the 3DS, the exception handler will then just close the app

**Comment by huwpascoe** [comment]
👍

**Comment by huwpascoe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/citra-emu/citra/2954)*

**Pull request merged**
