### PR TITLE
Fix read and write register blocks in gdbstub

### PR DESCRIPTION
**Pull request by polaris-**
Previously, the padding wasn't correctly accounted for which caused the gdbstub to read and write everything after R15 (starting with the dummy FPA registers) incorrectly, which caused CPSR to not be handled correctly. Everything appears to be working as expected with this change.

### CODE REVIEW

**Comment by yuriks** [comment]
LGTM, I'll let @Normmatt verify it works before merging.

(Btw, in the future try to keep the rename in a separate commit from the other logic changes. It makes it easier to check exactly what changed without clutter in the diff.)

**Comment by lioncash** [comment]
Seems like there's tab/space mismatches

**Comment by Normmatt** [comment]
This seems to be correct now :+1:

**Comment by yuriks** [comment]
@polaris- Can you sqush? Then I'll merge.

**Comment by bunnei** [comment]
LGTM

**Comment by polaris-** [comment]
@yuriks Done.

**Comment by Subv** [comment]
:shipit:

**Pull request merged**
