### PR TITLE
csnd_snd: Get rid of type punning

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by yuriks** [comment]
What's the point of this? The memory isn't being aliased by anything.

**Comment by lioncash** [comment]
For one, that violates alignment requirements.

**Comment by yuriks** [comment]
How? The structure will be aligned on the 3DS, so it will be aligned on the host too.

**Comment by lioncash** [comment]
You may run ubsan, and discover that no, no that isn't a guarantee.

**Comment by yuriks** [comment]
That's a bogus warning. Ubsan can't detect that a pointer has alignment due to external factors (in this case, being aligned on the proper 3DS alignment relative to the page, which is allocated with max type alignment by malloc on the host.)

**Comment by lioncash** [comment]
Do you have a source that verifies or confirms that inability?

**Comment by bunnei** [comment]
I don't really have an opinion either way on this. @lioncash and @yuriks please resolve your discussion.

**Comment by purpasmart96** [comment]
Looks a lot better imo

**Comment by bunnei** [comment]
Time's up...
Merging this one. While I agree with @yuriks in that I don't believe this matters at all, it certainly does not break anything and if it fixes some warning by some tool than ¯\_(ツ)_/¯ .. I'm tired of seeing this in our PR queue

**Pull request merged**
