### PR TITLE
citra-qt: Move config dialog code to its own directory

### PR DESCRIPTION
**Pull request by lioncash**
Moved for similar reasons as in #2362

### CODE REVIEW

**Comment by bunnei** [comment]
Missing some includes (configure_audio.h), otherwise looks fine.

**Comment by wwylele** [comment]
What's the status of this PR?

**Comment by bunnei** [comment]
Was this ever actually fixed...? Looks like the same weird travis errors were still occurring after your last update. Can you address these + rebase so we can get this merged?

**Comment by yuriks** [comment]
(Superceded by #2651)

**Pull request closed without merging**
