### PR TITLE
Misc prs

### PR DESCRIPTION
**Pull request by Astromojang**

### CODE REVIEW

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-02-17T02:34:40Z: https://github.com/citra-emu/citra/compare/0d086616d1af239b8e41b246bea3c1ef85fc907f...SeannyM:65d24ad83f68bd0ae58f015253e693bd48f3fed2

**Comment by yuriks** [comment]
??????? Why did you create this?

**Comment by Astromojang** [comment]
sorry didnt mean to :/

**Comment by SeannyM** [comment]
lol

**Pull request closed without merging**
